- assets/_config.yml
- lib/hexo/default_config.js
We should encourage people use use the ISO standard date by making it the default.
[If we really need a why...](http://xkcd.com/1179/)
> Default to using ISO-8601 date format

- lib/plugins/renderer/swig.js
- package.json
Adds support for `swig-extra`, enabling a bunch of filters and tags to the swig templating included by default.
Had some free time and this was easy to code so feel free to merge/discard as you see fit.
Explained on #1150
batch
groupby
indent
markdown
nl2br
pluck
split
trim
truncate
markdown
switch/case
> Add support for swig-extra

- lib/plugins/console/generate.js
Correct the spelling from `generatd` to `generated` for the file <https://github.com/hexojs/hexo/blob/master/lib/plugins/console/generate.js#L124> at line 124.
> Correct the spelling from generatd to generated.

- lib/hexo/post.js
- lib/hexo/render.js
- test/scripts/hexo/post.js
- test/scripts/hexo/render.js
To fix #1166, We must render tag plugins before 'post_render' filter works.
I added data.onRenderEnd field to render() and renderSync().
This field is a function that receives rendered content and returns processed content.
Now tag plugins be rendered in this function.
Please use this as material for further discussion.
> Change rendering order

- appveyor.yml
During test at AppVeyor, sometimes error occurs such like https://ci.appveyor.com/project/tommy351/hexo/build/145/job/iyx86d12grv6ficy .
About this problem, AppVeyor support said "Use npm v2" ( http://help.appveyor.com/discussions/questions/534-npm-cache#comment_35761655 ) .
So I modified appveyor.yml.
> Use npm v2.x at AppVeyor

- lib/plugins/helper/tagcloud.js
- test/scripts/helpers/tagcloud.js
If every tag has the same number of posts, tagcloud was broken because of division by zero.
Now every tag share the lowest level in this case.
* font ... smallest
* color ... same with start_color
this PR will fix #1123 .
> Fix the problem that occurs when every tag has the same number of posts.

- lib/models/category.js
- lib/models/tag.js
- test/scripts/box/box.js
- test/scripts/extend/filter.js
- test/scripts/extend/tag.js
- test/scripts/filters/new_post_path.js
- test/scripts/helpers/partial.js
- test/scripts/hexo/hexo.js
- test/scripts/hexo/locals.js
- test/scripts/hexo/render.js
- test/scripts/hexo/router.js
- test/scripts/models/asset.js
- test/scripts/models/cache.js
- test/scripts/models/category.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/models/post_asset.js
- test/scripts/models/tag.js
- test/scripts/theme_processors/config.js
I found some of test were not working.
For example...
```javascript
it('name - required', function(){
return Tag.insert({}).catch(function(err){
err.should.have.property('message', '`name` is required!');
});
});
```
If `Tag.insert({})` doesn't throw any error, `err.should.have.property` will be skipped.
So this test didn't check whether hexo throws error or not.
**modified**
added sinon.spy and calledOnce to check it.
```javascript
it('name - required', function(){
var errorCallback = sinon.spy(function(err) {
err.should.have.property('message', '`name` is required!');
});
return Tag.insert({}).catch(errorCallback).finally(function() {
errorCallback.calledOnce.should.be.true;
});
});
```
----
And I found two more problems.
One is problem of test. Please check …
> More strict error assertion

- lib/plugins/console/help.js
- package.json
- test/scripts/console/help.js
- test/scripts/console/index.js
```bash
$ hexo help list
```
Above command causes OutOfMemory.
At hexo v3.0.1, `printList(title, list)` ( https://github.com/hexojs/hexo/blob/e8e45ed0f379f975147a214fbf52b2c28a6c806a/lib/plugins/console/help.js#L59 ) has a problem.
If `list` have only one element, variable `length` becomes zero (because of the list is not sorted).
Then `while (padding--){ ... }` causes infinite loop.
Now `length` becomes length of the name of first element.
> [Bugfix] `hexo help list` command causes OutOfMemory

- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/filters/backtick_code_block.js
<raw>``` (tab)
Hello world!
</new>
The expressions like this causes a bug.
In this case, `args` in `backtickCodeBlock()` is not blank (it contains a tab character).
Then the `args` will not match both of `rAllOptions` and `rLangCaption`.
So `match` will be `null`. and we can't get `match[1]` in this case.
To fix it, I check whether `match` is `null` or not.
This pull request may solve #1228.
> Fix backtick_code_block for ignore tab character.

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
While `:title` includes subdirectories, `:name` only expands to the file name of the slug.
> Add `:name` to the list of permalink filters

- lib/plugins/helper/relative_url.js
- test/scripts/helpers/relative_url.js
Relative URLs from a subfolder to root lead to doubled slashes.
> Fix for relative url `..//`

- lib/plugins/helper/list_categories.js
- test/scripts/helpers/list_categories.js
Currently, this is handled by client-script, if needed.
> Add option to indicate current category with class name `current`

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
To avoid breaking any existing setups, create a new param which represents the title of a post.
Also, addresses #881 (as far as the problem I described there)
> Add new permalink param: `post_title`

- lib/plugins/helper/debug.js
- lib/plugins/helper/index.js
- test/scripts/helpers/debug.js
- test/scripts/helpers/index.js
Good for logging objects in theme and plugin
originally #1389
Changes to be committed:
modified:   lib/plugins/helper/debug.js
modified:   lib/plugins/helper/index.js
new file:   test/scripts/helpers/debug.js
modified:   test/scripts/helpers/index.js
> [helper] add log()

- lib/plugins/helper/url_for.js
- test/scripts/helpers/url_for.js
When user configures a prefix path as root path, urlForHelper can not resolve
url like '/archives' correctly with the prefix root path.
Resolves: #1105
> Prepend root path to urlForHelper

- lib/extend/tag.js
- lib/plugins/tag/code.js
- test/scripts/tags/code.js
fixing a bug with tag trimming which leads to incorrect indentation for some code blocks.
---
currently, when this is put inside of a codeblock:
```
return result;
}
if (tired && night){
sleep();
}
```
it will incorrectly be rendered as (approximately, can't reproduce the exact error with the github editor):
```
return result;
}
if (tired && night){
sleep();
}
```
> Correct tag trimming

- lib/plugins/helper/feed_tag.js
- test/scripts/helpers/feed_tag.js
According to the W3C, "alternative" is not a valid value for attribute "rel" on
element "link". The HTML5 standard uses <link rel="alternate" to provide an
alternate representation, such as RSS or Atom.
https://html.spec.whatwg.org/multipage/semantics.html#rel-alternate
> Fix HTML issue with RSS/Atom feeds: rel="alternate"

- lib/plugins/tag/code.js
- test/scripts/tags/code.js
this addresses issue: https://github.com/hexojs/hexo/issues/1537, adding options to override the line_number and highlight configuration options at the code block tag level
the new syntax will be:
```
{% codeblock [title] [lang:language] [url] [link text] [line_number:(true|false)] [highlight:(true|false)]%}
code snippet
{% endcodeblock %}
```
> override line_number, highlight settings at the codeblock level

- lib/plugins/helper/date.js
- lib/plugins/helper/index.js
- test/scripts/helpers/date.js
Moment.js provides a quite useful function for relative time, it would be a shame not to use it ;)
> New date helper using momentjs 'fromNow' method

- lib/plugins/tag/code.js
- test/scripts/tags/code.js
This way we can use codeblock with any of the fisrt line number , e.g. by doing :
```
{% codeblock lib/hexo/index.js first_line:418 %}
Hexo.prototype.execFilter = function(type, data, options) {
return this.extend.filter.exec(type, data, options);
};
Hexo.prototype.execFilterSync = function(type, data, options) {
return this.extend.filter.execSync(type, data, options);
};
{% endcodeblock %}
```
> Added `first_line` option to codeblock

- lib/models/tag.js
I have a post got tags like this https://gitcafe.com/magicdawn/magicdawn/raw/master/source/_posts/js-constructor-return-value.md
```
tags: 
- js
- constructor
- return
```
Cause `constructor` is a special key. `map['constructor'] === Object`, And will error `str must be string`.
> tag: fix special tag names

- lib/plugins/tag/jsfiddle.js
the fiddle iframe is not responsive in iOS safari and Chrome. By setting `scrolling="no"` makes it possible to fix this issue, by setting `width=1px; min-width=100%` in CSS. [See StackOverflow](http://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari)
> Set scrolling="no" to make iframe responsive

- lib/extend/tag.js
I found that when use the tag with space in parameter, even i wrapped it within a string literal, it do not work. For example:
> {% qnimg "image path with space" %}
when this (custom) tag is process, the arguments will become an array of
> ["image", "path", "with", "space"]
instead of 
>["image path with space"]
This is a big issue for any kind of tag ( no matter hexo native tag or custom tag plugin).
I found that the issue is, hexo simply connect all the lexical node to a string and then split it with space, this is not correct and result in the issue i mention.
So i fix it.
> Fix issue cannot correctly analyze arguments with space in tag 

- lib/extend/tag.js
> 解决code中存在类似swig语法被错误解析的问题

- lib/models/post.js
- lib/plugins/tag/img.js
- lib/plugins/tag/index.js
- test/scripts/helpers/list_archives.js
- test/scripts/helpers/list_categories.js
- test/scripts/helpers/list_posts.js
- test/scripts/helpers/list_tags.js
- test/scripts/helpers/tagcloud.js
- test/scripts/models/post.js
- test/scripts/tags/img.js
Current img tag doesn't prepend root path if it's not a slash. With
this fix, the root path will be prepend to the img src if it's not a
slash.
This fix only works for the hexo tags, does not work for the markdown
syntax of links and images. The issues of markdown links and images should
be fixed in the hexo-renderer-marked module.
Resolves: #1440
> Support root path configure for img tag

- lib/plugins/helper/css.js
- lib/plugins/helper/feed_tag.js
- lib/plugins/helper/js.js
- test/scripts/helpers/css.js
- test/scripts/helpers/feed_tag.js
- test/scripts/helpers/js.js
> Remove unneccessary refs to type attr in helper output snippets

- lib/plugins/helper/open_graph.js
Added twitter metatag image attribute.
Used the first image as twitter supports only one.
> OpenGraph: added support for twitter image attribute

- lib/theme/view.js
- test/scripts/theme/view.js
As reported in #1791, if a renderer supports precompilation, the `'after_render'` filter will not be executed after the actual rendering is done. This is different from previous version's behavior and will potentially break plugins that consume this filter.
In previous version, rendering layout `layouts/foo.ejs` will trigger `after_render:html` filter. An important use case for this behavior is that a plugin can inject `<script>` tags once per generated page dynamically based on its content. 
For example, [hexo-math](https://github.com/akfish/hexo-math) scans generated html for MathJax expressions and inject MathJax on-demand from `after_render:html`. With this behavior gone, the alternative would be modifying theme layouts directly, which is too messy and error-prone.
> Execute 'after_render' filter when rendering with precompiled renderer

- lib/plugins/tag/code.js
- test/scripts/tags/code.js
Hey, when highlight.js is disabled, `<` must be escaped otherwise HTML code is interpreted by the browser.
> codeblock tag : escape HTML code otherwise it will be interpreted by the browser

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
I think I might be one of [very few people](https://github.com/search?utf8=%E2%9C%93&q=open_graph+updated+extension%3Aejs&type=Code&ref=advsearch&l=&l=) who have ever tried to do this…
I deploy my static site from CircleCI to S3 automatically (the tool I used to actually push the files to S3 compares the MD5 hashes of the locally generated files against those in AWS and skips any that haven't change) when I push to `master` because on each build the `og:updated_time` changes it re-uploads each article.
I've worked around this by now after discovering if you set the `updated` option of the `open_graph` helper to be a string [that removes the `og:updated_time` meta tag](https://github.com/matthew-andrews/mattandre.ws/commit/1b7559837b87b56ae46536fb7e34e8addc3f3f81)…… But this feels like a …
> Add tests for og:updated_time in open_graph helper, and add ability to turn it off

- lib/theme/view.js
This checks to make sure an object is returned from `render.getRenderer(ext);`.
The following snippet changes https://github.com/hexojs/hexo/blob/master/lib/theme/processors/view.js#L18 to be something like https://github.com/hexojs/hexo/blob/master/lib/theme/processors/source.js#L28-L35, but there may be cases it doesn't properly account for.
```
exports.pattern = new Pattern(function(path) {
if (!_.startsWith(path, 'layout/')) return false;
path = path.substring(7);
var regex = /(^|\/)[\.]/;
if (regex.test(path) || common.isTmpFile(path) || ~path.indexOf('node_modules')) return false;
return {path: path};
});
```
> #1855: Addresses "TypeError: Cannot read property 'compile' of undefined" 

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
I believe `content` is a required attribute, so without it and without a description you get invalid markup.
http://htmldoctor.info/reference/html/meta.html
A suggested fix and tests ☺️
> Don't add /(?:og:|twitter:)?description/ meta tags if there is no description (invalid HTML)

- README.md
`hexo init blog` already performs `npm install`.
> Remove unnecessary `npm install` in readme

- lib/plugins/helper/search_form.js
- test/scripts/helpers/search_form.js
Chrome has deprecated and will remove results attribute for <input type="search"> in M53, see https://www.chromestatus.com/features/5738199536107520
> Remove results attribute in search form

- lib/hexo/index.js
- lib/plugins/filter/before_generate/render_post.js
- test/scripts/box/box.js
- test/scripts/filters/render_post.js
- test/scripts/hexo/hexo.js
This allows pages in the `source` folder to access properties in the `source/_data` files.
For example, in `source/index.html`:
```
<p>Hello {{site.data.foo.name}}</p>
```
> Access data files from source folder

- lib/models/post.js
- test/scripts/models/post.js
- test/scripts/tags/img.js
Fix the bug mentioned in #1812 
When the site is in subdirectory, we are suggest to have set url
as 'http://yoursite.com/child' and root as '/child/'.
But the share link in article footer will become
'http://yoursite.com/child/child/slug'.
Fix the bug by replace '/child/' by '/' in virtual link.
> Fix the wrong share link when the site is in subdirectory

- test/scripts/models/post.js
- test/scripts/tags/img.js
When the site is put in a subdirectory we have the
`url = 'http://yoursite.com/root';` and
`root = '/root/';`
But the test only set `hexo.config.root` but not `hexo.config.url`.
So the test cannot catch the bug in issue #1812 .
I cannot pass the unit test when I fix the bug.
> Fix the unit test on permalink_root_prefix - virtual

- lib/plugins/tag/jsfiddle.js
- test/scripts/tags/jsfiddle.js
在使用 jsfiddle 标签插件生成的 iframe 中的 src 地址默认是包含 `http://` 前缀的，如  `http://jsfiddle.net/xxxxxxx/embedded/result,css,html/light`
这会导致在 HTTPS 的网站中出现非 https 的内容，导致抛出警告，并且地址栏中的小锁加黄色警告标识。 jsfiddle 官方的 emmbed 插件地址已经去掉了前面的 http 前缀，所以这里可以放心的改成 `//jsfiddle.net/` 了
> 解决 jsfiddle 标签插件在 https 下报非 https 的警告

- lib/hexo/index.js
- lib/hexo/multi_config_path.js
- lib/hexo/multiconfig_path.js
- package.json
- test/scripts/hexo/index.js
- test/scripts/hexo/multi_config_path.js
Give the `--config` flag support for multiple config files when generating or serving your site.
Inspired by Jekyll as suggested by @Lindsor in #2210.
List the desired config files (JSON or YAML) in a comma-separated list (no spaces) after the config flag:
```
hexo server --config config1.yml,config2.json
```
This will combine all the config files and save the merged settings to `_multiconfig.yml`. The later values take precedence. It works with any number of JSON and YAML files with arbitrarily deep objects.
For instance, in the above example if `foo: bar` is in `config1.yml`, but `"foo": "dinosaur"` is in `config2.json`, `_multiconfig.yml` will contain `foo: dinosaur`.
> support for multiple config files (#2210)

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
It fixes #942 
Before fix: 
<meta property="og:image" content="https://example.com/blog/image.JPG">
After fix: 
<meta property="og:image" content="https://example.com/blog/2017/01/02/2017-01-02-blog-title/image.JPG">
> Fix issue #942

- lib/plugins/helper/open_graph.js
If first 200 characters have new line(s), Hexo will generate something like this:
```html
<meta name="description" content="We’ve continuously been hearing for a couple of years now that Samsung is working on foldable smartphones.
The company has a plethora of patents to its name that detail some of the technology">
```
This PR fix this little problem.
```html
<meta name="description" content="We’ve continuously been hearing for a couple of years now that Samsung is working on foldable smartphones. The company has a plethora of patents to its name that detail some of the technology">
```
> Replace new lines by spaces in description

- lib/hexo/index.js
- test/fixtures/_config.json
- test/scripts/hexo/hexo.js
> Fix multiple config issue #2518

- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
When using a custom server, I would like to store only the output of hexo's build process, and no extra dependencies, and the way I can do that is by storing the plugins in devDep and running npm install --production to get the server dependencies.
> Allow plugins to be stored as devDependencies too.

- lib/extend/tag.js
- test/scripts/extend/tag.js
This patch fixes a latent bug that causes the issue #2563.
The Pull Request #2461 (commit 5134cba97bed6ea83f1695bf054f08dc3f5f72ac) made the bug easier to be realized.
To fix the bug, change a regexp to be non-greedy.
And also add a test case and assertions.
> Fix parsing error about <code> tag (Issue #2563)

- lib/hexo/post.js
This PR adds Nunjucks disabling if the renderer claim that it can handle “tags” on its own.
Currently it is not active (i.e., Nunjucks would work) for all existing renderers.
> disable Nunjucks when the renderer spcify that

- lib/extend/tag.js
- test/scripts/extend/tag.js
nunchucks supports nested async tags.
this PR simple uses a callback function to properly chain these tags together
> enable async tags to have more nested async tags

- lib/box/index.js
- lib/hexo/default_config.js
- test/scripts/box/box.js
Example _config.yml entry.
```yaml
ignore: ['**/themes/**/node_modules/**', '**/themes/**/node_modules', '**/themes/**/.git', '**/themes/**/.git/**']
```
> feat: Ignore files from processing that are not required.

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
This OpenGraph property is optional, but generally recommended. Since Hexo has i18n it's easy to support and will provide extra detail.
The `og:locale` property content will be set according to: (in order)
1. the `language` option to the open graph helper;
2. the page lang/language;
3. the site config.
When no language is set anywhere, the og:locale attribute is not set. In that case, the OpenGraph specification uses `en_US` as default.
``` html
<meta property="og:locale" content="zh-tw">
```
> include og:locale

- test/scripts/filters/excerpt.js
MVS is removed from whitespace since Unicode 8.0.0, see http://www.unicode.org/L2/L2013/13004-vowel-sep-change.pdf
ES2016 uses Unicode 8.0.0 thus the test fails on node.js 8.4.0
- [-] Add test cases for the changes.
Blocks #2728.
> test: remove \u180e on excerpt test case

- lib/plugins/helper/link_to.js
- test/scripts/helpers/link_to.js
see https://developers.google.com/web/tools/lighthouse/audits/noopener
- [-] Add test cases for the changes.
> fix: opens external anchor using rel=noopener

- lib/hexo/load_plugins.js
Intuition says local changes should have precedence over external ones, so this enforces the following load order:
external modules -> theme scripts -> local scripts
This way, any changes made locally will surely be applied.
The motivation was a long time trying to debug something I've overwritten in a local script that wasn't running.
> Change plugins loading order

- lib/models/post.js
- lib/plugins/processor/post.js
- test/scripts/helpers/list_categories.js
- test/scripts/models/post.js
- test/scripts/processors/post.js
This implements the ability to have multiple category hierarchies attached to a single post (#848).
By default, everything works the way it currently does; a list of categories will be assembled for a single category hierarchy. The change implemented here is that, if a category is a list, `setCategories()` will switch into multiple category mode, and each top-level item in the list will be a category hierarchy itself.
```yaml
categories:
- Example 1
- Example 2
- [Example 3, Subexample 3.1]
```
This will result in four different categories assigned to the post, with three different hierarchies (`example-1`, `example-2`, and `example-3/subexample-3.1`). The category generator already created index pages for intermediate categories, so `[url]/category/example-3/` is a good URL, and would …
> 848 hierarchical categories

- .github/stale.yml
:wave: thanks for using the @probot stale app. I noticed some errors in our logs coming from this app, caused by multiple labels being used for the `staleLabel`. This is the label the app applies when an issue meets the stale criteria, so it only accepts one.
> Only one label can be used for marking

- lib/hexo/multi_config_path.js
- lib/plugins/console/config.js
- test/scripts/console/config.js
The `safeLoad` method is recommended for untrusted data. However, hexo uses `js-yaml` to parse config files handwritten by SAs. These config files should be treated as trusted data and thus we can use `load` method for flexibility. The `load` method uses `DEFAULT_FULL_SCHEMA` to support !!js/regexp or !!js/function types.
This commit does not introduce breaking change as `DEFAULT_FULL_SCHEMA` is a superset of `DEFAULT_SAFE_SCHEMA`, which is defaults of `safeLoad`.
> feat(config): use yml.load to support custom js types

- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
Plugins should be sourced from all available options, meaning both dependencies and devDependencies.  In the current implementation (#2558), plugins are only loaded from devDependencies *if there are no dependencies*.
> Actually allow plugins to be stored as devDependencies

- lib/plugins/tag/asset_img.js
- test/scripts/tags/asset_img.js
This change reuses `img` plugin within the `asset_img`. Thanks to this, we can use more flexible syntax:
`{% asset_img [class names] slug [width] [height] [title text [alt text]]%}`
If Google Translate is right, this PR is related to #2275.
> Reuse img in asset img

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/helper/link_to.js
- test/scripts/filters/external_link.js
- test/scripts/helpers/link_to.js
Rel "external" switched to "noopener" for security best practices.
See https://developers.google.com/web/tools/lighthouse/audits/noopener (and other related documentation) for more info on this threat.
- [V] Add test cases for the changes.
- [V] Passed the CI test.
> Rel external switched to noopener

- lib/plugins/tag/asset_img.js
- test/scripts/tags/asset_img.js
solving #2123
- plugin img tag resolve root path twice 
on `lib/plugin/tag/asset_img.js`
```
args[i] = url.resolve(ctx.config.root, asset.path);  << first 
```
and on `lib/plugin/tag/img.js`
```
function makeUrl(path) {
if (path[0] === '#' || path.substring(0, 2) === '//') {
return path;
}
var data = url.parse(path);
if (data && data.protocol) {
return path;
}
path = config.root + path;
return path.replace(/\/{2,}/g, '/'); << second
}
```
I think there is no reason to prefix root config twice.
> fix bug: remove dupliated root path when using asset_img tag

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Fixes https://github.com/hexojs/hexo/issues/2809.
Leaves other Open Graph meta tags @ 200 characters
> Limit meta description length to 160 characters

- package.json
- test/scripts/hexo/hexo.js
> Mocha version upgrade 2.5.3 to 4.0.1

- lib/plugins/console/generate.js
- test/scripts/console/generate.js
Add defaults to console command `generate`.
Related to [#Issue](https://github.com/hexojs/hexo/issues/2851)
> fix: Add defaults to console command generate

- lib/plugins/helper/paginator.js
When I use `paginator` function like this:
`paginator({
space: "",
end_size: 0,
mid_size: 2,
prev_text: " ",
next_text: " "
})`, then in `/page/2`, the page nums in `nav` tag whose class name is `page-nav` will be 2, 3, 4.
I think the corrent display should be 1, 2, 3, 4.
> Fix a bug then pages display more reasonable.

- lib/models/post.js
- test/scripts/models/post.js
When set `relative_link` to `true` in `config.yml`, the `post.permalink` will incrrect.
For example:
When `config.url` is `http://yoursite.com/` and the post's path is `2017/09/a-post` ,the result will `http://yoursite.com2017/09/a-post` . It misses a separator `/` after the site url.
This pull request aims to repair this problem.
> fix a bug that post.permalink error when config.relative_link is true

- lib/models/post_asset.js
- test/scripts/models/post_asset.js
Fixes #2134
Closes #2551
Closes #2504
cc @Alex1990 @changyuheng
> fix(post-asset): strip /\.html?$/ extensions on permalink

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Reverts hexojs/hexo#2810
As discussed in #2809, the user should be able to decide how to use the meta description.
> Revert "Limit meta description length to 160 characters"

- appveyor.yml
- test/scripts/box/file.js
This reverts commit a2184229232a9893179b43475f344c556ec4d956.
Since https://github.com/nodejs/node/pull/16705 is merged, the hotfix is unecessary.
#	test/scripts/box/file.js
> Revert "hotfix(file): cast dev to uint32"

- .travis.yml
Update dist of travis to `trusty`. Better boot time according to https://docs.travis-ci.com/user/reference/overview/
> chore(travis): update dist to trusty

- .lintstagedrc
- package.json
This PR introduces pre-commit hook to run eslint autofix on staged .js files. Most of time you will not waste your time adding whitespace or commas after you draft a PR and the travis fails due to style issues. No more, it is frustrating and tedious. We really treasure your time.
In this time you simply draft your ideas and let `eslint` fix most style issues for you on commit, you just sit and don't have to run `eslint` after you revise files.
`git-exec-and-restage` is less popular but it proves pretty handy over half a year coporate trial. Basically `git-exec-and-restage` will only run `git add` on fully staged file. It runs linter on partially staged file and it depends on you to commit the style changes of specific hunks later.
> chore(package): add lint-staged eslint autofix

- .eslintrc.json
Most of the rules done in the previous PR have been set to [eslint-config-hexo@2](https://github.com/hexojs/eslint-config-hexo).
Both of these are based on [jscs-preset-hexo](https://github.com/hexojs/jscs-preset-hexo), so there are many duplicate settings.
Therefore, it is not intentional that settings not overwritten from eslint-config-hexo will remain.
(That is, the rest are adjustments for the purpose of avoiding errors.)
> Delete duplicate eslint rule not overwritten

- lib/hexo/multi_config_path.js
- package.json
Fixes https://github.com/hexojs/hexo/issues/2966
- [Compatible with old ones. Runned and verified] Add test cases for the changes.
> Deep assign replaced with lodash merge

- lib/plugins/console/generate.js
[`new Buffer()` is Deprecated API from node.js v6 or later.](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html#buffer_new_buffer_string_encoding)
[`Buffer.from()` is also implemented in Node.js v4 LTS.](https://nodejs.org/docs/latest-v4.x/api/buffer.html#buffer_class_method_buffer_from_str_encoding)
see https://nodejs.org/docs/latest-v4.x/api/buffer.html#buffer_new_buffer_array
> change Buffer API

- lib/plugins/tag/include_code.js
This PR is to align `include_code` with `code` options
> include_code – add hljs option

- lib/plugins/renderer/plain.js
Just some typo fixes in `lib/plugins/renderer/plain.js`.
> Fix typos in plain.js

- lib/hexo/index.js
- lib/hexo/load_plugins.js
- package.json
Adding full support for [Yarn Workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) requires some more work on the [hexo-cli](https://github.com/hexojs/hexo-cli) package. These are some tasks required before this PR should be merged.
> Yarn Workspaces

- package.json
After I update to Hexo 3.6.0, `hljs` option still doesn't work, I found the version of `hexo-util` is "^0.6.0", but `hexo-util` doesn't support `hljs` option until "0.6.3"(https://github.com/hexojs/hexo-util/releases/tag/0.6.3).
After I update the version to "0.6.3", It works.
> Fixes: hljs option still doesn't work.

- lib/plugins/filter/template_locals/i18n.js
- test/scripts/filters/i18n_locals.js
Use default language when no language set, or there is no translation for specified language
If no language is set in _config, or the theme has no language file for the one set, then the translation data is chosen in indeterminate manner as it is taken from a list of all available translations returned by hexo.theme.i18n#list().
The changes to lib/plugins/filter/template_locals/i18n.js use i18n.languages in preference to config.language and i18n.list() as this provides an array of configured languages with 'default' on the end.  This ensures that if no language is set or the language cannot be found then then default translation will be used.
The changes to test/scripts/filters/i18n_locals.js set i18n.languages rather than config.language as the original test code did not set the …
> Use default language when no language set

- lib/plugins/console/clean.js
- test/scripts/console/clean.js
Related to #2436 
It allows injecting code to the `hexo clean` command to
let plugin developers perform additional clean up.
> Add after_clean filter

- lib/plugins/filter/template_locals/i18n.js
- test/scripts/filters/i18n_locals.js
Issue #3108 points out that many existing themes rely on the old but incorrect way of selecting language files prior to the pull request #3069 which fixes the incorrect behaviour.
This PR makes a small change so that when no language is configured and no default language file exists then the fallback is to use the old method of selecting a language file rather than not selecting any file.
A single test has been added to confirm that the first language file added will be used as the fallback.
> Use old language file selection when no default file exists

- lib/plugins/console/generate.js
- lib/plugins/filter/before_post_render/backtick_code_block.js
- lib/plugins/renderer/swig.js
- lib/plugins/tag/code.js
- lib/plugins/tag/include_code.js
> Do not use arguments object

- lib/plugins/filter/index.js
- lib/plugins/filter/meta_generator.js
This implements the `meta generator injection` feature. For more information, see Miscellaneous section of [Hexo 4.0 Roadmap](https://github.com/hexojs/hexo/issues/2492), and https://github.com/hexojs/site/pull/649.
> Misc: add meta generator injection filter

- lib/hexo/multi_config_path.js
- test/scripts/hexo/multi_config_path.js
Update to support absolute paths to config files. 
Commit checklist:
> updated config loader to accept absolute paths to config files

- lib/box/index.js
- lib/extend/tag.js
- lib/hexo/index.js
- lib/hexo/load_config.js
- lib/hexo/multi_config_path.js
- lib/plugins/console/generate.js
- lib/plugins/filter/index.js
- lib/plugins/filter/meta_generator.js
- lib/plugins/filter/template_locals/i18n.js
- lib/plugins/helper/css.js
- lib/plugins/helper/is.js
- lib/plugins/helper/js.js
- lib/plugins/helper/list_categories.js
- lib/plugins/helper/tagcloud.js
- lib/plugins/helper/url_for.js
- lib/plugins/tag/img.js
- lib/theme/processors/source.js
- test/scripts/hexo/multi_config_path.js
And String#indexOf() with String#includes()
> Replace String#substring() with String#startsWith() or String#endsWith()

- appveyor.yml
Node.js v9 is already EOL.
Drop v9 and support v10 on AppVeyor.
> Drop node.js v9 and support v10 on AppVeyor

- test/scripts/box/file.js
- test/scripts/console/config.js
- test/scripts/filters/backtick_code_block.js
- test/scripts/helpers/toc.js
- test/scripts/hexo/load_config.js
> Fix test: Reduce lodash depend code

- lib/plugins/filter/meta_generator.js
- test/scripts/filters/index.js
- test/scripts/filters/meta_generator.js
Fix #3313. Related to #3129.
1. When a third-party plugin uses cheerio 1.0.0-rc.1+, `<html><head><body>` are automatically added to every empty or open tag (see https://github.com/cheeriojs/cheerio/issues/1031 https://github.com/cheeriojs/cheerio/issues/1239). If I have `<p>`, it will results in,
```html
<html><head></head><body><p></body></html>
```
2. meta_generator.js prepend meta generator tag to every `<head>`. e.g.
```html
<html><head><meta name="generator"...></head><body><p></body></html>
```
3. Those extra `<html><head><body>` are stripped away in the final `$.html()`, leaving
```html
<meta name="generator"...><p>
```
As a workaround, meta_generator.js prepend only to non-empty _real_ `<head>`. I assume Hexo page has at least meta charset or css in the `<head>`.
Without this …
> fix: compatibility with cheerio 1.0.0+ (#3313)

- lib/box/index.js
- lib/extend/filter.js
- lib/extend/tag.js
- lib/hexo/index.js
- lib/hexo/render.js
- lib/hexo/router.js
- lib/hexo/source.js
- lib/models/tag.js
- lib/models/types/moment.js
- lib/plugins/console/deploy.js
- lib/plugins/console/generate.js
- lib/plugins/console/list/index.js
- lib/plugins/console/migrate.js
- lib/plugins/generator/asset.js
- lib/plugins/helper/css.js
- lib/plugins/helper/debug.js
- lib/plugins/helper/js.js
- lib/theme/index.js
`Function#call()` and `Function#apply()` can express assertion that it converts `this` value more clearly by converting it to `Reflect.apply()`.
> Use Reflect.apply()

- package.json
Update husky from 0.14.3 to 1.1.3 and change husky's script, because it [has breaking change in v1.0.0](https://github.com/typicode/husky#upgrading-from-014)
This PR divided from (#3277)
> chore(husky): update husky to 1.1.3

- lib/plugins/tag/blockquote.js
The blockquote built-in plugin is too large as a single function.
Also, most of the code concerns only footer output.
Therefore, we will create a new `parseFooter()` to reduce complexity.
> Spread function: Hexo built-in plugin blockquote

- package.json
This PR divided from (#3277)
Sinon breaking changes in 5.x , 6.x and 7.x is only removed `spt.reset()`. But this repositories doesn't using `spy.reset()`.
Please see sinon migrate guide.
* [4.x to 5.x](https://sinonjs.org/guides/migrating-to-5.0)
* [5.x to 6.x](https://sinonjs.org/guides/migrating-to-6.0)
6.x to 7.x migration guide nothing, but I  confirmed [7.x](https://github.com/sinonjs/sinon/blob/d193bb932bd03b587a661bbb74cc6772f2e6941f/docs/changelog.md#700--2018-10-14) change logs. It seems nothing breaking changes.
> chore(package): update sinon to 7.1.1

- lib/box/index.js
- lib/extend/tag.js
- lib/hexo/index.js
- lib/hexo/post.js
- lib/hexo/render.js
- lib/hexo/router.js
- lib/hexo/scaffold.js
- lib/models/cache.js
- lib/plugins/console/config.js
- lib/plugins/console/deploy.js
- lib/plugins/console/generate.js
- lib/plugins/console/list/index.js
- lib/plugins/console/new.js
- lib/plugins/console/publish.js
- lib/plugins/filter/before_exit/save_database.js
- lib/plugins/filter/before_generate/render_post.js
- lib/plugins/generator/asset.js
- lib/plugins/helper/list_archives.js
- lib/plugins/helper/list_categories.js
- lib/plugins/helper/list_posts.js
- lib/plugins/helper/list_tags.js
- lib/plugins/helper/paginator.js
- lib/plugins/helper/tagcloud.js
- lib/theme/processors/config.js
- lib/theme/view.js
> Refactor self

- package.json
This PR divided from (#3277)
The rewire 4.0.0 has two breaking changes.
One is drop nodejs v4. This hexo repository already set node-engines higher 6.9.0, so we don't worry this breaking change.
Another one is potentially breaking, sorry I can not be say absolutely no problem, but unit test are passed. I think may be no problem.
* [rewire 4.0.0](https://github.com/jhnns/rewire/releases/tag/v4.0.0)
> chore(package): update rewire to 4.0.1

- package.json
Update major version of strip-ansi package dependency.
The strip-ansi between 4.0 and 5.0 seems no [breaking change](https://github.com/chalk/strip-ansi/compare/c299056a42b31d7a479d6a89b41318b2a2462cc7...dfab6777144e0292c7b4be9969c180025d7d2d97). I think we can update major version of it.
> chore(package): update strip-ansi to 5.0.0

- lib/hexo/index.js
Even if the current `Hexo#_generate()` is divisible as an internal API, it still is big and feels chaotic.
This PR aims to divide `_generate()` and make the behavior clearer.
> Spread function: Hexo#_generate()

- lib/hexo/index.js
`Locals.prototype.site` were deleted in (#3359)
`hexo generate` command has error, If theme or others use `this.site.xxxxx`.
```
ReferenceError: \themes\tranquilpeak\layout\all-categories.ejs:116
115|     <section class="boxes">
>> 116|         <% site.categories.sort('name').each(function(category) { %>
117|             <% if (!category.parent) { %>
118|                 <%- displayCategories(category) %>
119|             <% } %>
site is not defined
at eval (eval at compile (C:\Users\N.Yoshinori\work\site\_main\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:123:8)
at returnedFn (C:\Users\N.Yoshinori\work\site\_main\node_modules\ejs\lib\ejs.js:653:17)
at Theme._View.View._compiled.locals [as _compiled] (C:\Users\N.Yoshinori\work\site\_main\node_modules\hexo\lib\theme\view.js:123:48)
at …
```
> fix site is not defined error

- .travis.yml
- appveyor.yml
This PR adds nodejs 10 as well as 11
node 10 will become the next lts
node 9 was an intermediate release
and add tests on linux for appveyor
See https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/#running-windows-and-linux-builds-side-by-side
and 
https://github.com/nodejs/Release#release-schedule
> update build matrix

- package.json
Specified size so that we will not publish package lock files to npm.
Before: 86.2 kB (308.5 kB)
After: 54.2 kB (199.5 kB)
> chore(package): specify files to shrink package size

- lib/plugins/tag/include_code.js
- test/scripts/tags/include_code.js
> feature: include ranged code lines

- .github/PULL_REQUEST_TEMPLATE.md
The idea is to help new contributors and Hexo team to have more information to accept PRs. Anyone can help test with the instructions.
---
---
Is this good? 👍🏻👎🏻 @hexojs/core @hexojs/founder 
If you like this maybe I can add it to every project in the future.
~~- [ ] Add test cases for the changes.~~
> PR template with more information

- lib/hexo/load_plugins.js
I use hexo with TypeScript, and fixed an issue with using TypeScript declaration module of any hexo-plugin.
In `load_plugins.js`, hexo shoud not load module started with `@types/`
`@types/*` is module of TypeScript Declaration File.
https://github.com/DefinitelyTyped/DefinitelyTyped/
That contains no js code, only type declaration file `*.d.ts`, so hexo will fail to load it as plugin.
```
ERROR Plugin load failed: @types/hexo-util
Error: EISDIR: illegal operation on a directory, read
```
One of TypeScript declaration module's naming is as follows.
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package
> If you are adding typings for an NPM package, create a directory **with the same name**.
The name of any plugin's type declaration file necessarily contains `hexo-`.
And …
> Ignore plugins whose name is started with "@types/"

- lib/plugins/helper/partial.js
- test/scripts/helpers/partial.js
Fixes: https://github.com/hexojs/hexo/issues/3384
> throw error on missing partial

- lib/plugins/helper/toc.js
Signed-off-by: Richard Lea <chigix@zoho.com>
> feat(toc): seek anchor id from parent nodes when target is not available

- .github/stale.yml
Update stale bot setting.
Some question issue seems closeable. But, issue reporters are not close them. Also maybe they will not close in the future.
Current stale bot do not close issue if issue added question label. IMHO this setting is no need.
No need.
> chore(stale): update stale exemptLabels setting

- package.json
- test/fixtures/post_render.js
Update devDeps. Somehow hexo-renderer-marked@1 results in extra new lines.
Supersede #3548 
```sh
git clone -b marked https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```
> chore(deps-dev): update hexo-renderer-marked requirement from ^0.3.0 to ^1.0.1

- .gitignore
- .travis.yml
- package.json
istanbul has been [deprecated](https://www.npmjs.com/package/istanbul) (last published 3 years ago). It is [replaced by nyc](https://www.npmjs.com/package/nyc) instead.
Current version (as of v14.1.1) [still supports](https://github.com/istanbuljs/nyc/blob/fe3311bd4770726c67e6eee1e39b15a3b616457b/package.json) Node 6.
```sh
git clone -b nyc https://github.com/weyusi/hexo.git
cd hexo
npm install
npm test
```
> chore(deps-dev): replace deprecated istanbul with nyc

- .github/stale.yml
Stale bot limit to only issue
IMHO old PR should not close automatically by stale bot.
For example #3335 
Nothing
Nothing
> chore(stale): stale bot limit to only issue

- lib/hexo/post.js
- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Fix the issue that code blocks in markdown are rendered as placeholder after disabling nunjucks
Fix the issue that "code block in markdown are not rendered correctly after set `disableNunjucks` to true", which is introduced in PR https://github.com/hexojs/hexo/pull/2593
Expected behavior: 
1. most tag plugins (nunjucks) feature should be disabled after set `disableNunjucks` to true ;
1. however, markdown features like code blocks should still work;
```sh
git clone -b master https://github.com/think-in-universe/hexo.git
cd hexo
npm install
npm test     # passed in my local test
```
To test `disableNunjucks`, we can use the [hexo-stop-tag-plugins](https://www.npmjs.com/package/hexo-stop-tag-plugins) plugin created by me. The plugin has been submitted to the plugins list via the PR …
> code block in markdown are not rendered correctly after set disableNunjucks to true

- .travis.yml
- appveyor.yml
- package.json
Drop Node 6 as per #3508 . It has [reached EOL](https://github.com/nodejs/Release) since 2019-04-30.
```sh
git clone -b drop-node6 https://github.com/weyusi/hexo.git
cd hexo
npm install
npm test
```
> chore: drop Node 6

- appveyor.yml
appveyor supports node 12 since [2019-06-14](https://www.appveyor.com/updates/2019/06/14/).
v11 is EOL since 2019-06-01.
```sh
git clone -b node-12 https://github.com/weyusi/hexo.git
cd hexo
npm install
npm test
```
> chore(appveyor): replace node 11 with 12

- lib/hexo/render.js
- lib/plugins/filter/post_permalink.js
- lib/plugins/helper/list_archives.js
- lib/plugins/helper/list_categories.js
- lib/plugins/helper/list_posts.js
- lib/plugins/helper/list_tags.js
- lib/plugins/helper/paginator.js
- lib/plugins/helper/tagcloud.js
- lib/plugins/helper/toc.js
- lib/plugins/processor/post.js
- package.json
- test/scripts/helpers/paginator.js
Update eslint to v6.
eslint@6 enable `no-prototype-builtins` rule [by default](https://eslint.org/docs/6.0.0/rules/no-prototype-builtins), which entails the refactors.
```sh
git clone -b eslint-prototype https://github.com/weyusi/hexo.git
cd hexo
npm install
npm test
```
Closes #3596
> chore(deps-dev): update eslint requirement from ^5.9.0 to ^6.0.1

- lib/box/index.js
- lib/plugins/processor/common.js
- package.json
- test/scripts/box/box.js
micromatch is a replacement of minimatch. It supports multiple patterns in an array, without string-to-array conversion, along with other globbing [features](https://github.com/micromatch/picomatch#library-comparisons). It's also [faster](https://github.com/micromatch/micromatch#latest-results) and updated much more frequently ([micromatch](https://github.com/micromatch/micromatch/commits/master) vs [minimatch](https://github.com/isaacs/minimatch/commits/master)). It's already utilized in hexo, indirectly through chokidar dep. `npm ls --depth 5` shows 4 instances of it.
Using micromatch@4 is rather drastic since it depends on Node >=8, considering other deps currently use micromatch@3. But it's not a major issue, as Node 6 will be eventually dropped (#3508).
~~Personally, I would prefer …
> refactor: switch minimatch to micromatch

- lib/plugins/filter/after_post_render/excerpt.js
- test/scripts/filters/excerpt.js
Skip excerpt generation for posts or pages if it is set in the front matter. This gives users the ability to write down whatever abstract they want instead of just showing begining part of the post.
For example:
```yaml
title: An article about blah blah blah
excerpt: This article is all about blah blah blah blah blah blah
---
Actual markdown content...
```
will generate:
```js
{
excerpt: 'This article is all about blah blah blah blah blah blah',
more: 'Actual markdown content...',
content: 'Actual markdown content...'
}
```
```sh
git clone -b BRANCH https://github.com/ppoffice/hexo.git
cd hexo
npm install
npm test
```
N/A
> feat(filter): use existing excerpt if possible

- package.json
`"scripts"` handles binaries in `./node_modules/.bin/` well, so there's no need for cli version of eslint. Most of the plugins are eslint-ed without eslint-ci just fine.
To run eslint locally, there are a few ways:
1. `$ npm run eslint`
2. `$ npx eslint .`
3. Add "./node_modules/.bin" to $PATH
```sh
git clone -b eslint-ci https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> chore(dev-deps): remove unneeded eslint-ci

- lib/hexo/default_config.js
- lib/plugins/filter/meta_generator.js
- test/scripts/filters/meta_generator.js
Add `meta_generator` option (enabled by default) to disable addition of `<meta name="generator" content="Hexo 3.9.0">`.
Fix https://github.com/hexojs/hexo/issues/3652#issuecomment-518601732
```sh
git clone -b meta-generator https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
cc @JoeyBling
> feat: add option to disable meta generator tag

- lib/hexo/default_config.js
Set default language as english. to match [the docs](https://hexo.io/docs/configuration#Site). Main purpose is to [set it in `<html>`](https://github.com/hexojs/hexo-theme-light/blob/b28cf1e9e1f3827e52cc654f59311752ca455306/layout/layout.ejs#L2), as [recommended](https://www.w3.org/International/questions/qa-html-language-declarations#attributes) by W3C.
I will update hexo-starter too. Edit: https://github.com/hexojs/hexo-starter/pull/12
```sh
git clone -b default-lang https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix: set english as default

- lib/plugins/filter/meta_generator.js
When `hexo.config.meta_generator` is `false`, return before `cheerio.load`.
Discussion: https://github.com/hexojs/hexo/issues/3663#issuecomment-521471346
- Travis CI
- [`theme-suka/hexo-theme-unit-test`](https://github.com/theme-suka/hexo-theme-unit-test) as basic hexo site
- [`hexo-theme-suka`](https://github.com/sukkaw/hexo-theme-suka)
- [`hexo-many-posts`](https://github.com/SukkaLab/hexo-many-posts): 300 posts that have 1 category, 5 tags, all markdown styles and large amounts of code blocks
- All the css, js & images are deleted before hexo clean && hexo g to make sure every file generated is rendered HTML.
Raw build log can be found [here](https://travis-ci.com/theme-suka/performance-test/builds/123322706).
**Test A**
- The latest master branch of Hexo from …
> fix: performance improvements when meta_generator is disabled

- test/scripts/helpers/open_graph.js
After https://github.com/hexojs/hexo/pull/3654, `language:` defaults to `en`, thus no longer empty by default.
```sh
git clone -b locale https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> test(open_graph): language is 'en' by default

- lib/plugins/console/generate.js
- lib/plugins/console/index.js
- test/scripts/console/generate.js
Allow users to set the number of files to be generated in parallel.
Users who are struggling with the "out of memory" problem (e.g., #3350 #3311) can limit Hexo's memory usage by `hexo g --concurrency <number>`.
1. `hexo init` a new blog.
2. change the `hexo` dependency to `ppoffice/hexo#master` in `package.json`
3. `npm install`
4. Add some posts `git clone https://github.com/SukkaLab/hexo-many-posts.git source/_posts/tests `
5. `hexo g -c <number of concurrent tasks>`
- **hexo**: https://github.com/ppoffice/hexo#master
- **theme**: landscape
- **hexo-cli**: 2.0.0
- **os**: Linux 5.0.0-21-generic linux x64
- **node**: 12.4.0
- **node_flags**: --max-old-space-size=8192
- No concurrency limit
- 659 files generated in 24 s
- Memory usage: 500 ~ 660 MB
- 20 concurrent tasks at most
- 659 …
> Solve "Out of memory" during generation by limiting the number of concurrent tasks

- lib/plugins/filter/meta_generator.js
- test/scripts/filters/meta_generator.js
- test/scripts/hexo/render.js
Less breaking alternative to https://github.com/hexojs/hexo/pull/3669
x-post from that PR:
> From the [benchmark](https://github.com/hexojs/hexo/issues/3663#issuecomment-521488465) performed by @SukkaW , we can see cheerio—used by meta_generator filter—incurs significant perf cost. The feature was initially introduced by https://github.com/hexojs/hexo/pull/3129.
> Despite effort to improve the situation (https://github.com/hexojs/hexo/pull/3667), the improvement was only minuscule. Hence, we try to avoid cheerio if possible.
```sh
git clone -b metagen-cheerio https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> perf(meta_generator): drop cheerio

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
cheerio is slow and we only use that to parse and list img in post.content. This PR drop cheerio and use regex to do the job.
```sh
cd hexo
npm install
npm test
```
https://github.com/hexojs/hexo/pull/3680/commits/913f5bed0d39cacda66479bd58345992b64cfb8d
| | NodeJS 8 | NodeJS 10 | NodeJS 12 |
|:---:|:---:|:---:|:---:|
| cheerio@0.22 (hexojs/hexo#master) | **7.12** | 6.96 | 6.86 |
| regex (This PR) | 7.15 | 6.96 | **6.78** |
| dom-parser (#3679) | 7.2 | 6.93 | 6.82 |
| conditional cheerio (#3670) | 7.15 | **6.92** | **6.78** |
https://github.com/hexojs/hexo/pull/3680/commits/4f86ddef8f8f70193c4b590ac35d0eaad9028237
| | NodeJS 8 | NodeJS 10 | NodeJS 12 |
|:---:|:---:|:---:|:---:|
| cheerio@0.22 (hexojs/hexo#master) | 7.03 | 6.59 | 6.51 | …
> refactor(open_graph): drop cheerio and use regex

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Remove `twitter:title` and `twitter:description` which is duplicated with `og:title` and `og:description`
According to the [Twitter Card Docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html):
> When using Open Graph protocol to describe data on a page, it is easy to generate a Twitter card without duplicating tags and data. When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property.
SInce the value of `twitter:title` and `twitter:description` is the same as `og:title` and `og:description`, they can be removed.
```sh
cd hexo
npm install
npm test
```
> fix(open_graph): remove duplicate twitter card tags

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
```sh
cd hexo
npm install
npm test
```
> if post.title is empty, set it to post.slug

- lib/plugins/filter/meta_generator.js
Only a minor changes, use template string instead of `replace()`.
```sh
git clone -b meta-generator https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(meta_generator): use template string

- lib/plugins/filter/meta_generator.js
- test/scripts/filters/meta_generator.js
After #3671 & #3696 , meta_generator filter will replace `</title>` with `<meta name="generator" content="Hexo ${hexo.version}"></title>`.
@curbengh [has mentioned](https://github.com/hexojs/hexo/pull/3696#issuecomment-526819260) some [edge cases](https://github.com/hexojs/hexo/pull/3696#issuecomment-526822365) will cause unwanted behavior:
```html
<html>
<head>
<style>
.foo {
background: url(data:image/svg+xml;utf8,<svg width="500" height="300" xmlns="http://www.w3.org/2000/svg"><g><title>svg</title></g></svg>);
}    
</style>
<title>TITLE</title>
</head>
...
</html>
```
This PR introduce replacing `</head>` with `<meta name="generator" content="Hexo ${hexo.version}"></head>` with [a pattern](https://regex101.com/r/4yIsOT/1/) that [ignore empty `<head>` …
> refactor(meta_generator): update regex and avoid edge case

- lib/plugins/helper/full_url_for.js
- lib/plugins/helper/index.js
- test/scripts/helpers/full_url_for.js
- test/scripts/helpers/index.js
https://github.com/hexojs/hexo-util/pull/84
Returns a url with the `config.url` prefixed.
**Use Case 1**
`link[canonical]` tag, which is one of a best practice for SEO, needs an absolute url of current page.
According to [the test carried out by theme NexT team](https://github.com/theme-next/hexo-theme-next/pull/1143#issuecomment-526828133):
> `{{ page.permalink }}` works on every page exclude index and archive page.
> `{{ url }}` is everywhere.
A `full_url_for(page.path)` can be used in this case.
**Use Case 2**
Use url to share the post at social media, which is similar to the first case:
- Sina Weibo `http://service.weibo.com/share/share.php?appkey=&title=[title]&url=[url]&pic=[site logo]&searchPic=false&style=simple`
- Twitter `https://twitter.com/intent/tweet?text=[title]&url=[url]` …
> feat(full_url_for): utilize hexo-util module

- lib/hexo/default_config.js
- lib/models/category.js
- lib/models/page.js
- lib/models/post.js
- lib/models/tag.js
- test/scripts/models/category.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/models/tag.js
Currently `permalink` variable of post, page, tag, category may end with "index.html". This PR adds `canonical_url` option to remove that. `canonical_url` defaults to false to avoid breaking change.
This is useful for SEO when web server (including `hexo server`) rewrite "index.html", so the url without it is the canonical version.
This way, plugins that use post.permalink don't need to remove it. Tested with [hexo-generator-sitemap](https://github.com/hexojs/hexo-generator-sitemap).
Related:
- https://github.com/hexojs/hexo-generator-sitemap/pull/59
- https://github.com/hexojs/hexo-generator-sitemap/issues/13
Note this PR doesn't cover `this.url`(https://github.com/hexojs/hexo/pull/3661).
```sh
git clone -b canonical https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
``` …
> feat(permalink): add pretty_urls option to remove index.html from url

- lib/hexo/index.js
- lib/models/category.js
- lib/models/page.js
- lib/models/post.js
- lib/models/tag.js
- lib/plugins/helper/url_for.js
- test/scripts/hexo/hexo.js
- test/scripts/models/category.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/models/tag.js
While working on https://github.com/hexojs/hexo-generator-sitemap/pull/68 and https://github.com/hexojs/hexo-generator-feed/pull/93, I find it strange that plugins have to encode url themselves.
I believe url should be [safe to consume](https://www.ietf.org/rfc/rfc1738.txt) by default. I can't think of any reason to use `this.url` in its original unescape form, except for aesthetic when displaying as a text, e.g. show http://foo.com/一二三 instead of http://foo.com/%E4%B8%80%E4%BA%8C%E4%B8%89
Displaying a full link as text should be considered as an edge case. In that case, it should be up to the user to decode it (we could write a helper to help).
Do note link inside `href` is decoded when mouse-over.
``` html
<a href="http://xn--fo-8ja.com/b%C3%A1r%20ab/">aaaaaaaaaaaaa</a>
```
It's a …
> fix: encode url and permalink by default

- lib/plugins/tag/asset_link.js
- lib/plugins/tag/post_link.js
- test/scripts/tags/asset_link.js
- test/scripts/tags/post_link.js
When the title contains `<,>,"` characters, it will cause some errors on browsers.
e.g.
the titles are
- `this is a title with <a tag>.`
- `this is a title with " class="badname`
```
- {% post_link test1 %}
- {% post_link test2 %}
```
generates to
```
<li><a href="/posts/test1/" title="this is a title with <a tag>.">this is a title with </a><a tag="">.</a></li>
<li><a href="/posts/test2/" title="this is a title with " class="badname">this is a title with " class="badname</a>
</li>
```
use `util.escapeHTML` function escape the titles.
how to use `post_link` with `escape` option:
```javascript
/**
* Post link tag
*
* Syntax:
*   {% post_link slug [title] [escape] %}
*/
escape = true or omit; // escape
escape = false; // do not escape
```
e.g.
```ejs
- {% post_link test1 %}
- {% post_link …
```
> fix post_link, asset_link when title contains <,>," charaters

- lib/plugins/helper/paginator.js
- package.json
- test/scripts/helpers/paginator.js
- test/scripts/tags/link.js
htmlTag in hexo-util@1.3.0 onward escape html tag and encode url by default. This PR adds trailing slash to expected value of `href`; trailing slash is added by encodeURL() of html-util.
In paginator helper,
- `spaceHtml` is not escaped to avoid double escaping the '&hellip;'.
- add `escape` option (enabled by default). Closes https://github.com/hexojs/hexo/issues/3729
```sh
git clone -b escape-html https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(paginator): compatibility with hexo-util@1.3.0

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Uses canonical url (the one that doesn't end with `index.html`) for open graph tags.
```sh
git clone -b ograph-canonical https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(open_graph): remove index.html from url

- lib/models/cache.js
- test/scripts/box/box.js
A current `modified` field mixed  `UnixTime` and `ISO8601`.
It seems `modified` field [expect to use UnixTime](https://github.com/hexojs/hexo/blob/2ed17cd105768df379dad8bbbe4df30964fe8f2d/lib/models/cache.js#L10) but `stats.mtime` return `ISO8601` format.
Migrates to warehouse `v3.0` test failure (#3736)  caused by this type of diff.
Because before warehouse `v3.0`, the warehouse `replaceById` method [return UnixTime](https://github.com/hexojs/warehouse/pull/19/files/b203b7c7a7178e46146ac3d7e02d8e17eea5a6e4#diff-a140b60b6a99a8c69f4b5d0d1f1f2bfaR333) forcibly.
```sh
cd hexo
npm install
npm test
```
Nothing
> fix(mtime): Use UnixTime at all of the modified fields

- lib/hexo/index.js
- lib/plugins/helper/tagcloud.js
Issue resolved: #3622
Categories / tags of draft are displayed / counted in non-draft generate.
In hexo-theme-next, we tried to filter out the categories / tags in the draft, but this caused performance issues.
More information:
theme-next/hexo-theme-next#42
theme-next/hexo-theme-next#87
```sh
git clone -b master https://github.com/stevenjoezhang/hexo.git
cd hexo
npm install
npm test
```
> Ignore categories / tags with zero posts

- lib/plugins/helper/relative_url.js
- lib/plugins/helper/url_for.js
- lib/plugins/tag/asset_img.js
- lib/plugins/tag/asset_link.js
- lib/plugins/tag/asset_path.js
- lib/plugins/tag/post_link.js
- lib/plugins/tag/post_path.js
- test/scripts/helpers/relative_url.js
- test/scripts/helpers/url_for.js
- test/scripts/tags/asset_img.js
- test/scripts/tags/asset_link.js
- test/scripts/tags/asset_path.js
- test/scripts/tags/post_link.js
- test/scripts/tags/post_path.js
Continuation of https://github.com/hexojs/hexo/pull/3708, this PR deals with helpers and tag plugins.
```sh
git clone -b encode-url-helper https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(helpers, tag plugins): encode url by default

- lib/plugins/helper/open_graph.js
- package.json
- test/scripts/helpers/open_graph.js
- test/scripts/tags/asset_img.js
root/path value should be percent-encoded, not html escaped.
``` yml
_config.yml
url: https://日本語テストgôg.com/hexô-testing
```
``` html
<meta property="og:url" content="https://&#x65E5;&#x672C;&#x8A9E;&#x30C6;&#x30B9;&#x30C8;g&#xF4;g.com/hex&#xF4;-testing/index.html">
```
``` html
<meta property="og:url" content="https://xn--gg-8ja8200c3ban0926g0ecl32k.com/hex%C3%B4-testing/index.html">
```
```sh
git clone -b url-encoding https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(open_graph): percent-encode url, not html escape

- package.json
Closes #3758 
This is mainly to update the warehouse in the CI, as user usually would get the latest minor/patch version of each dependency.
```sh
git clone -b warehouse-3-0-1 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> chore(deps): update warehouse from ^3.0.0 to ^3.0.1

- lib/hexo/post.js
- test/scripts/hexo/post.js
When backtick code block(s) exist as contents of a "blockquote" tag plugin,
each code block is translated to a string "undefined" in HTML (Issue #2318).
In analyzing markdown source text, while the replacement of these elements
with placeholders are nesting, recoveries from placeholders are executed
only once.  So I modify to repeat the recovery process until all
placeholders are recovered.
NOTE: From Pull Request #2319, I correct the condition of exception (accept empty string as escape content).
> Allow backtick code block in "blockquote" tag plugin (#2318)

- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/hexo/post.js
Fix #2969 
This patch makes the filter "backtick_code_block" to remove '>' characters at the head of each line.
How many '>' characters should be removed?
It is decided by the number of '>' characters at the first line.
This patch works well even if there are too few '>' characters at the head of a line.
(Simply removes all '>' characters less than or equal to the number of '>' characters at the first lines.)
Note that this patch works well for a "lang=dos" or "lang=cmd" code block.
The body of these code blocks is usually starting with '>' (DOS prompt).
This patch keeps it if it follows '>' characters which is the same number of the first line.
For example,
`````
> Hello
> 
> ```dos
> > dir
> ```
`````
is rendered to:
`````
<p>Hello</p>
<blockquote>
<pre><code>&gt; dir</code></pre> …
```
> Correct processing of backtick code block on blockquote (fix Issue#2969)

- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Fix #3767
A paragraph follows a backtick code block on a blockquote should be included same blcokquote block.
But the code block always terminates blockquote.
So the blockquote block splits two blocks.
This is caused by the implementation of `backtick_code_block.js`.
It inserts extra new line character into the end of backtick code block.
This patch disables this behavior.
```sh
$ npm test
```
> Disable to insert extra new line character into the end of backtick code block (fix #3767)

- package.json
Closes #3508 , Closes #3611
```sh
git clone -b 4.0.0 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
Pending deps (in hexo):
Pending deps' PR:
hexo-starter needs to be updated once this is merged but **before** publish.
> release: 4.0.0

- lib/extend/console.js
- lib/extend/filter.js
- lib/hexo/index.js
- lib/hexo/locals.js
- lib/hexo/post.js
- lib/hexo/router.js
- lib/plugins/console/config.js
- lib/plugins/console/list/route.js
- lib/plugins/helper/format.js
- lib/plugins/helper/fragment_cache.js
- lib/theme/index.js
- test/scripts/console/config.js
- test/scripts/hexo/load_config.js
https://github.com/hexojs/eslint-config-hexo/pull/22
ref: https://eslint.org/docs/rules/no-multi-assign
```sh
git clone -b no-multi-assign https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```
> style: no-multi-assign

- .eslintrc.json
- lib/plugins/filter/after_render/meta_generator.js
- package.json
- test/scripts/filters/meta_generator.js
Fix https://github.com/hexojs/hexo/issues/3777
BREAKING CHANGE: requires Node >= 8.10
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll
- https://node.green/#ES2018-features
```sh
git clone -b meta-gen-fix https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> fix(meta_generator): handle multi-line head tag correctly

- .travis.yml
Current [.travis.yml](https://github.com/hexojs/hexo/blob/52adf3913ac7eab26607722b6edca6685f184567/.travis.yml) are specified which distribution should use. And it's `ubuntu 14.04 (Xenial)`. It's too old.
Now, the TravisCI uses [Ubuntu 16.04(Xenial)](https://docs.travis-ci.com/user/reference/overview/#linux) by default.
I prefer to use the latest `18.04 (bionic)`. But, it very costally for us if we specify all repo's `.travis.yml` dist version. IMHO we should use the default to save our maintain time.
> [travis.yml list of specified dist](https://github.com/search?l=YAML&q=org%3Ahexojs+dist&type=Code)
Nothing
> ci: delete distribution version at travis.yml

- .travis.yml
- test/benchmark.sh
Add a `benchmark.sh` under `test` directory, used to perform benchmark for every build on travis ci, which enables us to evaluate the generation speed after each commit.
```sh
git clone -b benchmark https://github.com/sukkaw/hexo.git
cd hexo
npm install
./test/benchmark.sh
```
> ci: bring up benchmark

- lib/hexo/index.js
Continuation of https://github.com/hexojs/hexo/pull/3754. Inspired by https://github.com/hexojs/warehouse/pull/52.
Using lebab as suggested by @deepnum mentioned in that PR, this PR simply `lebab --transform class index.js -o class.js` and then hoist the arrow functions to the top; I might miss something.
Other files in [/lib/hexo](https://github.com/hexojs/hexo/tree/master/lib/hexo) can be refactored to this style as well, but since each file has >100 lines, I prefer to do each of them in a separate PR for easier review.
```sh
git clone -b refactor-class https://github.com/refactor-class/hexo.git
cd hexo
npm install
npm test
```
Tested on a test blog (both hexo g & s).
> refactor(hexo/index.js): Class syntax

- test/scripts/hexo/multi_config_path.js
Delete `/tmp/_multiconfig.yml` file at the end of the test.
Otherwise, the test will fail when other users on the same server run the test.
```sh
git clone -b fix-multiconfig-test https://github.com/dailyrandomphoto/hexo.git
cd hexo
npm install
npm test
npm test
```
> fix(test): delete /tmp/_multiconfig.yml file at the end of the test.

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
`article:published_time` and `article:modified_time` are listed in the [Open Graph](https://ogp.me/) spec. The spec doesn't include `og:updated_time` (removed in more recent spec?), but somehow it's widely adopted (thanks to [Yoast](https://kb.yoast.com/kb/getting-open-graph-for-your-articles/)?).
Edit: `og_updated_time` has been deprecated, hence it's not included in the spec. This PR replaces it with `article:modified_time`.
```sh
git clone -b og-updated https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
>  feat(open_graph): add article:published_time & article:modified_time

- lib/plugins/tag/iframe.js
- lib/plugins/tag/jsfiddle.js
- lib/plugins/tag/vimeo.js
- lib/plugins/tag/youtube.js
- test/scripts/tags/iframe.js
- test/scripts/tags/vimeo.js
- test/scripts/tags/youtube.js
Add `loading="lazy"` to iframe to enable native lazyload which is already supported by Chrome.
See https://github.com/scott-little/lazyload .
```sh
cd hexo
npm install
npm test
```
> Add lazyload to iframe related tags

- .travis.yml
[Node 13](https://github.com/nodejs/Release) is released a few days ago. Specify versions for clarity.
Use newer syntax for npm caching. The option is retained so that it's easy to disable, even though it's enabled [by default](https://docs.travis-ci.com/user/caching/#npm-cache).
Alternative syntax is `cache: npm`, but having a boolean is clearer.
```sh
git clone -b ci-node-13 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> ci: add node 13 and updating caching option

- lib/plugins/helper/index.js
- lib/plugins/helper/meta_generator.js
- test/scripts/helpers/index.js
- test/scripts/helpers/meta_generator.js
This is a continuation of #3669 
```sh
git clone -b meta_generator https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat: meta_generator helper

- lib/plugins/tag/iframe.js
- lib/plugins/tag/jsfiddle.js
- lib/plugins/tag/vimeo.js
- lib/plugins/tag/youtube.js
- test/scripts/tags/iframe.js
- test/scripts/tags/jsfiddle.js
- test/scripts/tags/vimeo.js
- test/scripts/tags/youtube.js
1. Always use https for jsfiddle, vimeo and youtube
2. create tag using [`htmlTag()`](https://github.com/hexojs/hexo-util#htmltagtag-attrs-text-escape). A benefit is that it encodes url and escapes unsafe values by default.
```sh
git clone -b https-frame https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(iframe_tags): utilize htmlTag function

- lib/hexo/post.js
This PR is a part of #3753
```sh
git clone -b drop-lodash-for-lib-hexo-post https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```
> refactor: drop lodash for lib/hexo/post

- lib/box/index.js
- test/scripts/box/box.js
Disable `fs.watch()` for dirs/files which are specified by `ignore` option in `_config.yml`.
This patch is supplement to #2631.
Fix #2179, #1316, hexojs/hexo-server#45.
And also, maybe mitigate #2090, hexojs/hexo-server#21.
```sh
npm test
```
> Disable fs.watch() for dirs/files specified by "ignore" option

- lib/plugins/filter/template_locals/i18n.js
This PR is a part of #3753.
```sh
git clone -b drop-for-lodash-for-filter-i18n https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: drop lodash for i18n filter

- lib/plugins/helper/css.js
- test/scripts/helpers/css.js
This is mainly to add [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (SRI) to `<layout>`, though arbitrary attributes are supported as well.
Existing syntax is still supported (credit to https://github.com/hexojs/hexo/pull/3681#issuecomment-524648521).
Supported syntax:
- `<%- css('layout.css') %>`
- `<%- css(['layout.css', 'gallery.css']) %>`
- `<%- css({href: 'layout.css', integrity: 'hash-value'}) %>`
- `<%- css({href: 'layout.css', integrity: 'hash-value'}) %>`
- `<%- css({href: 'layout.css', integrity: 'hash-value'}, {href: 'gallery.css', integrity: 'hash-stuff'}) %>`
- `<%- css([{href: 'layout.css', integrity: 'hash-value'}, {href: 'gallery.css', integrity: 'hash-stuff'}]) %>`
- `<%- css([{href: 'layout.css', integrity: …
> feat(css_helper): add support for custom attributes

- lib/plugins/helper/js.js
- test/scripts/helpers/js.js
This is mainly to add [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) (SRI) to `<script>`, though arbitrary attributes are supported as well.
Existing syntax is still supported (credit to https://github.com/hexojs/hexo/pull/3681#issuecomment-524648521).
Supported syntax:
- `<%- js('script.js') %>`
- `<%- js(['script.js', 'gallery.js']) %>`
- `<%- js({src: 'script.js', integrity: 'hash-value'}) %>`
- `<%- js({src: 'script.js', integrity: 'hash-value', async: true}) %>`
- `<%- js({src: 'script.js', integrity: 'hash-value'}, {src: 'gallery.js', integrity: 'hash-stuff'}) %>`
- `<%- js([{src: 'script.js', integrity: 'hash-value'}, {src: 'gallery.js', integrity: 'hash-stuff'}]) %>`
- `<%- js([{src: 'script.js', integrity: 'hash-value', defer: …
> feat(js_helper): add support for custom attributes

- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/hexo/post.js
fix #3769
Blank lines in backtick code block on blockquote should be kept.
But `backtick_code_block.js` removes them.
This patch fixes this behavior.
This bug is introduced by the PR #3765
```sh
npm test
```
> Keep blank lines in backtick code block on blockquote (fix #3769)

- lib/plugins/filter/new_post_path.js
This PR is part of #3753 
```sh
git clone -b drop-lodash-for-new-post-path https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: drop lodash for new-post-path filter

- .eslintrc.json
- lib/hexo/index.js
- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
- lib/plugins/filter/after_render/meta_generator.js
- lib/plugins/helper/toc.js
- lib/plugins/tag/img.js
- test/scripts/filters/external_link.js
- test/scripts/filters/meta_generator.js
- test/scripts/hexo/multi_config_path.js
`no-useless-concat` somehow is not enforced in recent commits.
I also remove rules override in `.eslintrc.json` for consistency across hexo projects.
Removing rules override is also in preparation for [prettier](https://github.com/hexojs/eslint-config-hexo/pull/25) to avoid conflicting rules (e.g. [[1]](https://github.com/prettier/prettier-eslint/issues/186), [[2]](https://github.com/prettier/prettier/issues/3806)).
```sh
git clone -b no-useless-concat https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> style: no-useless-concat & one-var (uninitialized)

- lib/plugins/filter/before_exit/save_database.js
- test/scripts/filters/save_database.js
After run `hexo` commands such as `hexo --version`, `hexo new`, 
the content of `db.json' file was cleared.
It is inconvenient for a site with a lot of posts.
This PR fixes this issue by saving the database only when the database was loaded.
```sh
git clone -b fix-save-database https://github.com/dailyrandomphoto/hexo.git
cd hexo
npm install
npm test
```
```sh
git clone https://github.com/hexojs/site.git
cd site
vi package.json
```
Change the version of hexo.
```diff
- "hexo": "hexojs/hexo"
+ "hexo": "dailyrandomphoto/hexo#fix-save-database"
```
Install and generate site.
```sh
npm install
npm run build
```
Check out the `db.json` file.
```
hexo --version
hexo new page "somepage"
```
Check out the `db.json` file.
The content of `db.json` should not be cleared.
> fix(save_database): should not clear database when use 'hexo new', 'hexo --help', etc.

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
Add hour and minute for the post permalink.
Edit _config.yml file
```yml
permalink: :year/:month:day:hour:minute
```
> Add hour and minute for the post permalink.

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Recently tested hexo.io against [facebook linter](https://developers.facebook.com/tools/debug/og/object/). Apparently, the value for "og:locale" must be in [`language_TERRITORY`](https://ogp.me/#optional) format, so "en" is invalid. Here is a list of [valid values](https://developers.facebook.com/docs/messenger-platform/messenger-profile/supported-locales/).
If `og:locale` is not specified, fb defaults to "**en_US**".
(The following note is only applicable if you're not using en-US locale. It's optional for en-US users.)
If the `language` value (regardless from config or front matter) is not in `language-TERRITORY` format, "og:locale" **will not be added**.
If the language value in _config is just two characters (e.g. "en", "fr"), then you need to append territory value, e.g. "en-GB", …
> fix(open_graph): locale must in language_TERRITORY format

- package.json
- test/scripts/helpers/open_graph.js
- test/scripts/hexo/hexo.js
- test/scripts/models/category.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/models/tag.js
- IDN now always output in unicode, regardless the source is unicode or punycode, after https://github.com/hexojs/hexo-util/pull/116
- category and tag uses chinese word because diacritic is [escaped](https://github.com/hexojs/hexo-util/blob/71bbcc49cafdfce094c226a0612de5895d576848/lib/slugize.js#L15) by default (`á` -> `a`); once escaped, it's not percent-encoded anymore so couldn't cover the url encoding test.
- expected result now uses dynamic result of encodeURL()/full_url_for() instead of hardcoded, this allows compatibility with any changes in `encodeURL()`.
```sh
git clone -b hexo-util_1.5 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> test: compatibility with hexo-util@1.5.0

- test/scripts/filters/backtick_code_block.js
Part of https://github.com/hexojs/hexo/issues/3753
```sh
git clone -b refactor-clonedeep https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(backtick_code): replace cloneDeep with Object.assign()

- lib/plugins/console/new.js
- test/scripts/console/new.js
When use `hexo new` command with `-p`, `-s` or `-r` options, unexpected properties('s:', 'r:') are generated in the front-matter.
e.g.
```sh
hexo new "Hello" -s "test" 
hexo new "Hello" -r
hexo new "Hello" -s "test" -r
```
It should generate the same as when using `--slug`, `--replace` options.
e.g.
```sh
hexo new "Hello" --slug "test" 
hexo new "Hello" --replace
hexo new "Hello" --slug "test" --replace
```
Make new a hexo site for test.
e.g.
```sh
git clone https://github.com/hexojs/site.git
cd site
vi package.json
```
Change the version of hexo.
```diff
- "hexo": "hexojs/hexo"
+ "hexo": "dailyrandomphoto/hexo#fix-create-new-post"
```
```sh
npm install
```
The two commands should generate the same properties in the front-matter.
```sh
hexo new "Hello1" --slug "test1" --replace
hexo new …
```
> fix(new): omit 'p:', 's:', 'r:' properties in fromt-matter

- lib/hexo/default_config.js
- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/filters/backtick_code_block.js
Continuation of https://github.com/hexojs/hexo-util/pull/112.
Alternative (less breaking than`hljs: true`) approach to https://github.com/hexojs/hexo/issues/3766
`wrap` is currently enabled by default, so codeblock is wrapped in `<table>`; disable it for simpler/shorter `<pre><code>`.
All credit to @seaoak 
```sh
git clone -b highlight-wrap https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> feat(backtick): support 'wrap' option

- test/scripts/hexo/load_config.js
This PR is part of #3753 
IMHO, since it is only about unit test, it is fine to use `JSON.parse(JSON.stringify())` to replace `cloneDeep()` without concerning about performance.
```sh
cd hexo
npm install
npm test
```
> test(load_config): drop lodash

- lib/box/index.js
- test/scripts/box/box.js
Fix issue #3873
When an individual (non-directory) file matches the glob in `ignore:` option,
it will be ignored (not process, not copy to `publish/` folder).
`fs.watch()` already ignores it by the PR #3797.
But Hexo still processes it.
This patch fixes this behavior.
```sh
git clone -b feature/enable_ignore_option_for_individual_file https://github.com/seaoak/hexo.git
cd hexo
npm install
npm test
```
> Enable to use "ignore:" option for individual files (fix #3873)

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Utilize hexo-util's `escapeHTML()`, and deprecate obsoluted `&apos;`.
```sh
git clone -b open_graph_escape https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(open_graph): utilize escapeHTML()

- lib/hexo/index.js
This PR is part of #3753 
This PR only replace `cloneDeep` and `debounce` with native while `lodash` itself retains exposed to global.
```sh
git clone -b drop-lodash-for-index https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
The performance is more or less the same after this PR.
> refactor: drop lodash for lib/hexo/index.js

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
Optimize the regexp used in external_link filter. The new regexp will avoid edge cases like `a` prefixed tag `<article>`, and it is faster ([benchmark](https://repl.it/repls/StableVioletMonotone) shows it is 18% faster).
```sh
git clone -b external_link_regex https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(external_link): optimize regex pattern

- lib/plugins/tag/code.js
- test/scripts/tags/code.js
Continuation of https://github.com/hexojs/hexo/pull/3827
```sh
git clone -b codeblock-wrap https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> feat(codeblock): add 'wrap' option

- lib/plugins/processor/asset.js
- lib/plugins/processor/common.js
- lib/plugins/processor/post.js
- test/scripts/processors/post.js
Fix #3881
`exlucde:` option and `include:` option in `_config.yml` is no effect for files in Asset Folder.
These are only effect for files outside of `source/_post/`
(such as `source/foo.jpg`, `source/foo/bar.jpg`).
This behavior does not match its document.
https://hexo.io/docs/configuration#Include-Exclude-Files-or-Folders
This patch fixes this behavior.
```sh
git clone -b feature/enable-exclude-and-include-options-for-files-in-asset-folder https://github.com/seaoak/hexo.git
cd hexo
npm install
npm test
```
> Enable "exclude:" and "include:" options for files in asset folder (fix #3881)

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
https://github.com/hexojs/hexo/pull/3808 introduces a :chicken: :egg: issue; setting "language" (like "en") prevent `og:locale` from being inserted, setting "language-TERRITORY" (like "en-GB") breaks theme's multilingual/i8n support.
This PR fixes that by assuming default locales.
Based on Facebook's [official list](https://developers.facebook.com/docs/messenger-platform/messenger-profile/supported-locales/).
```sh
git clone -b og-locale-backward https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(open_graph): set default locales

- lib/hexo/default_config.js
- lib/models/category.js
- lib/models/page.js
- lib/models/post.js
- lib/models/tag.js
- package.json
- test/scripts/models/category.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/models/tag.js
Continuation of https://github.com/hexojs/hexo/pull/3691.
Utilize `prettyUrls()` introduced in https://github.com/hexojs/hexo-util/pull/152 (credit @SukkaW)
Supersede #3893
When `pretty_urls.trailing_html` is disabled, permalink like `example.com/foo/bar.html` is transformed into `example.com/foo/bar`.
The option doesn't apply to url with trailing `index.html`, e.g. `example.com/foo/bar/index.html`. I don't think `example.com/foo/bar/index/` is valid.
```sh
git clone -b pretty_urls-util https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> feat(permalink): pretty_urls.trailing_html

- lib/hexo/load_config.js
- lib/hexo/multi_config_path.js
- package.json
#3753
This is only a PoC of lodash.merge replacement. If this PR doesn't have huge performance impact, we should bring up a `deepMerge()` in `hexo-util`.
```sh
git clone -b drop-lodash-for-config https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: drop lodash.merge

- lib/plugins/helper/meta_generator.js
- test/scripts/helpers/meta_generator.js
https://github.com/hexojs/hexo/issues/3919#issuecomment-563575110
```sh
git clone -b meta-gen https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(meta_generator): parse correct version

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
`permalink_defaults` option does not work correctly from 4.1.0.
According https://hexo.io/docs/permalinks, set `_config.yml` as
```yaml
permalink: :lang/:title/
permalink_defaults:
lang: en
```
```
$ hexo new "Hello World" --lang tw
```
and the URL will be:
```
http://localhost:4000/tw/hello-world/
http://localhost:4000/en/hello-world/
```
Compare v4.0.0 and v4.1.0,
I found the related change is https://github.com/hexojs/hexo/commit/e0f2478ef431cccb1d30d92d2d0c47d6f195675b#diff-dbb03cb234189f8e709e7c5f9921aa67L45  (#3790) 
```diff
- return permalink.stringify(defaults(meta, config.permalink_defaults));
+ return permalink.stringify(Object.assign(meta, config.permalink_defaults));
```
If change to
```js
Object.assign([], config.permalink_defaults, meta)
```
it causes "Maximum call stack …
> fix(postPermalinkFilter): permalink_defaults should not overwrite values

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
Handle potential `null` for `config.permalink_defaults`.
```sh
git clone -b permalink-filter-null https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix(permalink_filter): handle null config

- lib/box/index.js
- lib/hexo/default_config.js
- test/scripts/box/box.js
Continuation of https://github.com/hexojs/hexo/pull/3797
Supersedes and closes https://github.com/hexojs/hexo-starter/pull/30 cc @dailyrandomphoto 
Related: https://github.com/hexojs/hexo/issues/3885 https://github.com/hexojs/hexo-server/issues/45 https://github.com/hexojs/hexo-server/issues/43
cc @Shen-Yu 
1.
``` diff
package.json
-  "hexo": "^4.1.0",
+  "hexo": "curbengh/hexo#ignore-theme-node",
```
2. `rm -f package-lock.json && rm -rf node_modules/`
3. `npm install`
4. `hexo clean && hexo server`
Maintainers only:
```sh
git clone -b ignore-theme-node https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(box): ignore node_modules/ & .git/ in themes

- lib/hexo/render.js
```sh
git clone -b render-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(render): Class syntax

- lib/hexo/index.js
- test/scripts/hexo/hexo.js
Fixes #3964
cc @cmpute
``` yml
a:
c: 2
```
``` yml
theme_config:
a:
b: 3
```
1.
``` diff
package.json
-  "hexo": "^4.1.1",
+  "hexo": "curbengh/hexo#deepmerge_theme_config"
```
2. `rm package-lock.json && rm -rf node_modules/`
3. `npm install`
4. `hexo clean && hexo server` (or `hexo generate` if relevant)
5. Verify `theme.a` should have `{ b: 3, c: 2}`
Maintainers:
```sh
git clone -b deepmerge_theme_config https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(theme): deep merge configs

- lib/hexo/default_config.js
- lib/hexo/index.js
In #3756, @dailyrandomphoto disabled `cache rendered content` for `generate` and enabled for `hexo s`.
Enabling cache rendered content for `hexo s` will respond more quickly from second requests which is helpful when use `hexo-server` in production, but it also makes more difficult when developing theme or previewing other changes. So the `config.server.cache` is introduced in this PR. The documents for `hexo-server` will be updated after this PR is merged and released with `hexo@4.3`.
```sh
git clone -b server-development https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(cache): option for cache rendered content

- lib/theme/view.js
The last part of #3753, drop `lodash.assignIn` in `lib/theme/view`.
Port from `_.extend` in `underscore.js`.
```sh
git clone -b drop-lodash-assignIn https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(theme/view): drop lodash.assignIn

- test/scripts/console/deploy.js
- test/scripts/console/render.js
- test/scripts/helpers/list_archives.js
- test/scripts/hexo/hexo.js
- test/scripts/hexo/load_database.js
- test/scripts/models/category.js
Not very keen on 'x pending' message at the end of unit test.
I added "missing-unit-test" to the comment. We can mention it in the [roadmap](https://github.com/hexojs/hexo/issues/2492), and contributor can simply search for the keyword to locate missing tests.
Add a missing test for list_archives helper.
load_database test is being worked on #3975 
Revert #3742 
```sh
git clone -b test-missing https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> test: comment out missing tests

- lib/plugins/helper/fragment_cache.js
Fix a potential performance issue introduced by #3744: After #3744, the function passed to fragment_cache might be called twice instead of once.
A PoC can be viewed here: https://runkit.com/sukkaw/5df9e053e7c3d50019810e89
```js
const cache = {};
let called1 = 0;
let called2 = 0;
// This PR
const cacheFunc1 = (k, fn) => {
if (cache[k] != null) return cache[k];
const result = fn();
cache[k] = result;
return result;
}
// PR #3744
const cacheFunc2 = (k, fn) => {
if (cache[k] != null) return cache[k];
cache[k] = fn();
const result = fn();
return result;
}
cacheFunc1('1', () => { return called1++; });
cacheFunc1('1', () => { return called1++; });
cacheFunc1('1', () => { return called1++; });
cacheFunc2('2', () => { return called2++; });
cacheFunc2('2', () => { return called2++; }); …
```
> refactor(fragment_cache): reuse result

- lib/extend/console.js
- lib/extend/filter.js
- lib/hexo/index.js
- lib/hexo/locals.js
- lib/hexo/router.js
- lib/theme/index.js
Avoid issue #3985, to avoid calling a function twice (e.g. `dirname()`). The returned result of a function is referred instead.
```sh
git clone -b chain-assignment https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> style: chained assignment

- lib/theme/view.js
The continuation of #3969 (#3753).
`underscore.js` has a `createAssigner()` which is a internal function for `_.extend`, `_.defaults` & `_.assign`:
```js
_.extend = createAssigner(_.allKeys);
_.assign = createAssigner(_.keys);
_.defaults = createAssigner(_.allKeys, true);
```
When bring up #3969, I just simply merge and rewrite `createAssigner(_.allKeys)`:
```js
// Below is a part of _.allKeys which is unnecessary for assignIn itself
const keys = [];
for (const key in source) keys.push(key);
// Iterate Object from keys
const l = keys.length;	
for (let i = 0; i < l; i++) {
const key = keys[i];
obj[key] = source[key];
}
```
This PR simplify the `assignIn()` by directly iterating Object.
```sh
git clone -b simplify-assignIn https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(theme/view): simplify assignIn

- lib/extend/deployer.js
```sh
git clone -b deployer-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(deployer): Class syntax

- lib/extend/tag.js
- lib/hexo/load_config.js
- lib/hexo/router.js
- lib/hexo/source.js
- lib/plugins/console/deploy.js
- lib/plugins/console/generate.js
- lib/plugins/console/list/category.js
- lib/plugins/console/list/page.js
- lib/plugins/console/list/post.js
- lib/plugins/console/list/tag.js
- lib/plugins/console/migrate.js
- lib/plugins/console/new.js
- lib/plugins/console/publish.js
- lib/plugins/console/render.js
- lib/plugins/generator/asset.js
- lib/plugins/helper/debug.js
- lib/plugins/helper/index.js
- lib/plugins/helper/open_graph.js
- lib/plugins/helper/tagcloud.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
- lib/plugins/renderer/yaml.js
- test/fixtures/post_render.js
- test/scripts/helpers/debug.js
- test/scripts/tags/include_code.js
Continuation of #3324 #3940 & #3953
```sh
git clone -b style-destructure-modules https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: destructure modules

- test/benchmark.sh
After https://github.com/hexojs/hexo/pull/3991, the CI on master branch is failing because the hot processing takes less than 10 seconds.
This PR skips completion time and line number checking in hot processing.
```sh
git clone -b benchmark-hot-processing https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> test(benchmark): skip checking completion time in hot processing

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
- by utilizing [`prettyUrls()`](https://github.com/hexojs/hexo-util#prettyurlsurl-options) of hexo-util
- to support pretty_urls.trailing_html
```sh
git clone -b og-pretty-urls https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(open_graph-helper): pass all pretty_urls options

- lib/plugins/helper/toc.js
- test/scripts/helpers/toc.js
Add `min_depth` option.
The unit test for `toc()` has been refactored as well.
Supersedes and closes https://github.com/hexojs/hexo/pull/3929
```sh
git clone -b toc_min_depth https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(toc_helper): add min_depth option

- lib/models/types/moment.js
- lib/plugins/helper/date.js
- lib/plugins/helper/list_archives.js
- test/scripts/helpers/date.js
Hexo language code is different with `Moment.js`.
If we set language like this,
```yml
language:
timezone:
```
or
```yml
language: zh-CN
timezone:
```
then `default` or `zh-CN` will pass to `moment.locale(lang)`.
```js
const lang = this.page.lang || this.page.language || config.language;
...
if (lang) date = date.locale(lang); // lang = 'default' or 'zh-CN'
```
Whenever `.locale (lang)` is called, it causes `moment` to find the locale file repeatedly.
This PR adds `toMomentLocale()` to convert lang code, avoid lookup repeatedly with the wrong names.
```sh
git clone -b fix-moment-locale https://github.com/dailyrandomphoto/hexo.git
cd hexo
npm install
npm test
```
> fix(moment.locale): avoid lookup repeatedly with the wrong names.

- lib/plugins/helper/toc.js
- package.json
- test/scripts/helpers/toc.js
- To support headings without `id` attribute, after https://github.com/hexojs/hexo-util/pull/166
* Instead of `<a href="#null">text</a>`, it becomes `<a>text</a>`
- Use [`htmlTag()`](https://github.com/hexojs/hexo-util#htmltagtag-attrs-text-escape)
* so that unsafe class name is escaped
* this also means `href` is percent-encoded (e.g. `#标题` -> `#%E6%A0%87%E9%A2%98`
* **However**, even if the `href` is not encoded, browser automatically encodes it when you copy the link (at least in Firefox).
* text in `<a>text</a>` is html-escaped. [`tocObj()`](https://github.com/hexojs/hexo-util#tocobjstr-options) parses only the text inside heading, leaving out the markup.
``` js
tocObj('<h1 id="hello"><b>hello</b></h1>')
// [ { text: 'hello', id: 'hello', level: 1 } ]
```
- this means even when the …
> fix(toc_helper): escape class name and handle null id

- lib/plugins/helper/list_archives.js
- test/scripts/helpers/list_archives.js
Continuation of #4007.
`list_archives` will call `date.locale(lang)`, `date.format(format)` a lot of times, especial if set to `relative_link: true`. (fragment_cache was disabled)
This PR change makes `list_archives` call `date.locale(lang)`, `date.format(format)` once per group.
```sh
git clone -b improve-list_archives https://github.com/dailyrandomphoto/hexo.git
cd hexo
npm install
npm test
```
> refactor(list_archives): Reduce calls to date.format()

- package.json
- test/scripts/box/file.js
I think it's viable to eventually replace [chai-as-promised](https://github.com/hexojs/hexo/issues/3328) with async/await.
```sh
git clone -b test-box-file-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-box-file): async/await

- lib/hexo/index.js
```sh
git clone -b hexo-index-set https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(hexo/index): use Set

- lib/plugins/filter/after_render/meta_generator.js
- test/scripts/filters/meta_generator.js
Current regex pattern will only matches `<meta name="generator" content="Hexo 4.2.0">` but not`<meta content="Hexo 4.2.0" name="generator">`,
```sh
git clone -b meta_generator_fix https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix(meta_generator): avoid an edge case

- CODE_OF_CONDUCT.md
- README.md
Netlify recently updated their [policy](https://www.netlify.com/legal/open-source-policy/?utm_campaign=Netlify+%3C3+Open+Source+email&utm_content=Netlify+open+source+plan&utm_medium=email_action&utm_source=customer.io). It is required to have a Code of Conduct in the repository.
```sh
cd hexo
npm install
npm test
```
> Add Code of Conduct 

- lib/extend/tag.js
- test/scripts/extend/tag.js
Closes #3457.
```sh
cd hexo
npm install
npm test
```
Related API Documents:
- [nunjucks.Environment.hasExtension()](https://mozilla.github.io/nunjucks/api.html#hasextension)
- [nunjucks.Environment.removeExtension()](https://mozilla.github.io/nunjucks/api.html#removeextension)
> feat(tag): add unregister() method

- test/scripts/filters/save_database.js
```sh
git clone -b test-filters-save_database https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
>  refactor(test-filters-save_database): async/await 

- lib/hexo/index.js
- lib/plugins/filter/after_render/index.js
- test/scripts/hexo/hexo.js
#4048 See discussion here, add `after_route_render` implement it.
```sh
git clone -b filter https://github.com/jiangtj/hexo.git
cd hexo
npm install
npm test
```
> feat(filter): add after_route_render filter

- test/scripts/console/config.js
```sh
git clone -b test-console-config-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-console-config): async/await

- test/scripts/hexo/load_database.js
Added a workaround for the `EPERM error` in Windows.
Might as well refactor to async/await #3328.
```sh
git clone -b db-load-windows https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> test(load_database): enable 'database load failed'

- test/scripts/extend/tag_errors.js
This PR also removes the unneeded console.log.
```sh
git clone -b test-extend-tag_errors https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-extend-tag_errors): async/await

- test/scripts/console/generate.js
```sh
git clone -b test-console-generate https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-console-generate): async/await

- test/scripts/console/generate.js
- test/scripts/hexo/load_database.js
- test/scripts/theme_processors/source.js
Continuation of https://github.com/hexojs/hexo/pull/3975
Add workarounds for more reliable unit testing on Windows in CI env.
```sh
cd hexo
npm install
npm test
```
> test(load-database): fix EPERM error in windows

- .travis.yml
- appveyor.yml
The workarounds #3975 #4069 still don't work reliably in Travis' Windows.
I also reverse the order of Node version in Appveyor, to prioritize newer Node (Appveyor starts the tests sequentially). This is to avoid the issue experienced in https://github.com/hexojs/hexo-fs/pull/50.
```sh
git clone -b travis-disable-windows https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> ci(travis): remove Windows

- package.json
Include performance fixes in warehouse@[3.0.2](https://github.com/hexojs/warehouse/releases/tag/3.0.2)
This is necessary to force CI to update the dependency.
```sh
git clone -b warehouse-3.0.2 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> chore(deps): bump warehouse from 3.0.1 to 3.0.2

- .travis.yml
- test/benchmark.sh
Use `0x` to generate a human readable flamegraph after benchmark. The flamegraph directory will be under `${TRAVIS_BUILD_DIR}/0x`.
Before we could find a way to deploy the flamegraph, I will leave this PR as a draft.
```sh
git clone -b 0x-flamegraph https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
The directory structure should like this:
```
0x
├── flamegraph.html
├── isolate-0x5af5020-1756-1756-v8.log
├── isolate-0x5af5020-1756-1756-v8.log.json
├── isolate-0x5af5020-1756-1756-v8.log.preprocess-ready
└── meta.json
0 directories, 5 files
```
And the flamegraph looks like this:
> ci(benchmark): generate flamegraph

- test/scripts/models/post_asset.js
```sh
git clone -b test-models-post_asset https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-models-post_asset): async/await

- test/scripts/models/tag.js
```sh
git clone -b test-models-tag https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(test-models-tag): async/await

- test/scripts/console/publish.js
https://github.com/hexojs/eslint-config-hexo/pull/28
```sh
git clone -b style-async-fun-space https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> style: space for asyncArrow

- lib/hexo/index.js
- lib/plugins/console/deploy.js
- lib/plugins/filter/new_post_path.js
According to [the post](https://thecodebarbarian.com/object-assign-vs-object-spread.html), `Object.assign` is as fast as spread operator when shallow merging object (`Object.assign` is even slightly faster). However, when use `Object.assign` for copy object (passing `{}` as the first parameter), spread operator is consistently faster.
```sh
git clone -b spread-operator https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: copy object with spread operator

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
In 8bd3439421e2b50799d13e1ba3f804d599c94962 @curbengh utilize `open_graph()` helper with new `htmlTag()` util.
However, [`htmlTag()`](https://github.com/hexojs/hexo-util/blob/7e084de7244a8f11ff8571fae8a5782936ea65b0/lib/html_tag.js) from hexo-util is a little over complicated, thus I bring up this PR with avoiding usage of `htmlTag()`. 
```sh
git clone -b optimize-opengraph-helper https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
Benchmark Result after https://github.com/hexojs/hexo/pull/4125/commits/d13ab9a3c816b76ce092f83cd54ccbd96164fe68:
| | NodeJS 8 | NodeJS 10 | NodeJS 12 | NodeJS 13 |
|:---:|:---:|:---:|:---:|:---:|
| Current Master Branch | 17.87 | 14.83 | 15.91 | 14.77 |
| This PR | **16.18** | **14.32** | **15.23** | **14.6** |
There is about 3% - 5% …
> perf(open_graph): avoid using htmlTag() and enhance cache

- lib/plugins/tag/youtube.js
- test/scripts/tags/youtube.js
#3267 Add playlist support for `youtube` tag.
Related documents: https://support.google.com/youtube/answer/171780?hl=en
Usage:
```
// By default youtube tag will output video
{% youtube [id] %}
// Manually set type
{% youtube [id] 'video' %}
{% youtube [id] 'playlist' %}
```
```sh
git clone -btag-youtube-playlist https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(youtube_tag): support playlist

- lib/plugins/console/generate.js
- lib/plugins/helper/feed_tag.js
- lib/plugins/helper/tagcloud.js
- test/scripts/helpers/tagcloud.js
Issues found by lgtm.com (https://lgtm.com/projects/g/hexojs/hexo/)
- generate.js
- second parameter of `wrapDataStream()` is always called with an object, so there's no need for null-checking. (both `{ undefined }` and `{ null: null }` are truthy)
- feed_tag.js
* no need for second additional null-checking on `path` variable.
- tagcloud.js
* `if (!startColor || !endColor) color = false;` is unreachable since `new Color(null)` will throw error.
* throw more descriptive error (error message now says which required option is missing)
```sh
git clone -b check-condition https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix: remove useless conditions

- lib/hexo/index.js
```yaml
a:
foo: 'bar'
c: 'vaz'
```
```yaml
a:
foo: 'abc'
b:
baz: 'vrf'
```
**Before this PR**
In theme template:
- `theme.b.baz` --- `vrf`
- `config.a.foo` --- `bar`
- `theme.a.foo` --- `abc`
- `config.c` --- `vaz`
- `theme.c` --- `vaz`
**After this PR**
In theme template:
- `theme.b.baz` --- `vrf`
- `config.a.foo` --- `bar`
- `theme.a.foo` --- `abc`
- `config.c` --- `vaz`
- `theme.c` --- Throw `undefined` error
---
Since current behavior (merge site config into theme config) is not documented, I am assuming there is no theme developer is relying this behavior.
```sh
git clone -b remove-site-config-from-theme-config https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: remove site config from theme config

- lib/plugins/tag/youtube.js
- test/scripts/tags/youtube.js
youtube-nocookie.com is privacy-enhanced mode, meaning google/youtube's cookie is not used. If a visitor is logged into google/youtube, the embedded video would not be linked to the visitor's account.
https://support.google.com/youtube/answer/171780?hl=en
To use:
`{% youtube foobar, false %}`
`{% youtube foobar, 'video', false %}`
```sh
git clone -b youtube-nocookie https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> feat(youtube_tag): add cookie option

- lib/hexo/index.js
- lib/hexo/load_theme_config.js
- test/scripts/hexo/index.js
- test/scripts/hexo/load_theme_config.js
The part of #3890
> `theme_config` in `_config.yml` looks good, but it is better to have a separate theme config. We could introduce `_config.[name].yml`. Currently, `theme_config` has higher priority than `_config.yml` under theme directories. After bring up `_config.[name].yml`, I suggest the `theme_config in _config.yml > _config.[name].yml > _config.yml under theme directories` which will retain highest priority for `theme_config`.
```sh
git clone -b theme-config-dedicated https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(load_theme_config): support alternate theme config

- lib/plugins/console/generate.js
Continuation of https://github.com/hexojs/hexo/pull/4147
`bail` variable is of boolean type, passing `{ bail }` (boolean to object) as a parameter is unnecessary.
```sh
git clone -b object-boolean https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(console_generate): remove useless boolean-to-object conversion

- lib/hexo/post.js
- test/scripts/hexo/post.js
Currently, the regular expression `rSwigFullBlock` used in the `escapeAllSwigTags` method in `lib/hexo/post.js` may incorrectly match the Swig / Nunjucks block. For example, the user writes the following in a markdown document
```md
{% note danger %}note text, note text, note text{% endnote %}
{% note danger %}note text, note text, note text{% endnote %}
```
Then, this regular expression will match all three lines, starting from `{% note danger %}` in the first line to the ending `{% endnote %}` in the third line, which means that `## Title` in the second line is only processed by Nunjucks but not by the Markdown renderer, so it appears as `## Title` instead of `<h2>Title</h2>` in the output HTML.
By using non-greedy regular expression, the first and third line will be matched separately …
> fix(post): use non-greedy regular expressions

- test/scripts/box/box.js
- test/scripts/console/config.js
- test/scripts/console/deploy.js
- test/scripts/console/generate.js
- test/scripts/console/list_categories.js
- test/scripts/console/list_page.js
- test/scripts/console/list_post.js
- test/scripts/console/list_tags.js
- test/scripts/console/migrate.js
- test/scripts/extend/filter.js
- test/scripts/hexo/hexo.js
- test/scripts/hexo/post.js
- test/scripts/hexo/render.js
- test/scripts/hexo/router.js
- test/scripts/models/post.js
- test/scripts/theme/view.js
- test/scripts/theme_processors/config.js
```sh
cd hexo
npm install
npm test
```
> Refactor(test): Useful sinon.assert

- lib/hexo/index.js
`immediate` parameter is never called. Found by [lgtm](https://lgtm.com/projects/g/hexojs/hexo/snapshot/456b4eb3a67752d00d607db6a4f24f777c66d4fd/files/lib/hexo/index.js?sort=name&dir=ASC&mode=heatmap).
```sh
git clone -b unused-parameter https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> refactor(hexo_index): remove unused parameter

- lib/plugins/helper/list_tags.js
- test/scripts/helpers/list_tags.js
When the style `list` is not used, don't append `-link` to the class name, it prevents to fully control class name and so css framework to work correctly.
fix https://github.com/hexojs/hexo/issues/4058
```sh
git clone -b patch-1 https://github.com/noraj/hexo.git
cd hexo
npm install
npm test
```
Init a new test site:
```
hexo init test
cd test
```
Replace `themes/landscape/layout/_widget/tag.ejs` with:
```ejs
<% if (site.tags.length){ %>
<div class="widget-wrap">
<h3 class="widget-title"><%= __('tags') %></h3>
<div class="widget">
<%- list_tags(site.tags, {class: 'classtest', style: false, separator: ' + '}) %>
<hr>
<%- list_tags(site.tags, {class: 'classtest', style: 'list'}) %>
<hr>
<%- list_tags(site.tags, {class: {ul: 'ululul', li: 'lilili', a: 'aaa', count: 'ccc'}, style: false, …
```
> list_tags: custom class for each element

- lib/plugins/helper/toc.js
Fix #4181, an alternative to #4182. 
By avoid using over complicated `htmlTag()` to gain better performance and fit the current test cases.
```sh
git clone -b refactor/og-remove-htmltag https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(toc): avoid using htmlTag

- lib/plugins/filter/post_permalink.js
- test/scripts/filters/post_permalink.js
Like this:
```
permalink: :year/:month/:day/:hour/:minute/:second/:post_title/
```
Will generate:
```
example.com/2015/05/06/12/13/14/my-new-post/
```
```sh
cd hexo
npm install
npm test
```
> feat(post_ermalink): add `:second` attr option for post permalink

- lib/hexo/load_config.js
- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
The part of #3890
https://github.com/hexojs/hexo/issues/3890#issuecomment-573489000
```sh
git clone -b feat-ignore-theme-in-plugin https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(load_plugins): ignore hexo-theme-[config.theme]

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
- package.json
- test/scripts/filters/external_link.js
This PR add cache for 2 values:
- `EXTERNAL_LINK_(POST|SITE)_ENABLED`
Since hexo will only run filter for `post` or `site`, it is important to return earlier for another one.
- `EXTERNAL_LINK_(POST|SITE)_CONFIG`
Currently, hexo handles `hexo.config.external_link` inside the filter. With config being cached there will be no need to run `Object.assign()` again and again.
```sh
git clone -b optimize-external-filter https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(external_link): cache config

- lib/box/file.js
- lib/extend/tag.js
fix remaining alerts of [lgtm](https://lgtm.com/projects/g/hexojs/hexo/?mode=list).
- `file.js` - since `options` is not used in the function, there's no need to handle it.
- `tag.js` - return a callback if `render()` is called with a callback.
```sh
git clone -b callback-handling https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix: return callback if called

- lib/plugins/filter/after_render/meta_generator.js
- test/scripts/filters/meta_generator.js
This PR is mean to supersede #4070 and #4078.
With cached value `NEED_INJECT`, all the checks will be only executed once.
```sh
git clone -b meta_generator_optimize https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(meta_generator): avoid unnecessary check

- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Adding the test cases that are included in #4171.
Since #4171 is about to be discarded, I pick those added test cases up into this PR then.
```sh
git clone -b test-post-extra https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> test(post): adding extra test cases

- test/scripts/hexo/load_plugins.js
Fix potential race condition causing test to fail. Discovered in #4264.
```sh
git clone -b test-load-plugins https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> test(load_plugins): make sure file is created

- .github/workflows/tester.yml
```sh
cd hexo
npm install
npm test
```
> feat(github actions): Create tester job

- lib/box/index.js
- lib/plugins/console/generate.js
`hexo-util#HashStream` has already deprecated and is removed in https://github.com/hexojs/hexo-util/pull/198. This PR drop the usage of it. 
```sh
git clone -b drop-hashstream https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor: drop hexo-util#HashStream

- lib/box/index.js
- lib/plugins/console/generate.js
- lib/plugins/processor/post.js
https://github.com/hexojs/hexo-cli/pull/190
```sh
git clone -b fix-hexo-fs-enoent https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix: access error code from error object directly

- lib/hexo/load_config.js
- test/scripts/hexo/load_config.js
The part of #3890
> Hexo will read themes/[name] directory first, then search hexo-theme-[name] directory under node_modules. It means the theme under themes directory should have higher priority. In this way no extra theme_from_npm: true configuration is needed.
```sh
git clone -b theme_dir_load https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(load_config): support theme_dir in node_modules

- lib/box/index.js
- lib/hexo/load_config.js
- lib/theme/index.js
- test/scripts/box/box.js
- test/scripts/hexo/load_config.js
Ignore correct `.git` and `node modules` in the theme folder
```sh
git clone -b fix-watch-ignore https://github.com/jiangtj/hexo.git
cd hexo
npm install
npm test
```
> fix(box): ignore correct `.git` and `node modules` in the theme folder

- lib/box/index.js
- lib/plugins/console/generate.js
Fix errors of the issue #3818. (https://github.com/hexojs/hexo/issues/3818#issuecomment-622249260)
Supersede the draft PR #4292.
With Node.js v10.x (not v12.x), `npm test` fails some times.
One of them is `process() - skip (mtime changed but hash matched):` as follows:
```
1) Hexo
Box
Box
process() - skip (mtime changed but hash matched):
AssertError: expected spy to be called with match
[_File] {
params: {  },
path: "a.txt",
source: "J:\00_Seaoak\hexo\test\scripts\box\box_tmp\test\a.txt",
type: "update"
} { path: "a.txt", type: "skip" }
at Object.fail (J:\00_Seaoak\hexo\node_modules\sinon\lib\sinon\assert.js:107:21)
at failAssertion (J:\00_Seaoak\hexo\node_modules\sinon\lib\sinon\assert.js:66:16)
at Object.assert.(anonymous function) [as calledWithMatch] …
```
> Correct using createSha1Hash() with pipe()

- .github/workflows/tester.yml
- .travis.yml
- package.json
```sh
cd hexo
npm install
npm test
```
> Move coveralls from travis to github actions

- lib/box/file.js
- lib/plugins/console/deploy.js
- package.json
- test/scripts/hexo/post.js
The PR of #4336 is a provisional measure.
hexo-fs@3.1.0 needs to be modified to not pass the callback directly to hexo-fs.
```sh
cd hexo
npm install
npm test
```
> Fix not to pass callback to hexo-fs

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
Issue resolved: https://github.com/hexojs/hexo/issues/4228
See also https://github.com/hexojs/hexo/pull/3672
```sh
git clone -b revert-3672 https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> Posts without title should be accessible

- .github/ISSUE_TEMPLATE/other.md
- .github/ISSUE_TEMPLATE/question-help.md
The continuation for #3905
- Add special notice for zh-CN users
> As you can see, all of issues marked as [`non-english`](https://github.com/hexojs/hexo/issues?q=is%3Aissue+is%3Aopen+label%3Anon-english) are in zh-CN, and moer than half of the issues marked as [`not following issue templates`](https://github.com/hexojs/hexo/issues?q=is%3Aissue+is%3Aopen+label%3A%22not+following+issue+template%22) are in zh-CN as well. We MUST add such a notice for Chinese users.
- tips for security (not to contain Personal Access Token in issues).
```sh
cd hexo
npm install
npm test
```
> github(issue_template): add special notice

- lib/hexo/post.js
- test/scripts/hexo/post.js
The PR fixes #3259, #3346 & https://github.com/hexojs/hexo/issues/3346#issuecomment-595497849
```sh
git clone -b test-post-render-swig https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix(post): swig tag inside post

- lib/extend/tag.js
- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Similar to #4161, use non-greedy regexp. See #4161 for more details.
This PR closes #4317.
```sh
cd hexo
npm install
npm test
```
> fix(#4317): non-greedy regexp for tag escape

- lib/hexo/post.js
- test/scripts/hexo/post.js
Continuing #4352
https://github.com/hexojs/hexo/pull/4352/files#r441953318
Marked.js will escape code by default. If the swig inside ` ``  ` has been escaped, it will be escaped again by marked.js.
This PR avoid it.
cc @stevenjoezhang
```sh
git clone -b avoid-swig-double-escape https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix(post): avoid swig in code being double escaped

- lib/plugins/filter/post_permalink.js
- lib/plugins/processor/post.js
- test/scripts/filters/post_permalink.js
- test/scripts/processors/post.js
The PR closes #1158, closes #1813, closes #3464
https://github.com/hexojs/hexo/issues/3464#issuecomment-644238739
https://github.com/hexojs/hexo/blob/edef5c2a9c1217aaab02f64397e7e94d2f98e4fa/lib/plugins/processor/post.js#L123-L126
Originally, during the processing of the post, the `permalink` defined in the front-matter which is `data.permalink`, will override `data.slug` and `data.permalink` will be deleted.
And, in `post_permalink` filter, `data.slug` will be used to get `name` and `title` property:
https://github.com/hexojs/hexo/blob/edef5c2a9c1217aaab02f64397e7e94d2f98e4fa/lib/plugins/filter/post_permalink.js#L15-L16
So if I got a post: `source/_posts/i-love-hexo/hello.md`, I will get:
- title: `i-love-hexo/hello`
- name: `hello`
If I then defines `permalink` as …
> fix(#3464): override permalink use the front-matter

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
Fixed issue #3478. 
```sh
cd hexo
npm install
npm test
```
- the result before adding the unittest
The result is the same as the original master branch on my machine.
- the result after adding the unittest
- code coverage summary
> skip assets of unpublished posts and delete them if exist

- lib/extend/filter.js
- lib/hexo/index.js
- lib/plugins/filter/after_render/index.js
- test/scripts/hexo/hexo.js
- test/scripts/hexo/post.js
- test/scripts/hexo/render.js
- test/scripts/theme/view.js
- Extension of https://github.com/hexojs/hexo/pull/4051
- Rename `after_route_render` filter to `_after_html_render` (as an internal filter)
- Set `after_render:html` as an alias of `_after_html_render`
* so that existing plugins can take advantage of the new filter automatically (e.g. https://github.com/hexojs/hexo-html-minifier/pull/51 is no longer necessary)
CC @SukkaW @jiangtj 
```
let index = 0;
hexo.extend.filter.register('after_render:html', (data) => {
console.log(index++)
});
```
`index` is up to 78 in my dummy site
`index` is down to 6.
```sh
git clone -b after-route-render-alias https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> perf(filter): set after_render:html as alias of _after_html_render

- lib/hexo/default_config.js
- lib/models/page.js
- lib/models/post.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
- test/scripts/helpers/open_graph.js
- test/scripts/models/page.js
- test/scripts/models/post.js
- test/scripts/processors/asset.js
- test/scripts/processors/post.js
Continuation of #3235, specifically #3235 (comment). https://github.com/hexojs/hexo/pull/3887#issuecomment-567723586
Quote from #3887
> User may prefer to have full control on value of post.updated and not use file modification time. Currently for my blog, I have to use a new variable lastUpdated as a workaround; since that variable is not recognized by many plugins, I have to fork many plugins.
>
> With this PR, config.optional_updated can be enabled (disabled by default), to leave post.updated to be empty if updated: is not set in the front-matter.
This PR introduced a new option `updated_option` which accept:
- `mtime`: This is the default behavior of hexo, use file's `mtime` as `data.updated` when not set in front-matter.
- `date`: Use `data.date` as `data.updated` when not set in …
> feat: bring up config.updated_option

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
Deprecate old options, to be dropped in the next major release (Hexo 6), **not a breaking change** for Hexo 5. Retain backward compatibility only for one major version.
Initially I planned to drop `config.external_link: true` so that new option is used,
``` yml
external_link:
enable: true
```
but I noticed the [release note](https://github.com/hexojs/hexo/releases/tag/4.0.0) didn't mention about deprecation, so the old option is retained for now.
```sh
git clone -b drop-old-external_link https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> docs: deprecate config.external_link (boolean) & config.use_date_for_updated

- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/filters/backtick_code_block.js
Shorthand syntax. Return directly when there is no backtick code block inside a post.
```sh
git clone -b perf-backtick-code-filter https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(backtick_code): shorthand

- lib/plugins/helper/tagcloud.js
- test/scripts/helpers/tagcloud.js
The color of the tag in the tag-cloud is defined by the inline style, e.g.
```html
<a href="/tags/bcd/" style="font-size: 20px; color: #4682b4">bcd</a>
```
However, for themes that support the dark mode, it's necessary to display different tag colors for different background colors. Class name will be a better choice.
See also https://github.com/next-theme/hexo-theme-next/commit/cbcd3f04abfbc15c82f1cf430eca15591015fadc
Usage:
```njk
{{ tagcloud({ class: 'tag-cloud' }) }}
```
```styl
for $tag-cloud in (0 .. 10) {
$tag-cloud-color = mix($tag-cloud-end, $tag-cloud-start, $tag-cloud * 10);
.tag-cloud-{$tag-cloud} {
color: $tag-cloud-color;
}
}
@media (prefers-color-scheme: dark) {
for $tag-cloud in (0 .. 10) {
$tag-cloud-color = mix($tag-cloud-end-dark, $tag-cloud-start-dark, $tag-cloud * …
```
> feat(tagcloud): new option class & level

- lib/hexo/index.js
`Writing database to ${dbPath}/db.json` debug log is only relevant in the following [commands](https://hexo.io/docs/commands):
- init
- new
- generate
- publish
- server
- deploy
- render
- migrate
```sh
cd hexo
npm install
npm test
```
> fix(logging): log database only in relevant commands

- test/scripts/hexo/hexo.js
```sh
cd hexo
npm install
npm test
```
> refactor(test-hexo): async/await

- lib/hexo/index.js
Improve compatibility with 3rd-party console plugins that start with an 's'.
By default, `server` command has the following alias (using [`abbrev`](https://www.npmjs.com/package/abbrev)):
- 's'
- 'se'
- 'ser'
- ...
- 'server'
However, if there is a 3rd-party console that also starts with an 's', like 'save', 'server' will no longer have 's' alias; instead, its alias will start with 'se'. Another example is 'selenium', 'server' alias will start with 'ser'.
These examples illustrate `cmd.startsWith('s')` might match other commands than the intended 'server'.
```sh
git clone -b abbrev-compat https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> fix(server-cache): must match exact alias

- lib/plugins/tag/code.js
notice this issue when testing https://github.com/hexojs/hexo/pull/4390
```sh
git clone -b tag-code-wrap https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(tag-code): parse 'wrap' option

- lib/hexo/index.js
Loading config and plugins are not needed in `hexo clean`. Noticed from #4381.
Only filter plugins are executed, i.e. to execute `after_clean` filter,
```sh
cd hexo
npm install
npm test
```
> perf: avoid running irrelevant plugins in 'clean' command

- lib/plugins/helper/css.js
- lib/plugins/helper/js.js
> fix: remove unused type check

- test/scripts/box/box.js
- test/scripts/console/config.js
- test/scripts/console/deploy.js
- test/scripts/console/list_categories.js
- test/scripts/console/list_page.js
- test/scripts/console/list_post.js
- test/scripts/console/list_tags.js
- test/scripts/console/migrate.js
- test/scripts/hexo/render.js
- test/scripts/hexo/router.js
- test/scripts/theme/view.js
- test/scripts/theme_processors/config.js
Replace `sinon#assert` with `Chai.Assertion.LanguageChain`.
```sh
git clone -b test-replace-sinonAssert https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> test: replace sinon#assert

- lib/hexo/index.js
- test/scripts/hexo/hexo.js
#4120, https://github.com/hexojs/hexo/pull/4120#issuecomment-619574347, https://github.com/hexojs/hexo/issues/3890#issuecomment-644603994
This PR closes #3890.
```sh
git clone -b theme_config_ctx https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(hexo): merge theme_config before generation

- lib/hexo/index.js
- lib/hexo/load_config.js
- lib/hexo/validate_config.js
- test/scripts/hexo/index.js
- test/scripts/hexo/validate_config.js
Continuation fo #4371 and supersedes #4376. 
```sh
git clone -b config-validation https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(config): validate config after load_config

- lib/box/file.js
- lib/box/index.js
- test/scripts/box/file.js
Remove the `callback` from `box`.
All hexo internal functions are not relied on `box`'s callback, and `box`'s callback usage is never mentioned in Hexo API documents: https://hexo.io/api/box
```sh
git clone -b reduce-ascallback-box https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(box): remove Bluebird.asCallback

- test/scripts/console/deploy.js
- test/scripts/console/index.js
- test/scripts/console/list.js
- test/scripts/hexo/render.js
- test/scripts/processors/post.js
#3984
Continuation of #4050 
```sh
git clone -b test-coverage-1 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> test: improve coverage

- .github/workflows/tester.yml
- .gitignore
- .mocharc.yml
- package.json
A [new feature](https://mochajs.org/#parallel-tests) of mocha@8. Consistently 3s faster in my single-core VM.
nyc (for now, v15.1.0) [doesn't](https://github.com/istanbuljs/nyc/issues/1328) support mocha's parallel mode yet, so parallel mode is disabled in test coverage job.
```sh
git clone -b parallel-mocha https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> perf(mocha): run tests in parallel

- lib/plugins/tag/post_link.js
- test/scripts/tags/post_link.js
Issue resolved: #1594
```sh
git clone -b post_link https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> post_link should throw error if no slug/post found

- lib/hexo/load_config.js
- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
- test/scripts/filters/external_link.js
- test/scripts/hexo/load_config.js
Instead of migrating old boolean format config into object format every time the filter is executed, run the config migration during `load_config`.
```sh
git clone -b config-external-link-process https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(external_link): migrate config during load_config

- test/benchmark.js
- Speed up local benchmark.
- When `testDir` exists, `benchmark.js` won't setup dummy blog again.
- Add hook for `Rendering Post`
```sh
git clone -b faster-local-benchmark https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> test(benchmark): optimize for local & render post support

- lib/extend/tag.js
- test/scripts/extend/tag_errors.js
#3859 #4109 #1771
- Show the source file that contains error
`source` is available as a property of `options` that passed to `tag.render`.
- Beautify the Error
- The source of error will be colored in magenta while the error type will be in red.
```sh
cd hexo
npm install
npm test
```
> feat(tag): show source of the error & beautify

- lib/extend/tag.js
- lib/hexo/post.js
- test/scripts/hexo/post.js
Escape swig tag inside code block only once.
```sh
git clone -b post-tag-render-optimize https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(tag): rendering optimization

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
- lib/plugins/filter/after_render/meta_generator.js
```sh
git clone -b external-link-regexp-perf https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(external_link): optimized regexp

- lib/plugins/filter/after_render/meta_generator.js
- test/scripts/filters/meta_generator.js
Ignoring empty `<head>` tag is firstly introduced in https://github.com/hexojs/hexo/pull/3315, in which `cheerio@1` will automatically append `<html><head><body>`. After #3677, cheerio has been dropped from `dependencies`. And cheerio in `devDependencies` has been pinned at `0.22.0` as well. So I just assume there will be no empty `<head>` tag any more.
The PR removes empty `<head>` detection which results in less generation time.
```sh
git clone -b meta-generator-empty https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor(meta_generator): no longer ignore empty <head>

- lib/plugins/filter/after_post_render/excerpt.js
- test/scripts/filters/excerpt.js
The current regex to detect the excerpt tag `` is too lenient, it matches `` and even
```
```
This PR restricts it to two dashes only and zero or one space.
```sh
cd hexo
npm install
npm test
```
> fix(excerpt): stricter regex

- lib/hexo/post.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
- lib/theme/view.js
- package.json
- test/scripts/hexo/post.js
RT.
```sh
git clone -b deps-yfm-2 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> chore(deps): update hexo-front-matter from 1.0.0 to 2.0.0

- package.json
Release 5.0.0.
```sh
git clone -b 5.0.0 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
-----
Pending deps:
Pending PR:
Pending documents:
> release: 5.0.0

- lib/plugins/helper/css.js
- lib/plugins/helper/favicon_tag.js
- lib/plugins/helper/feed_tag.js
- lib/plugins/helper/image_tag.js
- lib/plugins/helper/js.js
- lib/plugins/helper/link_to.js
- lib/plugins/helper/list_archives.js
- lib/plugins/helper/list_categories.js
- lib/plugins/helper/list_posts.js
- lib/plugins/helper/list_tags.js
- lib/plugins/helper/paginator.js
- lib/plugins/helper/tagcloud.js
- test/scripts/helpers/css.js
- test/scripts/helpers/favicon_tag.js
- test/scripts/helpers/feed_tag.js
- test/scripts/helpers/image_tag.js
- test/scripts/helpers/js.js
- test/scripts/helpers/link_to.js
- test/scripts/helpers/list_archives.js
- test/scripts/helpers/list_categories.js
- test/scripts/helpers/list_posts.js
- test/scripts/helpers/list_tags.js
- test/scripts/helpers/mail_to.js
- test/scripts/helpers/paginator.js
- test/scripts/helpers/tagcloud.js
``` js
const css = hexo.extend.helper.get('css').bind(hexo)
const css = hexo.extend.helper.get('css')
```
doesn't work for me, somehow [`url_for()`](https://github.com/hexojs/hexo/blob/14890743dd00e1a1e7c4bd9c7ef632f609d35a4c/lib/plugins/helper/css.js#L27) is not available in the `hexo` context. I tried v4.0.0, v4.1.1, v4.2.1 & v5 in Node 12.18
```sh
git clone -b url_for https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix(helpers): call url_for from hexo-util

- lib/extend/injector.js
- test/scripts/extend/injector.js
It is common that many user won't have many plugins installed which is utilizing `Injector`. Also, rare SDK requires adding snippets right after `<head>` or `<body>`. AFAIK only facebook SDK requires adding `<script>` right after `<body>`.
The PR adds shorthand optimization to avoid unnecessary `String#replace`.
```sh
git clone -b perf-injector-shorthand https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(injector): shorthand optimization

- lib/plugins/filter/after_post_render/external_link.js
- lib/plugins/filter/after_render/external_link.js
`isExternalLink()` has a shorthand optimization for absolute link:
https://github.com/hexojs/hexo-util/blob/fe64888f28acaa77f26eab04e7d358c6e6029967/lib/is_external_link.js#L19
Then I think why can't we exclude relative link directly in the `rATag` to avoid extra `isExternalLink()` and `RegExp#test`? So here is the PR.
```sh
cd hexo
npm install
npm test
```
> perf(external_link): update regexp

- lib/hexo/index.js
This reverts commit 33dcc90b7914d9b96fb666e9cb7322868f00acae (#4386).
load_plugins.js was initially retained so that `after_clean` filter
still can run, however it loads every plugins including irrelevant
ones; this can cause `undefined` error when running `hexo clean` especially in hexo.extend.helper.get()
because default helpers are not loaded.
```sh
cd hexo
npm install
npm test
```
> Revert "perf: avoid running plugins in 'clean' command"

- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
Reverts https://github.com/hexojs/hexo/commit/f6407dc946c2a686731b2480ee6ed0b37f54c5f1
Issue resolved: https://github.com/hexojs/hexo/issues/1670#issuecomment-671682748
The easiest way to install local plugins is to place them in the `scripts` directory instead of `node_modules`.
```sh
git clone -b plugins https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> Remove plugins option in config

- lib/hexo/post.js
- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Basically the PR is reverting https://github.com/hexojs/hexo/pull/4254.
Given a code block like this:
````markdown
```html
<body>
</body>
```
````
`backtick_code_block` will use `prismjs` to convert the code block into html:
```
</span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span><span aria-hidden="true" class="line-numbers-rows"><span></span><span></span><span></span></span></code></pre>:hexoPostRenderEscape-->
```
`` is added by Hexo to avoid missing paragraph issue.
> Why they are needed, what is "missing paragraph" issue: https://github.com/hexojs/hexo/pull/4171#discussion_r387542843
However, instead of ignoring the comment, `marked.js.org` will add extra `<p>` tag:
```
</span> …
```
> fix(#4460): refactor post escape

- lib/hexo/post.js
- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/filters/backtick_code_block.js
In #4418 I have introduced the code escaping during tag plugins rendering. In #4472 I have brought back the backtick code block escaping during markdown rendering.
To avoid duplicated escaping, the PR will only restore escaped backtick code block after tag plugin rendering is finished,
The performance improves by 2%.
```sh
git clone -b refactor-codeblock-escape https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf(backtick_code): avoid duplicated escaping

- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
The first part of #4496. Prevent `@user/hexo-theme-[name]` being loaded as a plugin.
```sh
git clone -b npm-theme-owner https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> feat(load_plugin): ignore pkg name endswith theme name

- lib/hexo/post.js
- test/scripts/hexo/post.js
A workaround to fix https://github.com/hexojs/hexo/issues/3860, `disableNunjucks` may not be reliable in synchronous mode. The issue could be due to [`Promise.method()`](https://github.com/hexojs/hexo/blob/9662366f9122192359f15861fe05574365e8465e/lib/extend/renderer.js#L53) not including `disableNunjucks` property.
Before: https://github.com/hexojs/hexo-renderer-coffeescript/pull/72/checks?check_run_id=1030164260
After: https://github.com/hexojs/hexo-renderer-coffeescript/pull/72/checks?check_run_id=1030174895
```sh
cd hexo
npm install
npm test
```
> fix(disableNunjucks): query both async and sync versions of renderer

- lib/hexo/default_config.js
- test/scripts/helpers/feed_tag.js
- test/scripts/helpers/open_graph.js
- test/scripts/models/post.js
- test/scripts/tags/img.js
We should stop to use `yoursite.com`.
`yoursite.com` is a real company's domain.
We can use `example.com` instead of `yoursite.com`.
> [Reserved Example Second Level Domain Names](https://tools.ietf.org/html/rfc2606#section-3)
```sh
cd hexo
npm install
npm test
```
NONE
> chore: use example.com for example domain

- lib/hexo/router.js
- test/scripts/console/generate.js
Fix #4499. `hexo g` fails when `--bail` is set and there is dynamically generated content from Hexo generators. The root cause of this problem is that the `writeFile` function in `lib/plugins/console/generate.js` tries to concatenate strings generated from `RouteStream`s as buffers. The fix is to convert these strings to buffers beforehand in the `RouteStream`.
```sh
git clone -b BRANCH https://github.com/ppoffice/hexo.git
cd hexo
npm install
npm test
```
Not applicable.
> fix(router): convert string to buffer in route stream

- lib/hexo/post.js
- test/scripts/hexo/post.js
Fixes #4511 
a value of yml front-matter needs to be wrapped with double-quote when it contains ":", starts with "#" (comment) or [yaml tag](https://github.com/nodeca/js-yaml#supported-yaml-types):
``` yml
---
title: unsafe: value
title: #unsafetoo
title: !!js/regexp /dangerous/
---
```
Otherwise, it's not necessary so that #4511 use case can be supported.
```sh
git clone -b optiona-escape https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> fix: avoid escaping front-matter if unnecessary

- lib/hexo/post.js
- test/scripts/hexo/post.js
Requested by https://github.com/hexojs/hexo/issues/3259 cc @noraj 
Although the behavior of ```` `{{ }}` ```` (with backtick wrap) is now working as expected since v5, user may want to use `{{ }}` without backtick wrap for certain articles (post/page). With this PR, when `disableNunjucks` are disabled globally (default) or through a [renderer](https://github.com/hexojs/hexo-renderer-marked/pull/166), user can enable it per article; at the same time, it is also possible to disable it per article even when it is enabled globally.
enabling `disableNunjucks` will disable processing of `{{ }}` / `{% %}` and [tag plugins](https://hexo.io/docs/tag-plugins).
```sh
git clone -b fm-disable-nunjucks https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
> feat: support 'disableNunjucks' in front-matter

- lib/plugins/helper/list_tags.js
- test/scripts/helpers/list_tags.js
When `style` is not `list` with `show_count` the pseudo HTML is
```html
<a class="a">
raw label
<span class="count">count</span>
</a>
```
I implemented a way to customize the label too to something like
```html
<a class="a">
<span class="label">raw label</span>
<span class="count">count</span>
</a>
```
This is 100% backward compatible, for style = list there is not change, and if `option.class.label` is not set there is no span to not break the actual behavior. The new customization only appear when  `option.class.label` is set.
```sh
git clone -b list_tags/label https://github.com/noraj/hexo.git
cd hexo
npm install
npm test
```
Put this in a template:
```pug
list_tags({show_count: true, class: {a: 'tempor', count: 'dolor', label: 'lorem'}, style: false, separator: ''})
```
My use case …
> list_tags: span element & custom class for label

- lib/plugins/helper/format.js
- lib/plugins/helper/index.js
- test/scripts/helpers/escape_html.js
- test/scripts/helpers/index.js
Expose the `escape_html` utility function from [https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js](https://github.com/hexojs/hexo-util/blob/master/lib/escape_html.js) so it can be called in templates.
Testing may not be necessary? Covered in [https://github.com/hexojs/hexo-util/blob/master/test/escape_html.spec.js](https://github.com/hexojs/hexo-util/blob/master/test/escape_html.spec.js) already.
Other `hexo-util` functions, like `strip_html`, `trim`, `titlecase`, `word_wrap`, `truncate` are untested.
> expose `escape_html` helper method for string manipulation to templates

- lib/hexo/index.js
> Deprecated: Use require.main instead.
> The process.mainModule property provides an alternative way of retrieving require.main. The difference is that if the main module changes at runtime, require.main may still refer to the original main module in modules that were required before the change occurred. Generally, it's safe to assume that the two refer to the same module.
https://nodejs.org/api/process.html#process_process_mainmodule
```sh
git clone -b require https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> Replace `process.mainModule` with `require.main`

- lib/hexo/load_plugins.js
When there are multiple hexo themes in package.json, the ones that are not activated will be loaded as plugins, which will cause errors
See also https://github.com/hexojs/hexo/pull/4111
> fix(load_plugins): ignore plugin whose name is started with "hexo-theme"

- package.json
Fix https://github.com/hexojs/hexo/issues/4594
```
- fix(load_plugins): ignore plugin whose name is started with "hexo-theme" @stevenjoezhang [#4592]
- Replace `process.mainModule` with `require.main` @stevenjoezhang [#4583]
- expose `escape_html` helper method for string manipulation to templates @awwong1 [#4581]
- list_tags: span element & custom class for label @noraj [#4578]
- fix(codeblock): closing code fence may be followed only by spaces @stevenjoezhang [#4574]
- docs(badge): replace david-dm with more reliable shields.io @curbengh [#4538]
```
> release: 5.3.0

- lib/plugins/filter/after_post_render/excerpt.js
- test/scripts/filters/excerpt.js
Issue resolved: https://github.com/hexojs/hexo/issues/4626
```sh
git clone -b more https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> fix(excerpt): use span instead of anchor element for better SEO performance

- lib/hexo/load_config.js
- test/scripts/hexo/load_config.js
See this description about `url` and `root`, https://github.com/hexojs/hexo-starter/blob/3d337683d271aa28e5bebd31dd35ba12a7a2be82/_config.yml#L15
We can know that  `url` and `root` are closely related, so why do we configure it twice? `root` can be generated by `url`
```yml
url: https://hexo.io/foo
```
```sh
cd hexo
npm install
npm test
```
> feat: handle config.root is not exist

- lib/extend/console.js
#4136 
Before we migrate Hexo to typescript, we could first bring up JSDoc. It will not only help the migration later but also provides the autocompletion for those plugin developers.
cc @septs
```sh
git clone -b jsdoc-type-extend-console https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> doc(extend/console): add jsdoc

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
Since #3489, no draft assets are generated. This is the desired behavior when not rendering draft posts. But when working on drafts, the according assets are never rendered. This change checks if draft posts should be rendered, and if this is the case, the assets will not be deleted.
I validated this fix by
- Running `hexo clean && rm -rf public/ && hexo generate` - Draft assets are not generated (as before)
- Running `hexo clean && rm -rf public/ && hexo generate --draft` - Draft assets are generated
- Running `hexo server --draft` - Draft assets are generated
- Adjusting the existing unit test
Fixes: #4556
> Generate draft assets in draft mode

- lib/plugins/helper/list_tags.js
- test/scripts/helpers/list_tags.js
escape the HTML in Tag values. It should be text, not HTML
This is a breaking change as some people might have been relying on this use case (having html in tags) 
and documentation should be updated to explain that when using function transform, value should be escaped if needed
> Escape HTML  by default in list_tag

- lib/hexo/post.js
- test/fixtures/post_render.js
- test/scripts/hexo/post.js
Replace regexp with the state machine.
```sh
git clone -b post-render-escape-swig https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> refactor/perf(post): use state machine to escape swig tag

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Fixed to be able to set different URLs for `og:image` and `twitter:image`.
There is no aspect ratio specification in `og:image`.
On the other hand, `twitter:image` has an aspect ratio regulation according to the value of `twitter:card`.
* [summary_large_image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image)
> Images for this Card support an **aspect ratio of 2:1** with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. 
* [summary](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary)
> Images for this Card support an **aspect ratio of 1:1** with minimum dimensions of 144x144 or maximum of 4096x4096 pixels.
We want to optimize the image display when an article is shared on SNS. For example, …
> feat(open_graph): different URLs for `og:image` and `twitter:image`

- lib/hexo/index.js
- lib/hexo/load_plugins.js
- test/scripts/hexo/load_plugins.js
Resolve https://github.com/hexojs/hexo-renderer-marked/issues/205#issuecomment-912917230
See also https://github.com/hexojs/hexo/pull/4112 https://github.com/hexojs/hexo/pull/2558
```sh
git clone -b theme-pluginhttps://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> feat: load hexo plugin in the theme's package.json

- lib/hexo/index.js
- lib/hexo/load_plugins.js
- lib/hexo/post.js
- lib/hexo/render.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
- Make some functions pure and move them to the top level
- Avoid some Promise overhead
> Avoid nested promise and use as less `.then` as possible (Every `then` the promise implementation will push the task into the next tick of the event loop)
- Utilize Array method on non-performance-intensive tasks
- Avoid using `new Promise`
> The author of Bluebird once mentioned `new Proimse` is slow. And during my recent tests ([benchmark suite](https://github.com/SukkaW/promise-performance-tests)), it is indeed slower than directly returned Promise, also uses more memory.
```sh
git clone -b perf-refactor https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> perf: overall improvements

- lib/hexo/post.js
- test/fixtures/post_render.js
1. For the following content
```
{% mermaid graph TD %}
A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
{% endmermaid %}
```
The current state machine implementation will parse `{% mermaid graph TD %}` and `{% endmermaid %}` as two separate in-line swig tags (https://github.com/hexojs/hexo/pull/4780)
2. And according to the static analysis from lgtm, `swig_tag_name_begin` on line 123 of `lib/hexo/post.js` is always true
https://lgtm.com/projects/g/hexojs/hexo?mode=list
Both issues are resolved in this pull request.
```sh
git clone -b swig https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```
> fix(post): escape swig full tag with args

- package.json
Following the breaking change on list_tags, I propose to release a v6 of Hexo
cf https://github.com/hexojs/hexo/commit/042f86294691f7a18ab27b853dd7066d6aed1408
I checked, and this was the only commit to release v5:  https://github.com/hexojs/hexo/commit/14890743dd00e1a1e7c4bd9c7ef632f609d35a4c
I would also suggest to update all dependencies that are not yet updated before releasing v6 (devDependencies)
Anyone wanted to add something to the v6 ?
We should also prepare a blog post to announce the release :)
> Hexo 6.0.0

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
It alleviates the problem on the rendering asset files as posts, if `post_asset_folder` is set to `true`, by restricting the rendered file types to the default new post type (`new_post_name`). 
Caveat: Doesn't work with MD files as assets, when your default file type is MD. 
It is not a final solution, as it would be better to identify to subfolder as asset folder in this stage of code execution.
```sh
cd hexo
npm install
npm test
```
1. Set `post_asset_folder` to `true` in `_config.yml`
2. Create new post
3. Create subfolder (without leading underscore!) in newly created asset folder for the post
4. Copy a HTML, JS or CSS file into the subfolder
5. run `hexo generate`
None of the subfolders files should be rendered as post, as it will …
> fix(#1490): if `post_asset_folder` is set, restrict renderable files to default file extension

- lib/hexo/index.js
Hexo uses browserify's `resolve` to resolve a path of a plugin by default, which is incompatible with [`@vercel/nft`](https://github.com/vercel/nft). See also: https://github.com/vercel/nft/issues/257
So we use Node.js's built-in `require.resolve` by default (which is compatible with `@vercel/nft`), fallback to `resolve.sync` only when the module is not found (or other errors).
Since there are no other significant behavior differences (from hexo's usage) between `resolve.sync` and `require.resolve`, we should drop `resolve` from dependency in the future.
```sh
git clone -b fix-plugin-resolve https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```
> fix: plugin loading conflict with @vercel/nft

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/commenter.yml
It's now very easy to check out a Pull Request with GitHub’s official command line tool: https://github.com/cli/cli
See also https://github.com/hexojs/hexo/pull/3396
> github(pull_request_template): remove `How to test` section

- lib/plugins/renderer/yaml.js
- package.json
Repair backwards compatibility https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md
with a bunch of plugins that use these yaml tags.
e.g.: https://github.com/lavas-project/hexo-pwa#options uses these yaml tags in the routes `!!js/regexp`
Fixes backwards compatibility for some plugins that make use of js-yaml tags.
This broke since the hexo 5.4.0 release that bumps `js-yaml` to v4.0.0.
See: 
https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md#400---2021-01-03
and
https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md
for details.
> ⚠️ This fix is required for both the 5.x release as well the 6.x release.
> Fix js-yaml tags for v4.0.0+

- lib/plugins/tag/code.js
- lib/plugins/tag/include_code.js
- test/scripts/tags/code.js
Addresses #4516 
Accepts an optional threshold to only show line numbers as long as the numbers of lines of the code block exceed such threshold.
```sh
git clone -b issue-4516 https://github.com/dbelokon/hexo.git
cd hexo
npm install
npm test
```
I don't have any screenshots, yet.
> Add line threshold option for codeblocks

- lib/plugins/renderer/yaml.js
- package.json
This PR for apply https://github.com/hexojs/hexo/pull/4869 to `5.4.x`.
I will release `5.4.1` after merge this PR.
This PR target branch is `5.4.x` not a `master`.
> Fix js-yaml tags for v4.0.0+ (#4869)

- .mocharc.yml
- test/index.js
This deprecates the old `require('chai/register-should')` which causes the test to fail.
> chore/test: use chai#should

- lib/hexo/default_config.js
- lib/plugins/filter/before_post_render/backtick_code_block.js
- test/scripts/filters/backtick_code_block.js
Signed-off-by: corvofeng <corvofeng@gmail.com>
Only wrap some languages' code with `<pre>` and `<code>`, and do no render all tags(span, and br) in content, so that user could process those languages ​​freely.
```sh
git clone -b exclude_highlight_lang https://github.com/corvofeng/hexo.git
cd hexo
npm install
npm test
```
`config.yaml`:
```yaml
highlight:
enable: true
line_number: true
auto_detect: false
exclude_languages:
- flowchartjs-code
```
Blog code:
\`\`\`flowchartjs-code
st=>start: Start:>http://www.bing.com[blank]
e=>end:>http://www.bing.com
op1=>operation: My Operation
sub1=>subroutine: My Subroutine
cond=>condition: Yes
or No?:>http://www.google.com
io=>inputoutput: catch something...
para=>parallel: parallel tasks
st->op1->cond
cond(yes)->io->e
cond(no)->para
para(path1, …
> Exclude some languages in code highlighting

- test/benchmark.js
Since Node.js 16, the `perf_hook` will buffer the performance entry list before the observer callback is called, causing the race condition. This PR fixes that.
This fixes the issue that the benchmark result can not be collected on Node.js 16
> chore/fix(benchmark): fix benchmark on node 16+

- lib/plugins/helper/toc.js
- test/scripts/helpers/toc.js
This PR adds a new feature to hexo to control the numbering of headings by the `data-toc-unnumbered` attribute.
Using `pandoc`, code written in markdown like
```md
```
will be rendered as
```html
<h3 data-toc-unnumbered="true" id="title">Title</h3>
```
and finally unnumbered in TOC.
This PR should be merged after https://github.com/hexojs/hexo-util/pull/269 merged and published with `hexo-util`.
Closes #4860.
> feat(toc): Support unnumbered headings

- lib/plugins/helper/number_format.js
- lib/plugins/tag/code.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) or [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring) which work similarily but aren't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> chore: replace deprecated String.prototype.substr()

- package.json
> chore(deps): bump hexo-util from 2.6.0 to 2.6.1

- lib/plugins/tag/post_link.js
- test/scripts/tags/post_link.js
Throws an error if `post_link` receives no slug, or finds no post.
Is it ever okay to push a broken link? CI should fail if the author pushes a broken link (perhaps after a post filename change). 
The open issue: https://github.com/hexojs/hexo/issues/4937
> feat(tag/post_link): throw on post_link error

- .github/workflows/commenter.yml
- .github/workflows/linter.yml
- .github/workflows/release-drafter.yml
- .github/workflows/tester.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- lib/plugins/tag/include_code.js
See https://github.com/hexojs/hexo/pull/2982
> feat(tag/include_code): robust for url compuation of `view raw`

- lib/plugins/helper/paginator.js
- test/scripts/helpers/paginator.js
This pull request allows users to custom paginator's class name and force display prev & next button.
_None._
> feat(paginator): allow custom class name

- lib/plugins/helper/mail_to.js
- test/scripts/helpers/mail_to.js
The package [`querystring`](https://www.npmjs.com/package/querystring) is deprecated.
_None._
> chore(mail_to): use native URLSearchParams

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
Use [WHATWG URL API](https://nodejs.org/api/url.html) instead of the deprecated [`url`](https://www.npmjs.com/package/url) in `open_graph()` helper.
_None._
> refactor(helper/open_graph): use whatwg url api

- lib/plugins/helper/index.js
- lib/plugins/helper/is.js
- test/scripts/helpers/is.js
Added a new helper called ~~`is_index()`~~ `is_home_first_page()`. This helper will detect whether the page is a page generated by hexo-generator-index and the page number is 1.
~~In fact, I thought the functions of `is_home()` and `is_index()` should be swapped, but that would break the existing page, so I created a new helper.~~
_None._
> feat(helper/is): add `is_home_first_page()` helper

- test/scripts/extend/tag.js
> chore(test/extend/tag): async function (#3328)

- test/benchmark.js
Display performance test results in GitHub Actions using Markdown format.
ref: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
> chore: improved benchmark result in github actions

- lib/extend/tag.js
- test/scripts/extend/tag_errors.js
Error caused by the following example is not formatted by `formatNunjucksError()` (because err.message doesn't contain `Line x, Column y`), so the error message still shows `(unknown path)` which is not helpful. This PR replace it with source path.
```
{% test %}
${#var}
{% endtest %}
```
> fix(tag): show source file in unformatted error message

- package.json
c8 is a drop-in replacement for nyc. Both packages are created by Benjamin Coe (https://github.com/bcoe)
nyc is not updated for a long time, let's replace it with c8
> test: replace nyc with c8

- lib/plugins/tag/post_link.js
- test/scripts/tags/post_link.js
This PR modifies the `post_link` tag so that the "title" attribute will contain the actual post title.
I think this new behavior is better: 
* Same as the old behavior, the text will still show the title that users specified as arguments in `post_link` tag
* But once hovered, the tooltip will show full title of the actual post
In the old behavior:
* Once hovered, the tooltip will have the same content as the existing text, therefore the tooltip is not useful.
The screenshot shows the new behavior, where tooltip text is the actual post title
> let post_link use original post title as title attribute

- lib/plugins/helper/tagcloud.js
- test/scripts/helpers/tagcloud.js
Add an option to show posts count of each tag in tagcloud helper.
This pull request resolves #5047.
_None._
> feat(helper/tagcloud): show_count option (#5047)

- lib/hexo/default_config.js
- lib/plugins/filter/before_post_render/backtick_code_block.js
- lib/plugins/tag/code.js
- lib/plugins/tag/include_code.js
- test/scripts/tags/code.js
- test/scripts/tags/include_code.js
Add an option called `language_attr`.
_None._
> feat(tag/code): add `language_attr` option (hexojs/hexo-util#278)

- lib/plugins/helper/open_graph.js
- test/scripts/helpers/open_graph.js
> Don't use data-uri for og:image

- lib/hexo/default_config.js
- lib/hexo/validate_config.js
- lib/plugins/processor/asset.js
- lib/plugins/processor/post.js
- test/scripts/hexo/validate_config.js
- test/scripts/processors/asset.js
- test/scripts/processors/post.js
Breaking Change
`use_date_for_updated` should be dropped next major bump (v7.0.0)
> https://hexo.io/docs/configuration#Date-x2F-Time-format
N/A
> refactor: drop `use_date_for_updated` option for `updated_option`

- lib/plugins/processor/post.js
- test/scripts/processors/post.js
Fix #1099.
When `new_post_name` lacks `:title`, `new_post_name` is used as the slug.
_None._
> fix(#1099): hexo server error when changing the config

- lib/plugins/tag/img.js
- test/scripts/tags/img.js
Issue resolved: https://github.com/hexojs/hexo/issues/4715
> feat(tags/img): support quotes in img title and alt

- lib/plugins/tag/post_link.js
- lib/plugins/tag/post_path.js
Issue resolved: #5042
Issue resolved: https://github.com/hexojs/hexo/issues/4778
> feat(tags/post_link): search for both slug and title

- lib/hexo/index.js
- lib/models/category.js
- lib/models/post.js
- lib/models/tag.js
- lib/plugins/helper/list_categories.js
- lib/plugins/helper/list_tags.js
- test/scripts/models/category.js
- test/scripts/models/tag.js
Calling `post.tags[0].length` is slow, because Hexo will try to fetch all posts associated with one tag, which is unnecessary.
Tested with 8000 posts (copy https://github.com/SukkaLab/hexo-many-posts 16 times, with https://github.com/hexojs/hexo-starter), this patch will reduce the time of `hexo g` from ~17min to ~11min
TODO: `PostTag.find` is also slow. Need to replace it with a better data structure in the future.
See https://github.com/hexojs/hexo/issues/2579#issuecomment-1328065978
See also https://github.com/hexojs/hexo/pull/3624
> perf: reduce the number of traversals through posts

- lib/extend/index.js
- lib/hexo/scaffold.js
- lib/models/index.js
- lib/plugins/console/generate.js
- lib/plugins/console/list/index.js
- lib/plugins/helper/number_format.js
- lib/plugins/tag/img.js
Convert some `require`s to top level. They will be the static import after https://github.com/hexojs/hexo/pull/5092
Some lazyload `require`s e.g. `if (!highlight) highlight = require('hexo-util').highlight;` are left untouched.
And, found some possible bugs in #5092 
lib/plugins/console/generate.js 9ba40f4dd5894c20905a5380020833da8275015a
lib/hexo/scaffold.js 3323364f3a81b539f303f6dec4ae666bb3c34dcc
> refactor: prepare for migration to typescript

- test/benchmark.js
I have transferred the `hexo-many-posts` repo to the `hexojs` org. This should provide access for @hexojs/core to change/update the benchmark suite. The PR updates the benchmark setup.
> test(benchmark): update hexo-many-posts repo

- lib/plugins/tag/asset_img.js
- lib/plugins/tag/asset_link.js
- lib/plugins/tag/asset_path.js
- lib/plugins/tag/post_link.js
- lib/plugins/tag/post_path.js
Closes: #4479 
We just use `new URL`. No need to use `String.replace()` as #4479.
```sh
$ node
> new URL("/test", "https://example.com").pathname
'/test'
> new URL("test", "https://example.com").pathname
'/test'
> new URL("test", "https://example.com/").pathname
'/test'
> new URL("/test", "https://example.com/").pathname
'/test'
```
N/A
> refactor:  use the `WHATWG URL API` instead of `url.resolve`

- lib/hexo/post.js
- test/scripts/console/new.js
> fix: Failed to create post with special character title

- lib/box/index.js
Issue resolved: https://github.com/hexojs/hexo/issues/5166
`const stats = stat(fullpath)` returns undefined when `fullpath` is an invalid symbolic link. Calling `stats.isDirectory()` breaks the processing of other valid files.
This pull request aims to display an error message indicating the invalid file.
> fix(box): check for invalid file

- lib/box/index.ts
- lib/extend/console.ts
- lib/extend/deployer.ts
- lib/extend/filter.ts
- lib/extend/generator.ts
- lib/extend/helper.ts
- lib/extend/injector.ts
- lib/extend/migrator.ts
- lib/extend/processor.ts
- lib/extend/renderer.ts
- lib/extend/syntax_highlight.ts
- lib/extend/tag.ts
- lib/hexo/index.ts
- lib/plugins/console/index.ts
- lib/plugins/filter/index.ts
- lib/plugins/generator/asset.ts
- lib/plugins/generator/index.ts
- lib/plugins/helper/index.ts
- lib/plugins/highlight/index.ts
- lib/plugins/injector/index.ts
- lib/plugins/processor/index.ts
- lib/plugins/renderer/index.ts
- lib/plugins/tag/index.ts
- package.json
Add types to Hexo class and extend apis.
Only types are changed except for `lib/extend/tag.ts`, where I added an intermediate variable. All these changes should have no effect on runtime behavior.
This may help plugin authors who can now add hexo as devdependency and add `declare var hexo: import("hexo")` to `global.d.ts` to get better type inference.
After adds
I can get better type inference like this:
which used to be just any type.
> Refactor types

- lib/models/post_asset.js
Fixes [#2134](https://github.com/hexojs/hexo/issues/2134)
Closes [#2881](https://github.com/hexojs/hexo/pull/2881)
A better way to strip extensions on permalink in post-asset.js
To some degree, it is possible to increase plugin compatibility.
> fix(post-asset): strip extensions better on permalink

- lib/plugins/tag/post_link.ts
- test/scripts/tags/post_link.js
When using `post_link` to link a post without a title, the content of the generated link is empty.
> feat(tags/post_link): use slug when title is empty

- lib/plugins/tag/full_url_for.ts
- lib/plugins/tag/index.ts
- lib/plugins/tag/url_for.ts
- test/scripts/tags/full_url_for.js
- test/scripts/tags/index.js
- test/scripts/tags/url_for.js
> feat: add url_for and full_url_for tag plugins

- lib/hexo/index.ts
- test/scripts/hexo/load_plugins.js
Allow writing plugins or scripts with top-level await expressions.
> feat: allow top-level await in plugins or scripts

- lib/plugins/helper/css.ts
- lib/plugins/helper/js.ts
- test/scripts/helpers/css.js
- test/scripts/helpers/js.js
> fix(moize): helper function not working fine with relative_url

- lib/plugins/processor/post.ts
- test/scripts/processors/post.js
> fix: skip_render not working in post_asset_folder

- lib/hexo/index.ts
useful for plugin written in typescript or let IDE detecting it
Add global variable `hexo`. Since the release of TypeScript 3.4 there's a documented way to do it.
Useful for plugin written in typescript or let IDE typechecking detecting hexo.
script inside `scripts` folder automated detect global hexo without setting anything on IDE.
plugin using typescript.
demo improvement.
https://github.com/dimaslanjaka/hexo/tree/monorepo-v7/releases
> feat: define global variable hexo

- .github/workflows/linter.yml
- .github/workflows/tester.yml
I guess it's not always necessary to run ci. 
1. linter and tester only need to be executed when the code or environment changes
2. dependabot causes ci to run twice
1. add `paths` filter. only run ci when the code changes.
2. add `branches` filter. only run ci in specified branches.
> ci: reduce the running of ci

- lib/models/post_asset.js
> Revert "fix(post-asset): strip extensions better on permalink"

- lib/hexo/index.ts
- lib/plugins/filter/before_generate/render_post.ts
- test/scripts/filters/render_post.js
reverts #1969
fixes https://github.com/hexojs/hexo/issues/5260
Motivation for the modification: I suspect that this feature is rarely used (I noticed it for the first time today). In fact, users can access the 'site' variable through the template engine, without the need for tags within the article.
> revert: Access data files from source folder (#1969)

- package.json
>The former one should be fixed in https://github.com/hexojs/hexo-front-matter/pull/67, but since `hexo-front-matter` hasn't released a new version to include this change yet, we should still stick to v4.0.0 here to prevent type error.
_Originally posted by @Pcrab in https://github.com/hexojs/hexo/issues/5202#issuecomment-1544052137_
bump hexo-front-matter from 4.0.0 to ^4.2.0
dont merge this PR before:
> chore(deps): bump hexo-front-matter from 4.0.0 to ^4.2.0

- lib/hexo/multi_config_path.ts
- lib/plugins/console/generate.ts
fix `TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.` error. I ignore them with `@ts-ignore` when I published `v7.0.0`.
```
$ npm run build
> hexo@7.0.0 build
> tsc -b
lib/hexo/multi_config_path.ts:65:28 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
65   log.i('Config based on', count, 'files');
~~~~~
lib/plugins/console/generate.ts:172:44 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
172       log.info('%d files generated in %s', count, cyan(interval));
~~~~~
Found 2 errors.
```
N/A
> fix(types): cast from `number` to `string` explicitly

- .github/workflows/benchmark.yml
fix #5332
- [marocchino/sticky-pull-request-comment#basic](https://github.com/marocchino/sticky-pull-request-comment/blob/main/README.md#basic)
- https://github.com/hexojs/hexo/blob/268882b19a9a8510ce7df7d8a978ba2dd130d7be/.github/workflows/commenter.yml#L11
> ci(benchmark): add PR permissions for comment

- lib/plugins/tag/post_link.ts
- test/scripts/tags/post_link.js
Supports using `post_link` tag with urls containing hashes. For example `{% post_link my-post-slug#my-hash 'My Linked Post Title' %}`.
This PR solves this issue https://github.com/hexojs/hexo/issues/5333
--
> Added URL hash support for post_link tag

- .github/workflows/benchmark.yml
- .github/workflows/commenter.yml
- fix #5332, fix #5334
- fix #5335
demo: https://github.com/uiolee/test-hexo-commenter/pull/34
> ci(commenter): use workflows_run event to comment flamegraph

- lib/hexo/post.ts
- test/scripts/hexo/post.js
fix #5301
fix https://github.com/hexojs/hexo-renderer-pandoc/issues/60
Before escape tags, check if it contains a complete tag.
In others words, just escape complete tags.
> fix(escapeAllSwigTags): check tag completeness

- package.json
`prepublish` has been [deprecated](https://docs.npmjs.com/cli/v9/using-npm/scripts#life-cycle-scripts).
N/A
-----
Thanks :)
> chore: use `prepublishOnly` instead of `prepublish` and run `npm install` in `prepublishOnly` script

- lib/hexo/index.ts
- lib/plugins/generator/asset.ts
- lib/plugins/generator/post.ts
- lib/plugins/helper/css.ts
- lib/plugins/helper/date.ts
- lib/plugins/helper/favicon_tag.ts
- lib/plugins/helper/feed_tag.ts
- lib/plugins/helper/fragment_cache.ts
- lib/plugins/helper/full_url_for.ts
- lib/plugins/helper/image_tag.ts
- lib/plugins/helper/is.ts
- lib/plugins/helper/js.ts
- lib/plugins/helper/link_to.ts
- lib/plugins/helper/list_archives.ts
- lib/plugins/helper/list_categories.ts
- lib/plugins/helper/list_posts.ts
- lib/plugins/helper/list_tags.ts
- lib/plugins/helper/markdown.ts
- lib/plugins/helper/meta_generator.ts
- lib/plugins/helper/open_graph.ts
- lib/plugins/helper/paginator.ts
- lib/plugins/helper/partial.ts
- lib/plugins/helper/search_form.ts
- lib/plugins/helper/tagcloud.ts
- lib/plugins/helper/url_for.ts
- lib/theme/index.ts
- lib/types.ts
- package.json
> refactor: refactor types

- package.json
> chore(deps-dev): Limited `@types/node` version

- lib/hexo/index.ts
based on https://hexo.io/api/index.html#Exit method `hexo.exit()` is not always has callback function, make it optional for better typing with typescript
> chore: make callback on exit optional

- lib/box/index.ts
- lib/models/post_asset.ts
- lib/plugins/tag/asset_img.ts
- lib/plugins/tag/asset_link.ts
- lib/plugins/tag/asset_path.ts
- lib/plugins/tag/post_link.ts
- lib/plugins/tag/post_path.ts
- test/scripts/models/post_asset.ts
- test/scripts/tags/post_link.ts
Issue resolved: https://github.com/hexojs/hexo/issues/5383
> fix(tag): use url_for

- lib/box/index.ts
- lib/plugins/processor/asset.ts
- lib/plugins/processor/post.ts
- lib/theme/processors/source.ts
- test/scripts/box/box.ts
- test/scripts/processors/asset.ts
- test/scripts/processors/post.ts
- test/scripts/theme_processors/source.ts
I have noticed that currently on Windows, paths in Hexo are converted frequently. For example, when adding files to the `ctx.model('Cache')` database, the path separators `\` are replaced with `/`, and later when Assets use these paths, the `join` function is called, which on Windows, will replace `/` back with `\`. This pull request aims to standardize the separator in the cache's `_id` to match the current operating system's support and to avoid using hardcoded separators (using `path.sep` instead). It will not change existing functionalities but is intended to improve the uniformity and maintainability of the code.
~~WIP: pending https://github.com/hexojs/hexo/pull/5385~~
> refactor: backslashes on Windows

- lib/hexo/index.ts
https://github.com/hexojs/hexo/issues/5380#issuecomment-1871282281
revert some changes of #5119
fix #5380
fix #5367
> revert(categories,tags): revert behavior of locals.tags and locals.categories

- lib/hexo/load_plugins.ts
- lib/hexo/multi_config_path.ts
- lib/hexo/post.ts
- lib/hexo/render.ts
- lib/hexo/update_package.ts
- lib/plugins/helper/number_format.ts
- lib/plugins/renderer/nunjucks.ts
- lib/plugins/tag/include_code.ts
- package.json
- test/scripts/console/config.ts
- test/scripts/console/render.ts
- test/scripts/hexo/update_package.ts
> chore(deps): bump hexo-fs from ^4.1.1 to ^4.1.3

- lib/plugins/tag/include_code.ts
- test/scripts/tags/include_code.ts
Issue resolved: https://github.com/hexojs/hexo/issues/5250
~~WIP: Not working on Windows~~
> fix(tag/include_code): prevent path traversal

- lib/plugins/processor/post.ts
- refs: 
- https://github.com/hexojs/hexo/issues/2579#issuecomment-2053889785
- https://github.com/hexojs/hexo/issues/5456
I think other issues also related this PR
`config.post_asset_folder` is enabled.
When `config.post_asset_folder` is enabled, Hexo calls the `Post.toArray()` function for each file. The time complexity of `Post.toArray()` is `O(n)`. Additionally, Hexo uses the `Post.find` method to search for the post, and the average time complexity of `find` is also `O(n)`.
So, if there are 100 articles and 100 files, the time complexity would be `O(100 * 100 * 100) = O(n^3)`.
Avoid calling `Post.toArray()`. Instead, we will search based on whether the directory where the files are stored (`assetDir`) matches. Also, if the file found with `PostAsset`, use `Post.findById`. The time …
> perf(processor/post): improve processing speed when `config.post_asset_folder` is enabled

- lib/hexo/post.ts
- test/scripts/hexo/post.ts
> feat(renderScaffold): deepMerge frontMatter of post and scaffold

- lib/hexo/default_config.ts
- lib/plugins/processor/post.ts
- test/scripts/processors/post.ts
use `slug` as `title` of post when `title` is not specified.
closed #5372
> feat: add option to use slug as title of post

- lib/box/index.ts
- lib/plugins/processor/asset.ts
- lib/plugins/processor/post.ts
- lib/theme/processors/source.ts
- test/scripts/box/box.ts
- test/scripts/processors/asset.ts
- test/scripts/processors/post.ts
- test/scripts/theme_processors/source.ts
This reverts commit 80dafe2ab62f229e03d6af95c7e6a3abb5f257ab.
Fix https://github.com/hexojs/hexo-renderer-marked/issues/281
> Revert "refactor: backslashes on Windows (#5457)"

- lib/plugins/helper/toc.ts
- test/scripts/helpers/toc.ts
Added the ability to set an upper limit on the number of items in the table of contents output by the `toc()` helper.
If no value is specified, the default is `Infinity`. This is no different from previous behavior. If we specify a number greater than or equal to 1, the elements will be truncated in the following order.
* Delete items from descendants to ancestors (from `<h6>` to `<h1>`) to fit within the specified number.
* Subheadings, which are lower-level headings on the page, will be removed in groups by level.
* The behavior differs only for the highest heading that appears on the page, which is deleted sequentially from the back.
For example, if we have a heading like this:
> \## 1
> \### 1-1
> \### 1-2
> \## 2
> \### 2-1
If `5` is specified for `max_items`, all items will be …
> feat(helper/toc): specify maximum number of items to output

- lib/extend/helper.ts
- lib/extend/processor.ts
- lib/plugins/filter/template_locals/i18n.ts
- Apply hexo context for `this` callback, useful for plugin written with typescript. [Sample](https://github.com/dimaslanjaka/hexo-renderers/blob/147340f6d03a8d3103e9589ddf86778ed7f9019b/src/helper/related-posts.ts#L106-L113)
- Fix some missmatch type (fail compile fixed)
based on https://hexo.io/api/helper#How-do-I-use-another-registered-helper-in-my-custom-helper
> feat: bind hexo context to helper function callback

- .github/workflows/benchmark.yml
- .github/workflows/linter.yml
- .github/workflows/tester.yml
- package.json
Versions of Node.js prior than 16 are already in End-Of-Life status. We should upgrade the supported Node.js versions in `package.json`. The required Node.js versions for other Hexo plugins also need to be upgraded accordingly.
> chore: drop Node.js 16

- lib/plugins/processor/common.ts
- test/scripts/processors/common.ts
`ignoreTmpAndHiddenFile` function is unused.
N/A
> refactor(common): delete unused function `ignoreTmpAndHiddenFile`

- .husky/pre-commit
- package.json
The current `.husky/pre-commit` is not working on windows. If we update `husky` to `9.x`, it works.
Please see [husky migration guide](https://github.com/typicode/husky/releases/tag/v9.0.1).
N/A
> chore(deps): migrate `husky` from `8.x` to `9.x`

- package.json
after #5417, `pretest` is not required.
> delete scripts `pretest`

- lib/plugins/filter/post_permalink.ts
- test/scripts/filters/post_permalink.ts
> feat: add permalink variable `timestamp`

- lib/extend/injector.ts
- lib/plugins/helper/list_archives.ts
add cache for posts when relative_link is true(we cannot use cache in template)
before
after
> perf(listArchives): add cache for posts

- lib/extend/syntax_highlight.ts
- lib/plugins/filter/before_post_render/backtick_code_block.ts
- lib/plugins/highlight/highlight.ts
- lib/plugins/highlight/prism.ts
- lib/plugins/tag/code.ts
- test/scripts/filters/backtick_code_block.ts
> feat: Support additional options for Backtick Code Block

- lib/models/page.ts
- lib/models/post.ts
- lib/models/types/moment.ts
- lib/plugins/processor/asset.ts
- lib/plugins/processor/common.ts
- lib/plugins/processor/post.ts
- test/scripts/models/moment.ts
- test/scripts/processors/common.ts
1. According to https://github.com/hexojs/hexo/issues/3282#issuecomment-462077102, variables in `ctx.config` in `lib/models/page.ts` and `lib/models/post.ts` are Hexo default config, instead of variables from `_config.yml`.
Removing the code only affects its own unit tests, no other functionalities are affected.
I propose to remove it because it's not used and may cause confusion when developing timezone-related features.
2. Besides, I renamed `timezone` function in `common.ts` to `adjustDateForTimezone`, to make the name more precise.
> refactor(moment): remove unused timezone setting

- lib/hexo/load_config.ts
- lib/hexo/load_theme_config.ts
- test/scripts/hexo/load_config.ts
I've noticed that Hexo supports searching for configuration files with different suffixes, such as `_config.txt` and `_config.json`. However, this check is very loose, meaning that `_config.backup` or `_config.yml.bak` are also considered valid configuration files. This feature can cause confusion and even security issues for users. Therefore, I refactor this feature in the pull request.
> feat(load_config): enforce stricter extension checks

- lib/plugins/helper/partial.ts
Interestingly, just modifying this single line can significantly reduce the overhead of ObjectAssign.
8x hexo-many-posts + hexo-theme-reimu
before
after
> perf: reduce ObjectAssign overhead
