lib/models/post.js
test/scripts/models/post.js

Use CUID to find parent category.
This fix solve #1132.

Fix post.setCategories() to solve #1132

---

lib/plugins/helper/is.js
test/scripts/helpers/is.js

Changes to be committed:
modified:   lib/plugins/helper/is.js
modified:   test/scripts/helpers/is.js

Fixes #1088, update test case

---

lib/plugins/helper/debug.js
lib/plugins/helper/index.js

On branch add-debug-helper
Changes to be committed:
new file:   lib/plugins/helper/debug.js
modified:   lib/plugins/helper/index.js

add helper function 'inspect()'

---

test/scripts/hexo/post.js

Add test for coverage.
* post.create() with data.content
* post.create() with callback
* post.publish() with callback

Add test for improve coverage

---

lib/hexo/default_config.js
lib/plugins/filter/before_post_render/backtick_code_block.js

As master branch is ahead of dev, I made this MR onto master.
For more information, see [Issue #1224](https://github.com/hexojs/hexo/issues/1224)

Feature #1224 disable highlight auto detect

---

test/scripts/filters/backtick_code_block.js
test/scripts/filters/i18n_locals.js

Add test for plugins/filter to improve coverage.

Add test for plugins/filter to improve coverage.

---

lib/plugins/helper/list_categories.js
test/scripts/helpers/list_categories.js

Option for function `list_categories` to indicate that there are child-categories

Categories show children indicator

---

lib/plugins/helper/tagcloud.js
test/scripts/helpers/tagcloud.js

The links need a whitespace so they can wrap

Add whitespace after tagcloud links

---

lib/plugins/helper/gravatar.js

When blog is on https, there is warning if all resources are not on https...

Fix https warning

---

lib/plugins/filter/after_post_render/excerpt.js
test/scripts/filters/excerpt.js

Fix regular expression to allow any space combinations.

Fix more excerpt

---

lib/models/post.js

Modify tag_id to category_id in line 153.

Modify the error

---

lib/plugins/processor/post.js

fix "date" attribute default value #1522

fix "date" attribute default value #1522

---

lib/plugins/console/index.js
lib/plugins/console/list/category.js
lib/plugins/console/list/index.js
lib/plugins/console/list/post.js

I add a `hexo list category` command to list all category with name and length.
of course, you can use `cate` to replace `category`, which more simple.
And more, `hexo list post` command show post's category and tags now.

category can been list in hexo list command.

---

package.json
test/fixtures/post_render.js
test/scripts/box/file.js
test/scripts/processors/post.js

Fix all test errors
- Ignore milliseconds for the post test cases
- Fix cache key name error for box file test cases

Fix test errors

---

lib/plugins/helper/open_graph.js
test/scripts/helpers/open_graph.js

`keywords` meta is important in SEO. We use the tags as keywords for each blog.

keywords supported in open_graph

---

lib/plugins/helper/toc.js
test/scripts/helpers/toc.js

An toc option to use headings whose depth is at most maxdepth.

Add a new option `max_depth` to the helper `toc`

---

lib/plugins/helper/open_graph.js
test/scripts/helpers/open_graph.js

hexo\lib\plugins\helper\open_graph.js:70
在測試上給的資料是陣列，但是在正式的情況下給的是Getter的property。
導致Array.isArray(keywords)會return  false。
以至於<meta name="keywords">在正式的情況根本不會產生。

fixed <meta name="keywords"> not generated

---

lib/hexo/load_plugins.js
test/scripts/hexo/load_plugins.js

Add npm scoped package support

---

README.md
package.json

Revert "Activating Open Collective"

---

README.md
package.json
test/scripts/generators/post.js

Revert 2494 opencollective

---

lib/plugins/generator/post.js
test/scripts/generators/post.js

Revert #2262 Changes

---

lib/plugins/filter/after_post_render/index.js

Fix the issue #2538

---

lib/extend/tag.js
test/scripts/extend/tag.js
test/scripts/hexo/post.js

Revert "Fix parsing error about <code> tag (Issue #2563)"

---

.github/stale.yml

Resolve #2637.
- [-] Add test cases for the changes.
- [-] Passed the CI test.
Need Owner Membership of hexo to integrate probot-stale. See https://github.com/probot/stale#usage

chore(probot-stale): add probot-stale configuration

---

lib/plugins/helper/url_for.js

fix for "TypeError: this.relative_url is not a function" error, issue #2426

fix relative_url reference

---

lib/plugins/helper/url_for.js

Revert "fix relative_url reference"

---

lib/models/post.js

Fix relative_url issue #2426

---

.travis.yml
lib/plugins/filter/before_post_render/backtick_code_block.js
test/scripts/filters/backtick_code_block.js

as markdown begin code block:
```
```js   -> js code block without line number
```js=  -> js code block with line number, start in 1
```js=3 -> js code block with line number, start in 3
```

sel code block line number

---

package.json

Hmm, it should have been included in 3.3.9, anyway we can publish it on 3.3.10.
- [-] Add test cases for the changes.

chore(package): upgrade hexo-log to version 0.2.0

---

lib/plugins/helper/is.js
test/scripts/helpers/is.js

当我使用`is_current`的时候, 例如我在首页 `is_current('/') `得到的结果却是`false`，而像`landscape`这种主题，menu中的路径都是以 `/` 开头. 因此修改了`isCurrentHelper`方法

fix is_current bug

---

package.json
test/.eslintrc
test/scripts/box/file.js

Fix file stat test

---

appveyor.yml

remove nodejs_version: 9 until npm supports

---

package.json

Use eslint-ci to improve CI build time

Use eslint ci

---

lib/plugins/helper/toc.js
test/scripts/helpers/toc.js

fix(toc): title should escape html entities

---

lib/plugins/helper/toc.js
test/scripts/helpers/toc.js

fix(toc): use escaped text to generate toc from heading

---

lib/hexo/router.js
lib/plugins/console/generate.js
lib/plugins/console/index.js
test/scripts/console/generate.js

I've prepared an example repository when you can reproduce the bug: https://github.com/ertrzyiks/hexo-pug-syntax-error-example
Errors from the routing was not propagated in `hexo generate` command.
For example: the exit code was still 0 when the theme had syntax errors.
I use pug renderer. When I put 
```
link(rel="stylesheet"
```
The `hexo generate` should fail. It happily proceeds right now. This PR introduces `--bail` switch, which will make generate command to exit with an error in case of any error.
Example of usage:
```
hexo generate --bail
```
<details>
<summary>The output of the current version</summary>
```
> yarn build
yarn build v0.27.5
$ hexo generate
INFO  Start processing
INFO  Files loaded in 67 ms
Unhandled rejection Error: …
```

Add --bail option to handle errors thrown in generate command

---

appveyor.yml

Testing against nodejs_version 9 on appveyor.

chore(appveyor): add nodejs_version 9

---

lib/plugins/helper/date.js
package.json

Update eslint config hexo

---

package.json

upgrade cheerio

---

lib/hexo/post.js
test/scripts/hexo/post.js

I got callback as an argument, but ignored it.
Along with this correction, refactoring is carried out.

Fix that callback of Post.render () is not used

---

.github/CONTRIBUTING.md

Remove the JSCS (Migrated to ESLint) in CONTRIBUTING.md

doc(CONTRIBUTING.md): remove jscs

---

package.json

chore(package): update hexo-fs to 1.0.0

---

lib/extend/tag.js
lib/hexo/index.js
lib/hexo/post.js
test/scripts/extend/index.js
test/scripts/extend/tag_errors.js

Better tracing on error

---

lib/extend/filter.js

findIndex() to indexOf()

---

lib/plugins/generator/asset.js

Use spread syntax

---

lib/plugins/helper/css.js
lib/plugins/helper/js.js

Refactor(helper): array reduce

---

lib/plugins/tag/include_code.js

Refactor(tag): includeCodeTag

---

.github/ISSUE_TEMPLATE.md

I added a min nodejs version, because I saw multiple issues where the only issue was nodejs < 6
I also asked for a github repo, which would help us having more information from the beginning

Add nodejs min version + ask for github repo

---

README.md

Brush up a document for Contributor.
No need.
No need.

chore: update README for Contributing

---

.github/ISSUE_TEMPLATE.md

updating ISSUE_TEMPLATE.md
Updates spell check in ISSUE_TEMPLATE.md
NA
NA

updating ISSUE_TEMPLATE.md

---

README.md

Fixes https://github.com/hexojs/hexo/commit/0c115f7153ef535e956f269f2cabce9fc209ad21#commitcomment-34291408

docs(readme): add opencollective link

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature-request-improvement.md
.github/ISSUE_TEMPLATE/other.md
.github/ISSUE_TEMPLATE/question-help.md

Create new GitHub issue template.
New issue template may help users & contributors. Also maintainers.
> [Creating issue templates for your repository](https://help.github.com/en/articles/creating-issue-templates-for-your-repository)
Nothing
Nothing
I do not set a default label. Because issue author cannot define certainly which issue types. So, we should triage an issue later.

chore: update issue templates

---

.github/FUNDING.yml

Display a [Sponsor button](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) on the repo, which links to [Open Collective](https://opencollective.com/hexo). Suggested by @YoshinoriN https://github.com/hexojs/hexo/commit/0c115f7153ef535e956f269f2cabce9fc209ad21#commitcomment-34319307

Add Sponsor button

---

lib/plugins/helper/list_tags.js
test/scripts/helpers/list_tags.js

Add tags markup using [Schema](https://schema.org/keywords) and [Microformats](http://microformats.org/wiki/rel-tag).
```sh
git clone -b schema https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

feat(list_tags): add Schema "keywords" and Microdata "tag"

---

lib/plugins/helper/gravatar.js
package.json

https://github.com/hexojs/hexo-util/pull/81
```sh
git clone -b gravatar https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
~~- [ ] Add test cases for the changes.~~

 refactor(gravatar): utilize hexo-util module

---

lib/models/types/moment.js
package.json

chore(deps): update warehouse requirement from ^2.2.0 to ^3.0.0

---

test/scripts/console/render.js

just noticed an empty unit test.
```sh
git clone -b empty-test https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

test: remove empty test

---

.eslintrc.json
lib/extend/tag.js
lib/plugins/tag/code.js
test/scripts/console/list_categories.js
test/scripts/console/list_page.js
test/scripts/console/list_post.js
test/scripts/console/list_tags.js

part of https://github.com/hexojs/eslint-config-hexo/pull/22
ref: https://eslint.org/docs/rules/prefer-arrow-callback
```sh
git clone -b arrow https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

style: prefer-arrow-callback

---

lib/extend/tag.js
test/scripts/hexo/multi_config_path.js

https://github.com/hexojs/eslint-config-hexo/pull/22
config used:
``` json
"no-var": "error",
"prefer-const": ["error", { "ignoreReadBeforeAssign": true }]
```
```sh
git clone -b const https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

style: no-var & prefer-const

---

test/scripts/box/box.js

Fix up Issue #3759 
When "npm test" runs multiple times, a test case in `test/scripts/box/box.js` fails occasionally.
This is caused by a potential race condition.
The test case "process() - hash changed" fails
if it starts and finishes within wall-clock timer tick (=1ms).
This can be explained by the implementation of "box.Cache" (`lib/models/cache.js`).
"box.Cache" makes decision about "cache hit/miss" based on "mtime" and "hash" of target file.
"box.Cache" says "cache miss" only when both "mtime" and "hash" are changed.
The test case expects that "box.Cache" says "cache miss" always when "hash" is changed.
Unfortunately "box.Cache" says "cache hit" if "mtime" is not changed.
This patch is to clarify and complement these test cases.
```sh
$ while npm test; do :; done
```

Fix up potential race condition in test cases of "box" (fix #3759)

---

README.md

Make Hexo's README more beautiful. May publish with Hexo v4.
https://github.com/SukkaW/hexo/blob/new-readme/README.md

docs: new README for hexo

---

lib/plugins/helper/toc.js

This PR is a part of #3753
```sh
git clone -b drop-loadsh-for-toc-helper https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(toc_helper): replace lodash with hexo-util

---

lib/plugins/helper/date.js

This PR is a part of #3753
```sh
git clone -b drop-lodash-for-date-helper https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(date_helper): drop lodash

---

.travis.yml

```sh
cd hexo
npm install
npm test
```

Travis CI: The sudo: tag is now deprecated in Travis

---

lib/plugins/filter/post_permalink.js

This PR is a part of #3753 
```sh
git clone -b drop-lodash-for-post_permalink-filter https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: drop lodash for post_permalink filter

---

lib/plugins/console/deploy.js

This PR is a part of #3753 
```sh
git clone -b drop-loadsh-for-plugins-console-deploy https://github.com/SukkaW/hexo.git
cd hexo
npm install
npm test
```

refactor: drop lodash for lib/plugins/console/deploy

---

lib/plugins/helper/open_graph.js
test/scripts/helpers/open_graph.js

https://github.com/hexojs/hexo/pull/3674#issuecomment-543276077 & https://github.com/hexojs/hexo/pull/3674#issuecomment-543422019
```sh
git clone -b og-helper-tags-article https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

feat(open_graph): add article:author & article:tag

---

lib/theme/index.js
lib/theme/view.js

This PR is a part of #3753, the continuation of #3807.
```sh
git clone -b reduce-lodash-lib-themehttps://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: drop lodash & es6 syntax for lib/theme

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question-help.md

We never released and currently has no plan to release bugfix for older versions.

issue_template: use latest hexo

---

test/scripts/helpers/open_graph.js

Update open_graph test case for #3805.
```sh
git clone -b fix-test-article-tag https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(open_graph): missing update for #3805

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question-help.md

Update the Nodejs version of the Issue template.
```sh
cd hexo
npm install
npm test
```

docs(ISSUE_TEMPLATE): update node.js version

---

lib/hexo/default_config.js

Continuation of https://github.com/hexojs/hexo/pull/2901
```sh
git clone -b hljs-default https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

fix(default): disable 'highlight.hljs' by default

---

lib/plugins/filter/after_post_render/external_link.js
lib/plugins/filter/after_render/external_link.js
package.json
test/scripts/helpers/full_url_for.js
test/scripts/helpers/url_for.js

- update hexo-util to 1.6.1.
- include #3847 (with new `isExternalLink()`)
- update test case for `url_for`
- The test cases for `url_for()`, `full_url_for()` with `pretty_urls` configuration.
```sh
git clone -b hexo-util-1.6 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

chore(deps): bump hexo-util to 1.6.1

---

appveyor.yml

https://www.appveyor.com/updates/2019/11/08/
~~- [ ] Add test cases for the changes.~~

ci(appveyor): add node 13

---

lib/box/index.js
test/scripts/box/box.js

https://github.com/hexojs/hexo/issues/3904#issuecomment-562160070
cc @dailyrandomphoto 
```sh
git clone -b ignore-null https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

fix(box): handle null "ignore:"

---

test/scripts/helpers/open_graph.js

Fix (soft) failing test due to incomplete https://github.com/hexojs/hexo/pull/3921
```sh
git clone -b test-default-locale https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

test(open_graph): add default locale

---

package.json

bugfixes + https://github.com/hexojs/hexo/pull/3917
```sh
git clone -b 4.1.1 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

release: 4.1.1

---

test/benchmark.sh

- show only 400 lines of log on a potential failed build
- use single quote to escape `!!` in shell
```sh
git clone -b benchmark-cat-fail-log https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

ci(benchmark): update error msg on fail build

---

lib/hexo/index.js

```sh
git clone -b hexo-destructure https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(hexo/index): destructure modules

---

lib/box/file.js
lib/box/index.js

```sh
git clone -b box-destructure https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(box): destructure

---

lib/hexo/post.js

Continuation of https://github.com/hexojs/hexo/pull/3780
```sh
git clone -b post-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(post): Class syntax

---

lib/plugins/tag/img.js

```sh
git clone -b imgtag-src https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(imgTag): utilize url_for

---

lib/extend/renderer.js

```sh
git clone -b renderer-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(renderer): Class syntax

---

lib/extend/helper.js

```sh
git clone -b helper-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(helper): Class syntax

---

lib/extend/generator.js

```sh
git clone -b generator-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(generator): Class syntax

---

lib/theme/index.js

```sh
git clone -b theme-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(theme): Class syntax

---

lib/hexo/locals.js

```sh
git clone -b locals-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(locals): Class syntax

---

lib/extend/filter.js

```sh
git clone -b filter-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(filter): Class syntax

---

lib/hexo/index.js
test/scripts/hexo/hexo.js

Extension of https://github.com/hexojs/hexo/pull/3938
```sh
git clone -b hexo-locals-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(hexo-locals): Class syntax

---

package.json

Preparation for #3983 #3850
```sh
git clone -b bump-hexo-util-1.8.0 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

chore(deps): bump hexo-util to 1.8.0

---

lib/plugins/helper/fragment_cache.js

Utilize `Cache()` from `hexo-util`.
```sh
git clone -b fragment_cache_utilize_util https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(fragment_cache): utilize hexo-util

---

lib/hexo/locals.js
lib/plugins/console/generate.js
test/scripts/hexo/locals.js

Utilize hexo-util's `CacheStream()` & `Cache()`;
```sh
git clone -b utilize-hexo-util-cache https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: utilize hexo-util

---

package.json

```sh
git clone -b 4.2.0 https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```
~~- [ ] Add test cases for the changes.~~

release: 4.2.0

---

lib/hexo/router.js

```sh
git clone -b router-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(router): Class syntax

---

lib/extend/console.js

```sh
git clone -b console-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(console): Class syntax

---

lib/hexo/scaffold.js

```sh
git clone -b scaffold-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(scaffold): Class syntax

---

test/scripts/helpers/is.js

```sh
git clone -b test-helpers-is-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-helpers-is): async/await

---

test/scripts/helpers/is.js

Fix asyncArrow space after merging https://github.com/hexojs/hexo/pull/3957
```sh
git clone -b style-test-helper-is https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

style(test-helper-is): asyncArrow space

---

lib/plugins/helper/feed_tag.js
test/scripts/helpers/feed_tag.js

https://github.com/hexojs/hexo-theme-unit-test/pull/25#discussion_r361982937
also add `type="application/atom+xml"` if the type can be determined.
```sh
git clone -b feed_tag-atom-rss https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

feat(feed_tag): support parsing config.feed

---

lib/plugins/helper/css.js
lib/plugins/helper/js.js
test/scripts/extend/console.js
test/scripts/helpers/tagcloud.js
test/scripts/tags/code.js

This PR is a part of #3984
```sh
git clone -b test-coverage https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(tags-plugins/helper): improve test coverage

---

test/scripts/processors/data.js

```sh
git clone -b test-processors-data https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-processors-data): async/await

---

test/scripts/filters/post_permalink.js

```sh
git clone -b test-filters-post_permalink https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

test(post_permalink): async/await

---

test/scripts/helpers/partial.js

```sh
git clone -b test-helpers-partial https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-helpers-partial): async/await

---

test/scripts/filters/new_post_path.js

```sh
git clone -b test-filters-new_post https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test_new_post_path): async/await

---

test/scripts/extend/filter.js
test/scripts/extend/generator.js
test/scripts/extend/migrator.js
test/scripts/extend/renderer.js

```sh
git clone -b test-extend-filter-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

 refactor(test-extend): async/await 

---

test/scripts/models/page.js

```sh
git clone -b test-models-page-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-models-page): async/await

---

test/scripts/theme/theme.js
test/scripts/theme/view.js

```sh
git clone -b test-theme-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-theme-theme): async/await

---

test/scripts/helpers/list_archives.js
test/scripts/helpers/list_categories.js
test/scripts/helpers/list_posts.js
test/scripts/helpers/list_tags.js

```sh
git clone -b test-helpers-list https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-helpers-list): async/await

---

test/scripts/theme_processors/view.js

```sh
git clone -b test-theme_processors-view-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-theme_processors-view): async/await

---

test/scripts/models/asset.js
test/scripts/models/cache.js

```sh
git clone -b test-models-asset-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-models-asset): async/await

---

lib/extend/tag.js

```sh
git clone -b tag-class https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(tag): Class syntax

---

test/scripts/generators/asset.js
test/scripts/generators/page.js
test/scripts/generators/post.js

```sh
git clone -b test-generators-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-generators): async/await

---

test/scripts/theme_processors/source.js

```sh
git clone -b test-theme_processors-source https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-theme_processors-source): async/await

---

test/scripts/models/category.js

```sh
git clone -b test-models-category-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-models-category): async/await

---

test/scripts/theme_processors/config.js

```sh
git clone -b test-theme_processors https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-theme_processors-config): async/await

---

test/scripts/theme_processors/i18n.js

```sh
git clone -b theme-theme_processors-i18n https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-theme_processors-i18n): async/await

---

test/scripts/helpers/tagcloud.js

```sh
git clone -b test-helpers-tagcloud https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-helpers-tagcloud): async/await

---

test/scripts/console/clean.js

```sh
git clone -b test-console-clean-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-clean): async/await

---

test/scripts/filters/render_post.js

```sh
git clone -b test-filters-render_post https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-filters-render_post): async/await

---

.travis.yml

Based on https://github.com/hexojs/hexo-renderer-less/pull/31
[Existing repos](https://github.com/orgs/hexojs/projects/4) with Travis+Windows seem to be running fine.
Appveyor is retained for now for compatibility testing, it can be dropped in 1-2 months.

ci(travis): add Windows

---

test/scripts/helpers/open_graph.js

currently if `default` test fails, it only soft fail and CI would still pass (false negative). This PR make it hard fail instead.
```sh
git clone -b og-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-open_graph): async/await

---

test/scripts/box/box.js

```sh
git clone -b test-box-box-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-box-box): async/await

---

test/scripts/console/new.js

```sh
git clone -b test-console-new https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-new): async/await

---

test/scripts/console/config.js
test/scripts/console/deploy.js
test/scripts/extend/filter.js
test/scripts/extend/tag.js

This PR is a part of #3984
```sh
git clone -b test-coverage-improve-1 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test: improve coverage

---

test/scripts/generators/page.js

```sh
git clone -b generators-age-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-generators-page): arrow function

---

lib/plugins/filter/after_post_render/external_link.js
lib/plugins/filter/after_render/external_link.js
test/scripts/filters/external_link.js

Optimize the regexp used by external_link filter
```sh
git clone -b external_link_filter https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(external_link): optimize

---

lib/models/category.js
lib/models/page.js
lib/models/post.js
lib/models/tag.js
lib/plugins/helper/css.js
lib/plugins/helper/gravatar.js
lib/plugins/helper/js.js

Replace `const url_for = require('./url_for');` with `this.url_for()` to avoid extra require and retain consistent with other helpers.
```sh
git clone -b refactor-helper https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(helper): minor changes

---

test/scripts/processors/post.js

```sh
git clone -b test-processors-post https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-processors-post): async/await

---

test/scripts/processors/asset.js

```sh
git clone -b test-processors-asset-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-processors-asset): async/await

---

test/scripts/console/publish.js

```sh
git clone -b test-console-publish https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-publish): async/await

---

test/scripts/console/render.js

```sh
git clone -b test-console-render https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-render): async/await

---

lib/box/file.js
lib/extend/migrator.js
lib/extend/processor.js

```sh
git clone -b class-syntax https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: Class syntax

---

.travis.yml
test/benchmark.sh

Attempt to fix `surge.sh` deployment.
To see if Travis CI build of this PR has succeed.

ci(flamegraph): fix 0x

---

lib/hexo/index.js
lib/plugins/generator/asset.js
lib/theme/index.js
lib/theme/view.js

```sh
cd hexo
npm install
npm test
```

refactor: simplify code

---

lib/hexo/post.js
lib/plugins/console/list/route.js

Rewrite `Object.keys()` and classic for loops into `Object.entries`.
```sh
git clone -b utilize-object-entries https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: utilize Object.entries

---

.github/workflows/linter.yml

ci: add GitHub Actions to run linter

---

test/scripts/console/migrate.js

```sh
git clone -b test-console-migrate-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-migrate): async/await

---

test/scripts/extend/tag.js

```sh
git clone -b test-extend-tag https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-extend-tag): async/await

---

lib/box/file.js
lib/box/index.js
lib/hexo/index.js
lib/hexo/source.js
lib/models/types/moment.js
lib/theme/index.js
lib/theme/view.js

```sh
cd hexo
npm install
npm test
```

Refactor(class): Replace prototype to class syntax

---

test/scripts/console/deploy.js

```sh
git clone -b test-console-deploy https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-console-deploy): async/await

---

package.json
test/index.js
test/scripts/console/config.js
test/scripts/console/deploy.js
test/scripts/console/list_categories.js
test/scripts/console/list_page.js
test/scripts/console/list_post.js
test/scripts/console/list_tags.js
test/scripts/helpers/date.js
test/scripts/helpers/debug.js
test/scripts/hexo/hexo.js
test/scripts/hexo/post.js
test/scripts/hexo/render.js
test/scripts/hexo/router.js
test/scripts/models/post.js

```sh
cd hexo
npm install
npm test
```

Refactor(test): Replace from rewire to sinon.stub()

---

test/scripts/hexo/post.js

Fix test cases added in #4161
```sh
git clone -b test-post-fix https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(post): fix cases added in #4161

---

test/scripts/console/list_categories.js
test/scripts/console/list_page.js
test/scripts/console/list_post.js
test/scripts/console/list_tags.js

```sh
git clone -b test-list-async https://github.com/curbengh/hexo.git
cd hexo
npm install
npm test
```

refactor(test-list-categories-page-post-tags): async/await

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Please see the following issue.
> https://github.com/hexojs/hexo/issues/3858
I tested my repository before submitting PR. Please see the following. The following example settings are the same with this PR.
> https://github.com/YoshinoriN/TestRepository/releases/tag/v3.0.2
N/A
N/A

chore: add release release-drafter (#3858)

---

test/scripts/hexo/load_plugins.js

- destructure syntax
- avoid async/await syntax for some cases
- **fix Appveyor CI fail**
```sh
git clone -b test-ignore-types-theme https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(load_plugins): minor changes

---

lib/hexo/index.js
test/scripts/hexo/load_plugins.js

Closes #4251 
cc @booninite @stevenjoezhang 
```sh
git clone -b fix-4251 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

fix(#4251): load_plugin with extra line EOF

---

test/scripts/box/box.js

Fix test cases that failed on macOS in https://github.com/hexojs/hexo/pull/4169#issuecomment-619465134
```sh
git clone -b test-watch-macos https://github.com/USER/hexo.git
cd hexo
npm install
npm test
```

test(box): fix test cases for macOS

---

test/scripts/helpers/css.js
test/scripts/helpers/js.js
test/scripts/hexo/load_theme_config.js

https://github.com/hexojs/hexo/issues/3984
```sh
git clone -b test-coverage-improvements https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test: coverage improvements

---

lib/hexo/index.js
package.json

- https://github.com/hexojs/hexo/issues/2492
- https://github.com/hexojs/hexo/issues/4002
```sh
git clone -b remove-lodash-from-global-variable https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor: remove lodash from global variable

---

package.json

```sh
git clone -b warehouse-4-deps https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

chore(deps): bump warehouse from 3.0.2 to 4.0.0

---

.github/workflows/tester.yml

Update tester node version

---

lib/box/index.js
lib/plugins/tag/code.js

```sh
cd hexo
npm install
npm test
```

Reduce array#reduce

---

package.json

A part of #4333. Prevent breaking changes from hexo-fs@3.1.0
```sh
git clone -b hexo-fs-3 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

chore(deps): pin hexo-fs

---

lib/plugins/console/generate.js

Co-Authored-By: segayuu <segayuu@gmail.com>
A part of #4333. 
```sh
git clone -b refactor-console-generator-class https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(console/generate): class & destructure assign

---

lib/hexo/post.js

Co-Authored-By: segayuu <segayuu@gmail.com>
A part of #4333.
Reduce promise inside `lib/posts`.
https://github.com/hexojs/hexo/pull/4333/commits/1eeef5fa33219706f9b3ffec3264be26bc8c262a
Proper author info is added.
```sh
git clone -b post-reduce-promise https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(post): reduce promise

---

lib/box/index.js
lib/plugins/console/generate.js

```sh
cd hexo
npm install
npm test
```

Reduce stream

---

test/scripts/hexo/load_config.js

```sh
cd hexo
npm install
npm test
```

refactor(test): async hexo/load_config.js

---

.github/ISSUE_TEMPLATE/bug_report.md

* Add special notice for zh_CN users (because most of them just won't follow issue template)
* Add a step about Safe mode debugging
* Provide a tip for using code blocks
No test is needed for this PR.
https://github.com/SukkaW/hexo/blob/1ecce8e6de96a49bdf891d252dda2d5d6d9ff9f6/.github/ISSUE_TEMPLATE/bug_report.md

github(issue_template): add some info

---

lib/extend/renderer.js
lib/hexo/post.js
lib/hexo/render.js
lib/hexo/router.js
lib/models/category.js
lib/models/tag.js
lib/plugins/helper/is.js
lib/plugins/helper/open_graph.js
lib/plugins/processor/asset.js
lib/plugins/processor/common.js
lib/plugins/processor/post.js
lib/plugins/tag/img.js
lib/plugins/tag/include_code.js

```sh
git clone -b es6-syntax-1 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

style: es6 string extensions & destructure

---

test/scripts/hexo/post.js

The PR closes #3543 & closes #3459.
cc @phanan
Thanks for your patience! It appears that your issue has been solved (in coming `hexo@5`)。
We lost the track that which PR fixed your issue, so in this PR we add a new test case specific for your issue.
```sh
git clone -b issue-3543 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(post): add test cases for #3543 & #3459

---

test/scripts/hexo/post.js

#4087 should be fixed by @stevenjoezhang in https://github.com/hexojs/hexo/pull/4161, this PR adds test case for #4087 to confirm the issue has been fixed.
Closes #4087. cc @hujinbo.
```sh
git clone -b fix-4087 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(#4087): add related cases

---

test/benchmark.sh

```sh
git clone -b benchmark-update https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(bencmark): minor updates

---

lib/extend/filter.js

- Return `data` directly if no registered filters.
- Make `after_render:html` as an alia of `_after_render_html`.
```sh
git clone -b perf-filter-shorthand https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

perf(filter): shorthand syntax

---

test/scripts/console/generate.js

Try to avoid unit test failure.
```sh
cd hexo
npm install
npm test
```

test(generate): add a small delay before clean up

---

lib/extend/tag.js
test/scripts/hexo/post.js

Closes #4385.
cc @dumindu 
```sh
git clone -b test-4385 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(#4385): no double escape in code block

---

test/scripts/console/generate.js

Fix potential failed test on macOS.
```sh
git clone -b test-generate-watch-delete https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

test(generate): add a longer delay after fs#unlink

---

lib/extend/injector.js
lib/hexo/load_theme_config.js
lib/hexo/post.js
lib/plugins/filter/before_post_render/backtick_code_block.js
lib/plugins/helper/paginator.js
lib/plugins/tag/code.js

Fix typos from the following files
```
lib/extend/injector.js
lib/hexo/load_theme_config.js
lib/hexo/post.js
lib/plugins/filter/before_post_render/backtick_code_block.js
lib/plugins/helper/paginator.js
```
```sh
cd hexo
npm install
npm test
```

Fix multi comments typos

---

lib/hexo/index.js

```sh
cd hexo
npm install
npm test
```

Fix a typo in comment

---

test/scripts/box/box.js
test/scripts/console/config.js
test/scripts/console/deploy.js
test/scripts/console/list_categories.js
test/scripts/console/list_page.js
test/scripts/console/list_post.js
test/scripts/console/list_tags.js
test/scripts/console/migrate.js
test/scripts/hexo/render.js
test/scripts/hexo/router.js
test/scripts/theme/view.js
test/scripts/theme_processors/config.js

https://github.com/hexojs/hexo/pull/4401#issuecomment-654151590

revert: test: replace sinon#assert

---

lib/hexo/render.js

```sh
cd hexo
npm install
npm test
```

refactor: simplify code 

---

test/benchmark.js

- Use "non-blocking" async/await
- Add profiling
```sh
git clone -b refactor-benchmark https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

refactor(benchmark): minor changes

---

lib/plugins/filter/after_post_render/external_link.js
lib/plugins/filter/after_render/external_link.js
lib/plugins/filter/after_render/meta_generator.js

```sh
cd hexo
npm install
npm test
```

Refactor: filter regexp

---

lib/plugins/tag/code.js
lib/plugins/tag/include_code.js

- lazy require `prismHighlight` & `highlight.js` for faster code start.
- shorthand for `code` tag by return code early when no highlight is enabled.
```sh
cd hexo
npm install
npm test
```

 perf(tag/code): performance improvements

---

lib/plugins/filter/before_post_render/titlecase.js

Lazy require `titlecase`.
```sh
cd hexo
npm install
npm test
```

perf(titlecase): lazy require

---

lib/plugins/filter/after_post_render/external_link.js
lib/plugins/filter/after_render/external_link.js

- Improve regexp: require less step for matching
- Adjust condition for shorthand optimization
```sh
git clone -b perf-external-link https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

perf(external_link): faster regexp & condition shorthand

---

package.json

Update hexo-util in the CI's npm cache. This has no effect on users' npm, since npm will install the latest minor version of hexo-util.
https://github.com/hexojs/hexo/pull/4423#issuecomment-663802142

chore(deps): update hexo-util from 2.0.0 to 2.2.0

---

package.json

Update hexo-cli to 4.0.0
```sh
git clone -b deps-cli-4 https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

chore(deps): update hexo-cli from 3.0.0 to 4.0.0

---

README.md

```sh
cd hexo
npm install
npm test
```

docs(readme): replace Travis badge with Actions'

---

package.json

release: 5.0.1

---

package.json

emergency bugfix https://github.com/hexojs/hexo/pull/4470
```sh
cd hexo
npm install
npm test
```

release: 5.0.2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question-help.md

```sh
cd hexo
npm install
npm test
```

chore(issue-template): fix link to Node version requirement

---

test/scripts/tags/include_code.js

```sh
cd hexo
npm install
npm test
```

refactor(test/include_code): async/await

---

test/scripts/hexo/render.js

```sh
cd hexo
npm install
npm test
```

refactor(test/render): async/await

---

test/scripts/hexo/scaffold.js

```sh
cd hexo
npm install
npm test
```

refactor(test/scaffold): async/await

---

test/scripts/hexo/update_package.js

```sh
cd hexo
npm install
npm test
```

refactor(test/update_package): async/await

---

test/fixtures/post_render.js
test/scripts/hexo/post.js

```sh
cd hexo
npm install
npm test
```

refactor(test/hexo/post): async/await

---

lib/extend/helper.js

```sh
cd hexo
npm install
npm test
```

docs(extend/helper): add jsdoc

---

test/scripts/hexo/hexo.js

https://github.com/hexojs/hexo-uglify/pull/147#pullrequestreview-483136707
```sh
cd hexo
npm install
npm test
```

test(execFilter): promise should resolve

---

.github/workflows/benchmark.yml
.travis.yml
test/benchmark.js

Closes #4413.
The PR aims to gradually migrate from Travis CI to GitHub Actions. It is the first part of #4437.
Just see if GitHub Action passed.

chore/ci: move benchmark to gh action

---

lib/hexo/validate_config.js
test/scripts/hexo/validate_config.js

Closes #4510 
```sh
cd hexo
npm install
npm test
```

fix: validate value of config.url

---

lib/plugins/filter/after_post_render/external_link.js
lib/plugins/filter/after_render/external_link.js

Faster regexp for a little bit performance improvements.
```sh
cd hexo
npm install
npm test
```

perf(external_link): faster regexp

---

package.json

release: 5.2.0

---

lib/plugins/filter/before_post_render/backtick_code_block.js
test/scripts/filters/backtick_code_block.js

Issue resolved: https://github.com/hexojs/hexo/issues/4573 
```sh
git clone -b code https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

fix(codeblock): closing code fence may be followed only by spaces

---

.github/workflows/benchmark.yml
.github/workflows/linter.yml
.github/workflows/stale.yml
.github/workflows/tester.yml

```sh
git clone -b actions https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

github: update actions/setup-node action to v2

---

lib/plugins/filter/template_locals/i18n.js

```sh
git clone -b i18n https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

fix(i18n): page.lang is undefined when using the key `language` in front-matter

---

.github/workflows/stale.yml
lib/plugins/filter/before_post_render/backtick_code_block.js
test/scripts/filters/backtick_code_block.js

See also https://github.com/hexojs/hexo/pull/4574
```sh
git clone -b backtick_code_block https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

fix(codeblock): match whitespace but not newlines

---

lib/box/index.js

Issue resolved: #4632
See also https://github.com/paulmillr/chokidar/issues/954
```sh
git clone -b watch https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

fix(box): set property awaitWriteFinish for chokidar filewatcher

---

.github/workflows/tester.yml
package.json
test/scripts/hexo/post.js

```
- feat: handle config.root is not exist @jiangtj [#4616]
- fix(codeblock): match whitespace but not newlines @stevenjoezhang [#4625]
- fix(i18n): page.lang is undefined when using the key `language` in front-matter @stevenjoezhang [#4614]
- github: update actions/setup-node action to v2 @stevenjoezhang [#4604]
- chore/ci: migrate from probot/stale to GitHub Actions @stevenjoezhang [#4598]
- fix(box): set property awaitWriteFinish for chokidar filewatcher
- fix(excerpt): use span instead of anchor element for better SEO performance @stevenjoezhang [#4627]
- chore(deps): bump js-yaml from 3.14.1 to 4.0.0 @dependabot-preview [#4607]
```
```sh
cd hexo
npm install
npm test
```

release: 5.4.0

---

lib/plugins/helper/paginator.js

Refactor pagination function, `lib/plugins/helper/paginator.js::pagenasionPartShow`
- paginatorHelper - function pagenasion
```sh
git clone https://github.com/CroMarmot/hexo.git
cd hexo
npm install
npm test
```

refactor: refactor pagination - paginatorHelper - pagenasionPartShow

---

.github/workflows/benchmark.yml
.github/workflows/linter.yml
.github/workflows/tester.yml
package.json

```sh
cd hexo
npm install
npm test
```

chore: drop Node.js 10 and add Node.js 16

---

lib/hexo/post.js
lib/plugins/processor/asset.js
lib/plugins/processor/post.js
lib/theme/index.js

https://v8.dev/blog/fast-properties
In short, the `delete` operator has a potential performance impact (related with v8 hidden class, and `delete` could cause v8 to degrade object process). By replacing `delete` operator it could gain performance.
Benchmark result:
**master branch**
```
Cold processing
┌──────────────────────────────┬───────────────┐
│           (index)            │ Cost time (s) │
├──────────────────────────────┼───────────────┤
│ Load Plugin/Scripts/Database │    '0.41s'    │
│        Process Source        │    '3.60s'    │
│         Render Posts         │    '3.36s'    │
│         Render Files         │    '7.27s'    │
│        Save Database         │    '0.35s'    │
│          Total time          │   '14.99s'    │
└──────────────────────────────┴───────────────┘
Hot …
```

perf: avoid using delete operator

---

README.md

- fixes #4570
---
cc @curoky @SukkaW

doc: add homebrew install

---

lib/hexo/post.js
test/scripts/hexo/post.js

Fix https://github.com/hexojs/hexo/pull/4780#issuecomment-926353733
```sh
git clone -b fix-post-render-escape https://github.com/hexo/hexo.git
cd hexo
npm install
npm test
```

fix(#4780): curly brackets

---

lib/hexo/post.js
test/scripts/hexo/post.js

Fix https://github.com/hexojs/hexo/pull/4780#issuecomment-927212313
cc @stevenjoezhang 
```sh
git clone -b fix-post-render-escape-empty-tag https://github.com/sukkaw/hexo.git
cd hexo
npm install
npm test
```

fix(#4780): empty tag name correction

---

.github/dependabot.yml

And add github actions updates
```sh
cd hexo
npm install
npm test
```

Cleanup dependabot

---

package.json

I'm going to release `5.4.1` after merge #4876.
This is a backport. Target branch is `5.4.x` not a `master`.

chore: bump version from 5.4.0 to 5.4.1

---

.github/workflows/benchmark.yml
.github/workflows/commenter.yml

Issue resolved: https://github.com/hexojs/hexo/issues/4437
Issue resolved: https://github.com/hexojs/hexo/pull/4535#issuecomment-694355665
```sh
git clone -b actions-flamegraph https://github.com/hexojs/hexo.git
cd hexo
npm install
npm test
```

chore/ci: reply flamegraph URL in pull request

---

package.json

chore: bump hexo-util from 2.5.0 to 2.6.0

---

package.json

I will publish the `6.1.0` after merge this PR.
Thank you :)

chore: bump version from 6.0.0 to 6.1.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/other.md

Honestly, we can't understand anything even if we confirm a theme config they are using.
IMHO, **unofficial** plugins setting is also.  (But, we can not be able anything to it soon.)

chore(ISSUE_TEMPLATE): delete `Your theme _config.yml` section

---

package.json

Update warehouse.
This version includes workaround for #4922

chore(deps): bump warehouse from 4.0.0 to 4.0.1

---

package.json

This PR is instead of #4298 
We are already merged some PR to `master` other than hotfix (#4917, #4943)
I'm going to release a new version after merge this PR.
Thank you :)

chore: bump version from 6.1.0 to 6.2.0

---

lib/hexo/index.js

Issue resolved: https://github.com/hexojs/hexo/issues/4993

fix(hexo/index): `db.json` file path in debug logging on Windows

---

package.json

chore(deps): bump hexo-util and warehouse

---

.github/ISSUE_TEMPLATE/other.md

chore: update issue template

---

package.json

chore(deps): bump hexo-log from 3.0.0 to 3.2.0

---

package.json

IMHO, we should publish `6.3.0` after merge #5017. (and if possible #4995)

release: 6.3.0

---

test/scripts/console/index.js
test/scripts/console/list_route.js

See https://github.com/hexojs/hexo/issues/3984

test(list_route): improve coverage

---

lib/plugins/helper/open_graph.js
test/scripts/helpers/open_graph.js

Issue resolved: https://github.com/hexojs/hexo/issues/5084

feat(open_graph): drop google_plus

---

lib/hexo/post.js
test/scripts/hexo/post.js

Issue resolved: https://github.com/hexojs/hexo/issues/1591
Issue resolved: https://github.com/hexojs/hexo/issues/2522
Issue resolved: https://github.com/hexojs/hexo/issues/2675
Issue resolved: https://github.com/hexojs/hexo/issues/4468
Issue resolved: https://github.com/hexojs/hexo/issues/4774
Issue resolved: https://github.com/hexojs/hexo/issues/5056
Issue resolved: https://github.com/next-theme/hexo-pangu/issues/4

fix(post): skip before_post_render and after_post_render on non-posts

---

lib/plugins/filter/before_post_render/titlecase.js
test/scripts/filters/titlecase.js

Add an option called `no_titlecase` to disable `titlecase` in a single post.
_None._

feat: add an option to disable titlecase in post

---

package.json

I'm going to release `v7.0.0-rc1`
Thank you :)

release: `v7.0.0-rc1`

---

lib/hexo/default_config.ts
lib/plugins/highlight/prism.ts
test/scripts/filters/backtick_code_block.js

see #4939 
work in hexo-theme-next

feat: add exclude_languages feature to prismjs

---

package.json

release: `v7.0.0-rc2`

---

lib/models/post.ts
lib/plugins/processor/post.ts
test/scripts/models/post.js
test/scripts/processors/post.js

Issue resolved: https://github.com/hexojs/hexo/issues/5239

feat(post): remove front-matter property `link`

---

package.json

release: v7.0.0

---

package.json

https://github.com/hexojs/hexo/compare/v7.0.0...master

release: 7.1.0

---

package.json

because of #5401, we need a patch

release: 7.1.1

---

README.md

Remove invalid picture
Add the image of `Sponsors` from `opencollective`

docs(README): Update Sponsors images

---

.github/workflows/benchmark.yml
.github/workflows/commenter.yml

Suppress comment err ,
reduce benchmark running

ci: suppress comment err and reduce benchmark running

---

package.json
test/scripts/console/new.ts

add test case for #4334
Supersedes #5117

test: add test case for issue #4334

---

package.json

https://github.com/hexojs/hexo/compare/v7.1.1...master
https://github.com/hexojs/hexo/compare/v7.1.1...v7.2.0

release: 7.2.0

---

.github/workflows/commenter.yml

I'm sorry that I introduced a bug in #5454, which caused commenter [stop running](https://github.com/hexojs/hexo/actions/runs/8735536659) to comment "how to test".
Now it will be fixed.

ci(comment): fix wrong condition

---

.github/workflows/linter.yml
.github/workflows/tester.yml
tsconfig.json

build: upgrade ecmascript version

---

package.json

resolve #5557
~- [] Add test cases for the changes.~

chore(deps-dev): bump @types/node to ^20.16.10

---

lib/plugins/helper/open_graph.ts
test/scripts/helpers/open_graph.ts

* See: https://github.com/hexojs/hexo/issues/5458
Issue resolved: https://github.com/hexojs/hexo/issues/5458

fix(open_graph): sort the tags

---

lib/plugins/tag/code.ts
lib/plugins/tag/include_code.ts
test/scripts/tags/code.ts
test/scripts/tags/include_code.ts

Escape HTML in title of `code` and `include_code` tags

Escape HTML in title of `code` and `include_code` tags
